import crypto from 'node:crypto';
import { autoDetect, audit, finishInstallation, integrationStatus, normalizeEmail, readState, roles, workflowStages, writeState } from './lib/storage.mjs';
import { generatedPermissions, loadModules } from './lib/module-registry.mjs';
function json(statusCode, body, extra = {}) { return { statusCode, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...extra }, body: JSON.stringify(body) }; }
function pathOf(event) { return (event.rawUrl ? new URL(event.rawUrl).pathname : event.path || '/').replace(/^\/\.netlify\/functions\/api/, '').replace(/^\/api/, '') || '/'; }
function parse(event) { try { return event.body ? JSON.parse(event.body) : {}; } catch { return {}; } }
function requireInstalled(state) { return state.installation_complete ? null : json(423, { ok:false, code:'INSTALL_REQUIRED', redirect:'/install/', message:'Installation is not complete.' }); }
function seedWorkflow(state, actor='system') {
  if (state.workflow.length) return state.workflow[0];
  const now = new Date().toISOString();
  const customer = { id: crypto.randomUUID(), name:'Example Client', email:'client@example.com', status:'active', createdAt:now };
  const request = { id: crypto.randomUUID(), customerId:customer.id, title:'Kitchen outlet repair', status:'client_request', active:true, createdAt:now };
  const estimate = { id: crypto.randomUUID(), requestId:request.id, source:'manual', status:'estimate_ready', total:275 };
  const quote = { id: crypto.randomUUID(), requestId:request.id, status:'quote_sent', total:325, publicUrl:`/quote/${request.id}` };
  const workOrder = { id: crypto.randomUUID(), quoteId:quote.id, status:'work_scheduled', assignedTo:null, active:true };
  const invoice = { id: crypto.randomUUID(), workOrderId:workOrder.id, status:'payment_pending', total:325, publicUrl:`/invoice/${workOrder.id}` };
  state.records.customers.push(customer); state.records.requests.push(request); state.records.estimates.push(estimate); state.records.quotes.push(quote); state.records.workOrders.push(workOrder); state.records.invoices.push(invoice);
  const wf = { id: crypto.randomUUID(), requestId: request.id, currentStage:'quote_sent', stages: workflowStages, history:[{ at:now, actor, stage:'client_request' },{ at:now, actor, stage:'estimate_ready' },{ at:now, actor, stage:'quote_sent' }] };
  state.workflow.push(wf); audit(state, actor, 'workflow.seeded', { requestId: request.id }); return wf;
}
export async function handler(event) {
  try {
    const method = event.httpMethod || event.method || 'GET';
    const path = pathOf(event);
    let state = readState();
    if (path === '/install-status' && method === 'GET') return json(200, { ok:true, installation_complete: state.installation_complete, redirect: state.installation_complete ? '/dashboard/' : '/install/' });
    if (path === '/install/health' && method === 'GET') return json(200, { ok:true, installable:true, node:'20', storage:'json-file-with-postgres-ready-adapter', optionalIntegrations: integrationStatus(), detected: autoDetect(state), warnings: integrationStatus().filter(i => !i.configured).map(i => i.message) });
    if (path === '/install/draft' && method === 'GET') return json(200, { ok:true, draft: { ...autoDetect(state), ...state.installDraft } });
    if (path === '/install/draft' && method === 'POST') { state.installDraft = { ...state.installDraft, ...parse(event), updatedAt:new Date().toISOString() }; audit(state, state.installDraft.ownerEmail, 'installation.draft_saved'); writeState(state); return json(200, { ok:true, draft: state.installDraft }); }
    if (path === '/install/finish' && method === 'POST') { state = finishInstallation(parse(event)); return json(200, { ok:true, redirect:'/dashboard/', installation_complete:true, bootstrap: state.bootstrap }); }
    const lock = requireInstalled(state); if (lock) return lock;
    if (path === '/bootstrap' && method === 'GET') return json(200, { ok:true, bootstrap: state.bootstrap, installation_complete:true });
    if (path === '/modules' && method === 'GET') return json(200, { ok:true, modules: loadModules(), permissions: generatedPermissions() });
    if (path.startsWith('/modules/') && method === 'GET') { const id = path.split('/')[2]; const module = loadModules().find(m => m.id === id); return module ? json(200,{ok:true,module, records: state.records[id] || []}) : json(404,{ok:false,message:'Module not found'}); }
    if (path === '/dashboard' && method === 'GET') return json(200, { ok:true, headline:'Welcome to Your New Business Platform', checklist:['Create First Client','Create First Request','Create First Quote','Create First Work Order','View Homepage','Open System Center'], health:{ modules: state.modules.length, integrations: integrationStatus(), activeWorkflows: state.workflow.filter(w => !['closed_archived'].includes(w.currentStage)).length } });
    if (path === '/system/integrations' && method === 'GET') return json(200, { ok:true, integrations: integrationStatus(), manualMode:true });
    if (path === '/auth/magic-link' && method === 'POST') { const { email } = parse(event); const normalized = normalizeEmail(email); if (!process.env.RESEND_API_KEY && !process.env.SMTP_HOST) return json(200, { ok:false, code:'EMAIL_NOT_CONFIGURED', message:'Email not configured yet. Configure Resend or SMTP in System Center later.', canContinueManually:true }); const raw = crypto.randomBytes(24).toString('hex'); const token = { id:crypto.randomUUID(), email:normalized, hash:crypto.createHash('sha256').update(raw).digest('hex'), expiresAt:new Date(Date.now()+15*60*1000).toISOString(), used:false }; state.magicTokens.push(token); audit(state, normalized, 'auth.magic_link_created'); writeState(state); return json(200,{ok:true,message:'Magic link created.', devLink:`/account/setup?token=${raw}`}); }
    if (path === '/auth/consume' && method === 'POST') { const { token, email } = parse(event); const hash = crypto.createHash('sha256').update(String(token||'')).digest('hex'); const found = state.magicTokens.find(t => t.hash === hash && !t.used); if (!found || new Date(found.expiresAt) < new Date()) return json(401,{ok:false,message:'Magic link is invalid or expired.'}); found.used = true; let user = state.users.find(u => u.email === found.email || u.email === normalizeEmail(email)); if (!user) { user = { id:crypto.randomUUID(), email:found.email, roles:['client'], status:'setup_required', createdAt:new Date().toISOString() }; state.users.push(user); } const session = { id:crypto.randomUUID(), userId:user.id, expiresAt:new Date(Date.now()+7*864e5).toISOString() }; state.sessions.push(session); audit(state, user.email, 'auth.session_created'); writeState(state); return json(200,{ok:true, session, user, redirect: user.status === 'setup_required' ? '/account/setup' : '/dashboard/'}); }
    if (path === '/account/setup' && method === 'POST') { const body = parse(event); const email = normalizeEmail(body.email); let user = state.users.find(u => u.email === email); if (!user) { user = { id:crypto.randomUUID(), email, roles:['client'], createdAt:new Date().toISOString() }; state.users.push(user); } Object.assign(user, { name:body.name, phone:body.phone, contactPermission:Boolean(body.contactPermission), company:body.company||'', propertyAddress:body.propertyAddress||'', preferredContactMethod:body.preferredContactMethod||'email', notes:body.notes||'', status:'active' }); for (const list of Object.values(state.records)) if (Array.isArray(list)) list.forEach(r => { if (normalizeEmail(r.email) === email || normalizeEmail(r.customerEmail) === email) r.userId = user.id; }); audit(state, email, 'account.setup_completed'); writeState(state); return json(200,{ok:true,user,redirect:'/portal/client/'}); }
    if (path === '/impersonate' && method === 'POST') { const body = parse(event); const entry = { id:crypto.randomUUID(), actor:body.actor||'owner', targetUserId:body.targetUserId, at:new Date().toISOString(), reason:body.reason||'testing/support' }; state.impersonations.unshift(entry); audit(state, entry.actor, 'user.impersonation_started', entry); writeState(state); return json(200,{ok:true,impersonation:entry}); }
    if (path === '/view-switch' && method === 'POST') { const body = parse(event); if (!roles.includes(body.workspace)) return json(400,{ok:false,message:'Unknown workspace'}); audit(state, body.actor||'owner', 'workspace.switched', { workspace:body.workspace }); writeState(state); return json(200,{ok:true,workspace:body.workspace}); }
    if (path === '/workflow/demo' && method === 'POST') { const wf = seedWorkflow(state, 'demo'); writeState(state); return json(200,{ok:true,workflow:wf,records:state.records}); }
    if (path === '/workflow/advance' && method === 'POST') { const body = parse(event); let wf = state.workflow.find(w => w.id === body.workflowId) || seedWorkflow(state, body.actor); const target = body.stage || workflowStages[Math.min(workflowStages.indexOf(wf.currentStage)+1, workflowStages.length-1)]; if (!workflowStages.includes(target)) return json(400,{ok:false,message:'Invalid workflow stage'}); wf.currentStage = target; wf.history.push({ at:new Date().toISOString(), actor:body.actor||'system', stage:target }); if (target === 'payment_verified' || target === 'closed_archived') { state.records.workOrders.forEach(w => { if (target === 'closed_archived') w.active = false; }); state.records.invoices.forEach(i => { if (target === 'payment_verified') i.status = 'paid'; }); } audit(state, body.actor, 'workflow.advanced', { stage:target }); writeState(state); return json(200,{ok:true,workflow:wf}); }
    if (path === '/ai/estimate' && method === 'POST') return json(200,{ok:true, mode:process.env.OPENAI_API_KEY?'ai':'manual', warning:process.env.OPENAI_API_KEY?null:'OpenAI not configured; returned manual estimate template.', estimate:{ laborHours:2, materials:75, total:275, confidence:'manual-review-required' }});
    if (path === '/ai/quote' && method === 'POST') return json(200,{ok:true, mode:process.env.OPENAI_API_KEY?'ai':'manual', quote:{ lineItems:[{name:'Labor',qty:2,price:100},{name:'Materials allowance',qty:1,price:75}], total:275, reviewRequired:true }});
    if (path === '/ai/troubleshoot' && method === 'POST') return json(200,{ok:true, mode:process.env.OPENAI_API_KEY?'ai':'manual', steps:['Confirm symptoms','Check power/water/gas safety','Capture photos','Escalate to technician if unresolved']});
    if (path.startsWith('/public/quote/') && method === 'GET') return json(200,{ok:true, quote: state.records.quotes.find(q => q.id === path.split('/').pop()) || { status:'available', actions:['accept','request_changes'] }});
    if (path.startsWith('/public/invoice/') && method === 'GET') return json(200,{ok:true, invoice: state.records.invoices.find(i => i.id === path.split('/').pop()) || { status:'payment_pending', paymentOptions:['square_link_when_configured','manual_payment'] }});
    return json(404, { ok:false, message:'API route not found', path });
  } catch (error) { return json(500, { ok:false, message:'A handled platform error occurred.', detail:error.message }); }
}
