import crypto from 'node:crypto';

let dbDepsPromise;
let appDepsPromise;
let appDepsLoaded;
async function loadDbDeps(){
 if(!dbDepsPromise) dbDepsPromise=import('./shared/db.mjs');
 return dbDepsPromise;
}
async function loadAppDeps(){
 if(!appDepsPromise) appDepsPromise=Promise.all([
  loadDbDeps(),
  import('./shared/seed.mjs'),
  import('./shared/env-metadata.mjs'),
  import('./shared/core-data.mjs'),
  import('./shared/workflow.mjs')
 ]).then(([db,seed,env,core,workflow])=>{ appDepsLoaded={...db,...seed,...env,...core,...workflow}; return appDepsLoaded; });
 return appDepsPromise;
}
const json=(statusCode,body)=>({statusCode,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(body)});
const parse=(event)=> event.body ? JSON.parse(event.body) : {};
const clean=(r)=>JSON.parse(JSON.stringify(r));
const safeDatabaseMessage='A database URL was found, but the connection failed.';
const databaseCheckingMessage='No database connection URL was found.';
const databaseMissingMessage='Database connection not detected.\n\nOnce a Netlify Database is linked to this site, the installer will automatically create all required tables and seed records.\n\nOpen Netlify → Storage → Database, create or link a database, then click Retry Database Check.';
const bootstrapMissingMessage='No database connection was detected. Link a Netlify Database, then retry.';
const netlifyDatabaseGuide=['Open Netlify dashboard.','Go to Storage → Database.','Create or link a database.','Redeploy if Netlify asks.','Click Retry Database Check.'];
function dbNotConfigured(message=databaseMissingMessage, extra={}){ return {ok:false,installed:false,needsInstall:true,safeMode:true,code:'NO_DATABASE_URL',state:'NO_DATABASE_URL',message,canRetry:true,manualDatabaseLinkRequired:true,manualSetupRequired:true,canBootstrapSchema:false,runtimeProvisioningSupported:false,netlifyRuntimeCanProvisionDatabase:false,memoryFallbackAllowed:false,nextAction:'Link a Netlify Database, then click Retry Database Check.',netlifyDatabaseDetected:false,guide:netlifyDatabaseGuide,...extra}; }
function dbManualRequired(message=databaseMissingMessage, extra={}){ return {ok:false,installed:false,needsInstall:true,safeMode:true,code:'MANUAL_DATABASE_LINK_REQUIRED',state:'MANUAL_DATABASE_LINK_REQUIRED',message,canRetry:true,manualDatabaseLinkRequired:true,manualSetupRequired:true,canBootstrapSchema:false,runtimeProvisioningSupported:false,netlifyRuntimeCanProvisionDatabase:false,nextAction:'Link a Netlify Database, then click Retry.',netlifyDatabaseDetected:false,guide:netlifyDatabaseGuide,...extra}; }
function dbUnavailable(message=safeDatabaseMessage, extra={}){ return {ok:false,installed:false,needsInstall:true,safeMode:true,code:'DATABASE_CONNECTION_FAILED',state:'DATABASE_CONNECTION_FAILED',message,canRetry:true,manualDatabaseLinkRequired:false,manualSetupRequired:false,canBootstrapSchema:false,runtimeProvisioningSupported:false,netlifyRuntimeCanProvisionDatabase:false,netlifyDatabaseDetected:true,...extra}; }
function validationFailed(message, missing=[], goToStep='review'){ return {ok:false,code:'INSTALL_VALIDATION_FAILED',message,missing,goToStep}; }
function isDatabaseError(error){ return ['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','MANUAL_DATABASE_LINK_REQUIRED','DATABASE_MANUAL_LINK_REQUIRED','DATABASE_UNAVAILABLE','DATABASE_CONNECTION_FAILED','DATABASE_CLIENT_MISSING','DATABASE_DRIVER_LOAD_FAILED','DATABASE_DRIVER_MISSING','NETLIFY_DATABASE_REQUIRED'].includes(error?.code)||/database|postgres|connection|pg|relation|schema|migration|module|import|package/i.test(error?.message||''); }
async function bootstrapInstallerDatabase(){
 const { ensureSchema, seedInstallerPrerequisites, verifyRequiredTables, sql }=await loadAppDeps();
 const db=sql();
 const migrations=await ensureSchema(db);
 await seedInstallerPrerequisites(db);
 const tableCheck=await verifyRequiredTables(db);
 return {db,migrations,tableCheck};
}
async function withDb(fn){ const { db }=await bootstrapInstallerDatabase(); return fn(db); }
async function tryInstallDb(fn, failureBody){
 try{ return await withDb(fn); }catch(error){
  if(['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','NETLIFY_DATABASE_REQUIRED'].includes(error?.code)) return json(200,{...dbNotConfigured(undefined,{draft:failureBody.draft,goToStep:failureBody.goToStep}),databaseError:error.message});
  if(isDatabaseError(error)) return json(200,{...failureBody,code:failureBody.code||'DATABASE_DRIVER_LOAD_FAILED',databaseError:error.message});
  throw error;
 }
}
async function databaseHealth(){
 let deps;
 try{ deps=await loadDbDeps(); }catch(error){
  return {configured:false,reachable:false,driverPackage:'pg',clientPackage:'@netlify/database',driverLoaded:false,clientLoaded:false,driverError:error.message,error:`Database support could not be loaded: ${error.message}`,env:[]};
 }
 const { sql, getDatabaseUrl, configuredDatabaseUrl, databaseEnvStatus, databaseClientPackage, databaseDriverPackage, loadNetlifyDatabaseClientResult, loadDatabaseDriverResult }=deps;
 const configured=!!getDatabaseUrl(); const configuredEnv=configuredDatabaseUrl?.();
 if(!configured) return {configured:false,reachable:false,databaseConnected:false,schemaReady:false,state:'NO_DATABASE_URL',code:'NO_DATABASE_URL',clientPackage:databaseClientPackage,driverPackage:databaseDriverPackage,clientLoaded:false,driverLoaded:false,driverError:null,error:'No database connection URL was found.',env:databaseEnvStatus(),requiresDatabase:true,manualDatabaseLinkRequired:true,manualSetupRequired:true,canBootstrapSchema:false};
 const clientResult=loadNetlifyDatabaseClientResult();
 const clientLoaded=!!clientResult.ok;
 const clientError=clientResult.ok?null:(clientResult.details||clientResult.message);
 if(!clientLoaded) return {configured:true,configuredEnv:configuredEnv?.key,reachable:false,databaseConnected:false,schemaReady:false,state:'DATABASE_CLIENT_MISSING',clientPackage:databaseClientPackage,driverPackage:databaseDriverPackage,clientLoaded,driverLoaded:false,driverError:null,clientError,error:clientError,env:databaseEnvStatus(),code:'DATABASE_CLIENT_MISSING'};
 const driverResult=loadDatabaseDriverResult();
 const driverLoaded=!!driverResult.ok;
 const driverError=driverResult.ok?null:(driverResult.details||driverResult.message);
 if(!driverLoaded) return {configured:true,configuredEnv:configuredEnv?.key,reachable:false,databaseConnected:false,schemaReady:false,state:'DATABASE_DRIVER_MISSING',clientPackage:databaseClientPackage,driverPackage:databaseDriverPackage,clientLoaded,driverLoaded,driverError,error:driverError,env:databaseEnvStatus(),code:'DATABASE_DRIVER_MISSING'};
 try{
  const bootstrapped=await bootstrapInstallerDatabase();
  const { migrations, tableCheck }=bootstrapped;
  const [row]=await sql()`select true as reachable`;
  return {configured:true,configuredEnv:configuredEnv?.key,reachable:!!row?.reachable,databaseConnected:!!row?.reachable,schemaReady:!!row?.reachable,state:'SCHEMA_READY',code:'SCHEMA_READY',clientPackage:databaseClientPackage,driverPackage:databaseDriverPackage,clientLoaded,driverLoaded,driverError:null,error:null,env:databaseEnvStatus(),migrations,tables:tableCheck.tables,seedReady:!!row?.reachable,bootstrapAtStartup:true};
 }catch(error){
  return {configured:true,configuredEnv:configuredEnv?.key,reachable:false,databaseConnected:false,schemaReady:false,state:'DATABASE_CONNECTION_FAILED',clientPackage:databaseClientPackage,driverPackage:databaseDriverPackage,clientLoaded,driverLoaded,driverError:null,error:error.message,env:databaseEnvStatus(),code:'DATABASE_CONNECTION_FAILED',safeDetails:error?.code||error?.name||'Connection attempt failed'};
 }
}
function pathOf(event){ return ('/'+(event.path||'').replace(/^\/\.netlify\/functions\/api/,'').replace(/^\/api/,'')).replace(/\/+/g,'/'); }
async function list(db, table, active=true){ const where= active ? ` where coalesce(status,'active') not in ('workflow.closed','workflow.archived','quote.accepted','invoice.paid')` : ''; return db.unsafe(`select * from ${table}${where} order by created_at desc limit 200`); }
async function createCrud(db, table, body, defaults={}){ const data={...defaults,...body}; const keys=Object.keys(data).filter(k=>data[k]!==undefined); const values=keys.map(k=>data[k]); const cols=keys.map(k=>`"${k}"`).join(','); const params=keys.map((_,i)=>`$${i+1}`).join(','); const rows=await db.unsafe(`insert into ${table}(${cols}) values(${params}) returning *`,values); await appDepsLoaded?.audit?.(`${table}.create`,{id:rows[0].id},table,rows[0].id); return rows[0]; }
async function updateCrud(db, table, id, body){ const keys=Object.keys(body).filter(k=>!['id','created_at','updated_at'].includes(k)); if(!keys.length) return (await db.unsafe(`select * from ${table} where id=$1`,[id]))[0]; const sets=keys.map((k,i)=>`"${k}"=$${i+1}`).join(','); const rows=await db.unsafe(`update ${table} set ${sets}, updated_at=now() where id=$${keys.length+1} returning *`,[...keys.map(k=>body[k]),id]); await appDepsLoaded?.audit?.(`${table}.update`,{id},table,id); return rows[0]; }
export const handler=async(event)=>{ try{
 const method=event.httpMethod; const path=pathOf(event);
 if(path==='/install-status') {
  const health=await databaseHealth();
  if(!health.reachable) return json(200,{...(health.requiresDatabase?dbNotConfigured():dbUnavailable()),installation_complete:false,draft:{},completed_at:null,databaseConfigured:health.configured,databaseReachable:false,databaseError:health.error,clientPackage:health.clientPackage,driverPackage:health.driverPackage,clientLoaded:health.clientLoaded,clientError:health.clientError,driverLoaded:health.driverLoaded,driverError:health.driverError,env:health.env,manualDatabaseLinkRequired:health.manualDatabaseLinkRequired||false,manualSetupRequired:health.manualSetupRequired||false,canBootstrapSchema:health.canBootstrapSchema||false,schemaReady:false,state:health.state||health.code});
  const { sql }=await loadDbDeps();
  const db=sql();
  const rows=await db`select installation_complete, installer_draft, completed_at from platform_installation where id='default'`;
  const complete=!!rows[0]?.installation_complete;
  return json(200,{ok:true,installed:complete,needsInstall:!complete,installation_complete:complete,draft:rows[0]?.installer_draft||{},completed_at:rows[0]?.completed_at||null,databaseConfigured:true,databaseReachable:true,databaseConnected:true,schemaReady:true,state:'SCHEMA_READY',code:'SCHEMA_READY',database:'ok',netlifyDatabaseDetected:true,driverPackage:health.driverPackage,driverLoaded:health.driverLoaded,env:health.env,migrations:health.migrations});
 }
 if(path==='/install/health') {
  const health=await databaseHealth();
  const body=health.reachable?{ok:true,code:'SCHEMA_READY',state:'SCHEMA_READY',message:'Database schema is ready.',database:'ok',databaseConnected:true,schemaReady:true,canBootstrapSchema:true}:(health.requiresDatabase?dbNotConfigured():dbUnavailable(health.code==='DATABASE_CLIENT_MISSING'?'Database client package is missing from package.json.':(health.code==='DATABASE_DRIVER_MISSING'?'Database driver is missing.':'A database URL was found, but the connection failed.'),{code:health.code,state:health.state,safeDetails:health.safeDetails}));
  return json(200,{...body,safeMode:!health.reachable,databaseConfigured:health.configured,databaseReachable:health.reachable,databaseConnected:health.databaseConnected||false,schemaReady:health.schemaReady||false,netlifyDatabaseDetected:health.configured,databaseError:health.error||null,clientPackage:health.clientPackage,driverPackage:health.driverPackage,clientLoaded:health.clientLoaded,clientError:health.clientError,driverLoaded:health.driverLoaded,driverError:health.driverError,env:health.env,guide:body.manualSetupRequired?netlifyDatabaseGuide:undefined,needsInstall:!health.reachable,migrations:health.migrations});
 }
 if(path==='/install/bootstrap-database' && method==='POST') {
  const health=await databaseHealth();
  if(health.reachable) { const { verifyDatabaseWrites, sql }=await loadAppDeps(); const writeTest=await verifyDatabaseWrites(sql()); return json(200,{ok:true,code:'SCHEMA_READY',state:'SCHEMA_READY',databaseConnected:true,schemaReady:true,canBootstrapSchema:true,message:'Database schema is ready and write verification passed.',database:'ok',databaseConfigured:true,databaseReachable:true,migrations:health.migrations,tables:health.tables,writeTest,attemptedAutomaticBootstrap:true}); }
  if(health.requiresDatabase) return json(200,{...dbNotConfigured(bootstrapMissingMessage),databaseConfigured:false,databaseReachable:false,databaseConnected:false,schemaReady:false,databaseError:health.error,env:health.env,attemptedAutomaticBootstrap:true});
  return json(200,{...dbUnavailable(health.code==='DATABASE_CLIENT_MISSING'?'Database client package is missing from package.json.':(health.code==='DATABASE_DRIVER_MISSING'?'Database driver is missing.':'A database URL was found, but the connection failed.'),{code:health.code,state:health.state,safeDetails:health.safeDetails}),databaseConfigured:health.configured,databaseReachable:false,databaseConnected:false,schemaReady:false,databaseError:health.error,clientPackage:health.clientPackage,driverPackage:health.driverPackage,clientLoaded:health.clientLoaded,clientError:health.clientError,driverLoaded:health.driverLoaded,driverError:health.driverError,env:health.env,attemptedAutomaticBootstrap:true});
 }
 if(path==='/install/draft' && method==='GET') return await tryInstallDb(async db=>{ const rows=await db`select installer_draft from platform_installation where id='default'`; return json(200,{ok:true,draft:rows[0]?.installer_draft||{}}); }, dbUnavailable('Automatic bootstrap could not load installer draft.',{draft:{}}));
 if(path==='/install/draft' && method==='POST') return await tryInstallDb(async db=>{ const body=parse(event); await db`insert into platform_installation(id,installer_draft) values('default',${db.json(body)}) on conflict(id) do update set installer_draft=platform_installation.installer_draft || excluded.installer_draft, updated_at=now()`; await db`insert into installer_drafts(id,draft) values('default',${db.json(body)}) on conflict(id) do update set draft=installer_drafts.draft || excluded.draft, updated_at=now()`; return json(200,{ok:true,draft:body}); }, dbUnavailable('Automatic bootstrap could not save installer draft.'));
 if(['/install/integration-status','/system/integration-status','/install/env-status'].includes(path)) { const { integrationStatus }=await loadAppDeps(); return json(200,{ok:true,integrations:integrationStatus(),variables:integrationStatus()}); }
 if(path==='/install/finish' && method==='POST') { const body=parse(event); const missing=[]; if(!body.owner?.email && !body.company?.email) missing.push('owner_account'); if(missing.length) return json(200,validationFailed('Owner account is missing.',missing,'owner')); const { seedPlatform, verifyDatabaseWrites }=await loadAppDeps(); return await tryInstallDb(async db=>{ const preflightWriteTest=await verifyDatabaseWrites(db); await seedPlatform(db,body); const finalWriteTest=await verifyDatabaseWrites(db); const checks=await db`select (select count(*) from app_users) users,(select count(*) from roles) roles,(select count(*) from permissions) permissions,(select count(*) from role_permissions) role_permissions,(select count(*) from workspace_access) workspace_access,(select count(*) from module_registry) modules,(select count(*) from service_categories) service_categories,(select count(*) from company_settings where id='default') company_settings,(select count(*) from homepage_settings where id='default') homepage_settings,(select count(*) from theme_settings where id='default') theme_settings,(select installation_complete from platform_installation where id='default') complete`; const c=checks[0]; if(!c.complete||Number(c.company_settings)<1||Number(c.homepage_settings)<1||Number(c.theme_settings)<1||Number(c.users)<1||Number(c.roles)<5||Number(c.permissions)<25||Number(c.role_permissions)<25||Number(c.workspace_access)<5||Number(c.modules)<25||Number(c.service_categories)<8) return json(200,{ok:false,code:'INSTALL_VALIDATION_FAILED',message:'Install validation failed after database writes.',checks:c,goToStep:'review'}); return json(200,{ok:true,redirect:'/dashboard/',checks:c,writeTest:{preflight:preflightWriteTest,final:finalWriteTest}}); }, dbUnavailable('Automatic bootstrap failed while creating the platform.',{goToStep:'review'})); }
 const { audit, seedPlatform, integrationStatus, modules, roles, permissions, transition, assertTransition }=await loadAppDeps();
 if(path==='/bootstrap') return await withDb(async db=>{ const [company]=await db`select * from company_settings where id='default'`; const mods=await db`select * from module_registry where enabled=true order by group_name,label`; return json(200,{ok:true,company:company||null,modules:mods.length?mods:modules,roles:Object.keys(roles)}); });
 if(path==='/modules') return await withDb(async db=>json(200,{ok:true,modules:await db`select * from module_registry order by group_name,label`}));
 if(path==='/dashboard/summary') return await withDb(async db=>{ const [row]=await db`select (select count(*) from customers where status='active') customers,(select count(*) from estimate_requests where status not in ('workflow.closed','workflow.archived')) requests,(select count(*) from quotes where status not in ('quote.accepted','workflow.archived')) quotes,(select count(*) from work_orders where status not in ('workflow.closed','workflow.archived')) work_orders,(select count(*) from invoices where status not in ('invoice.paid','workflow.archived')) invoices_due,(select coalesce(sum(total-paid_total),0) from invoices where status <> 'invoice.paid') outstanding`; const activity=await db`select action, entity_type, created_at from audit_logs order by created_at desc limit 10`; return json(200,{ok:true,stats:row,activity,quickStart:['Create first client','Create first request','Create first quote','Schedule a work order','Send an invoice','Configure integrations']}); });
 if(path==='/auth/magic-link' && method==='POST') return await withDb(async db=>{ const {email}=parse(event); const normalized=String(email||'').trim().toLowerCase(); if(!normalized.includes('@')) return json(400,{ok:false,error:'Enter a valid email address.'}); const token=crypto.randomBytes(24).toString('hex'); const tokenHash=crypto.createHash('sha256').update(token).digest('hex'); await db`insert into magic_link_tokens(normalized_email, token_hash, expires_at) values(${normalized},${tokenHash},now()+interval '30 minutes')`; await audit('auth.magic_link.requested',{email:normalized,emailConfigured:Boolean(process.env.RESEND_API_KEY)}); return json(200,{ok:true,emailConfigured:Boolean(process.env.RESEND_API_KEY),message:process.env.RESEND_API_KEY?'Magic link queued.':'Email not configured yet. Use owner setup mode or configure Resend in System Center.',devLink:process.env.RESEND_API_KEY?undefined:`/login/?token=${token}&email=${encodeURIComponent(normalized)}`}); });
 if(path==='/auth/verify' && method==='POST') return await withDb(async db=>{ const {email,token}=parse(event); const normalized=String(email||'').trim().toLowerCase(); const tokenHash=crypto.createHash('sha256').update(String(token||'')).digest('hex'); const rows=await db`update magic_link_tokens set used_at=now() where normalized_email=${normalized} and token_hash=${tokenHash} and used_at is null and expires_at>now() returning id`; if(!rows.length) return json(401,{ok:false,error:'Expired or invalid login link.'}); let users=await db`select * from app_users where normalized_email=${normalized}`; if(!users.length) users=await db`insert into app_users(full_name,email,normalized_email,active) values(${normalized.split('@')[0]},${normalized},${normalized},true) returning *`; return json(200,{ok:true,user:users[0],session:{role:'client',expiresAt:new Date(Date.now()+86400000).toISOString()}}); });
 const parts=path.split('/').filter(Boolean);
 const resource=parts[0]; const id=parts[1]; const tableMap={customers:'customers',requests:'estimate_requests',quotes:'quotes','work-orders':'work_orders',inventory:'inventory_items',invoices:'invoices',payments:'payments',files:'files',users:'app_users',audit:'audit_logs'};
 if(tableMap[resource]) return await withDb(async db=>{ const table=tableMap[resource]; if(method==='GET'&&!id) return json(200,{ok:true,items:clean(await list(db,table,resource!=='audit'))}); if(method==='GET'&&id) return json(200,{ok:true,item:(await db.unsafe(`select * from ${table} where id=$1`,[id]))[0]||null}); if(method==='POST'&&!id){ const body=parse(event); let row; if(resource==='quotes' && body.request_id){ const req=(await db`select * from estimate_requests where id=${body.request_id}`)[0]; row=await createCrud(db,table,{...body,customer_id:body.customer_id||req?.customer_id,title:body.title||`Quote for ${req?.service_category||'Service'}`},{line_items:body.line_items||[]}); await transition(db,{entityType:'request',entityId:body.request_id,fromStatus:req.status,toStatus:'quote.draft'}); }
 else if(resource==='work-orders' && body.quote_id){ const q=(await db`select * from quotes where id=${body.quote_id}`)[0]; if(q?.status!=='quote.accepted') await transition(db,{entityType:'quote',entityId:body.quote_id,fromStatus:q.status,toStatus:'quote.accepted'}); row=await createCrud(db,table,{...body,customer_id:body.customer_id||q?.customer_id,title:body.title||q?.title||'Work Order'}); }
 else if(resource==='invoices' && body.work_order_id){ const wo=(await db`select * from work_orders where id=${body.work_order_id}`)[0]; row=await createCrud(db,table,{...body,customer_id:body.customer_id||wo?.customer_id,title:body.title||`Invoice: ${wo?.title||'Work'}`}); }
 else row=await createCrud(db,table,body); return json(201,{ok:true,item:clean(row)}); }
 if(method==='PATCH'&&id) return json(200,{ok:true,item:clean(await updateCrud(db,table,id,parse(event)))});
 if(method==='DELETE'&&id){ const status= resource==='customers'?'archived':'workflow.archived'; await db.unsafe(`update ${table} set status=$1, updated_at=now() where id=$2`,[status,id]); await audit(`${table}.archive`,{id},table,id); return json(200,{ok:true}); }
 });
 if(path==='/workflow/transition'&&method==='POST') return await withDb(async db=>{ const body=parse(event); const current=(await db.unsafe(`select status from ${({request:'estimate_requests',quote:'quotes',work_order:'work_orders',invoice:'invoices'}[body.entityType])} where id=$1`,[body.entityId]))[0]; assertTransition(current.status,body.toStatus); await transition(db,{...body,fromStatus:current.status}); return json(200,{ok:true}); });
 if(path==='/ai/run'&&method==='POST') return json(200,{ok:!!process.env.OPENAI_API_KEY,configured:!!process.env.OPENAI_API_KEY,message:process.env.OPENAI_API_KEY?'AI request accepted.':'AI is not configured yet. Configure OpenAI in System Center → Environment & Integrations.'});
 if(path==='/health') return await withDb(async db=>{ const [counts]=await db`select (select count(*) from module_registry) modules,(select count(*) from roles) roles,(select count(*) from permissions) permissions`; return json(200,{ok:true,database:true,counts,integrations:integrationStatus().map(i=>({key:i.key,configured:i.configured,category:i.category}))}); });
 return json(404,{ok:false,error:'API route not found',path});
 }catch(err){ const path=pathOf(event); if(path.startsWith('/install')||path==='/install-status') return json(200,{ok:false,code:['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','NETLIFY_DATABASE_REQUIRED'].includes(err?.code)?'NO_DATABASE_URL':(isDatabaseError(err)?'DATABASE_CONNECTION_FAILED':'INSTALL_API_ERROR'),state:['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','NETLIFY_DATABASE_REQUIRED'].includes(err?.code)?'NO_DATABASE_URL':(isDatabaseError(err)?'DATABASE_CONNECTION_FAILED':'INSTALL_API_ERROR'),message:['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','NETLIFY_DATABASE_REQUIRED'].includes(err?.code)?databaseCheckingMessage:(isDatabaseError(err)?safeDatabaseMessage:(err.message||'Unexpected installer API error')),safeMode:true,canRetry:true,manualDatabaseLinkRequired:['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','NETLIFY_DATABASE_REQUIRED'].includes(err?.code),manualSetupRequired:['NO_DATABASE_URL','DATABASE_NOT_CONFIGURED','NETLIFY_DATABASE_REQUIRED'].includes(err?.code),databaseError:isDatabaseError(err)?err.message:undefined}); return json(err.statusCode||500,{ok:false,error:err.message||'Unexpected error'}); }};
