import { promises as fs } from 'fs';
import { json, readJson, SECRET_KEYS, redact } from './shared/json.mjs';
import { readState, writeState, defaultTheme, defaultHomepage, publicBootstrap, now } from './shared/store.mjs';
import { ENV_METADATA, envStatusFromProcess } from './shared/env-metadata.mjs';
async function registry(){try{return JSON.parse(await fs.readFile('public/generated/module-registry.json','utf8')).modules}catch{return []}}
function seedRoles(){return [{key:'owner',name:'Owner',hierarchy:100},{key:'admin',name:'Admin',hierarchy:80},{key:'manager',name:'Manager',hierarchy:60},{key:'worker',name:'Worker',hierarchy:30},{key:'client',name:'Client',hierarchy:10}]}
function pathOf(event){return (event.path||'').replace(/^\/api\/install\/?/,'')||''}
export async function handler(event){try{const p=pathOf(event); const method=event.httpMethod||'GET'; const state=await readState();
 if(p==='health'&&method==='GET'){const mods=await registry(); const env=ENV_METADATA.map(m=>({...m,...redact(process.env[m.key]||state.env?.[m.key]?.value), setupSteps:m.setupSteps})); return json(200,{ok:true,data:{database:{ok:true,provider:process.env.NETLIFY_DATABASE_URL?'netlify_database':'local_safe_store'},migrations:{ok:true},functions:{ok:true},bootstrap:{ok:!!state.installation.bootstrap_generated},moduleRegistry:{ok:mods.length>0,count:mods.length},environment:env},safeMode:false});}
 if(p==='draft'&&method==='GET') return json(200,{ok:true,data:{draft:state.draft||{},currentStep:state.installation.current_step}});
 if(p==='draft'&&method==='POST'){const body=await readJson(event); state.draft={...(state.draft||{}),...(body.draft||{})}; state.installation.current_step=body.currentStep||state.installation.current_step; state.installation.updated_at=now(); await writeState(state); return json(200,{ok:true,data:{draft:state.draft,currentStep:state.installation.current_step}});}
 if(p==='finish'&&method==='POST'){const body=await readJson(event); if(!body.confirm) return json(400,{ok:false,code:'CONFIRM_REQUIRED',message:'Finish Install requires confirmation.',missing:['confirm']}); const draft={...(state.draft||{}),...(body.draft||{})}; const missing=[]; if(!draft.companyName) missing.push('company_profile'); if(!draft.ownerName||!draft.ownerEmail) missing.push('owner_account'); if(missing.length) return json(422,{ok:false,code:'INSTALL_VALIDATION_FAILED',message:'Required installer steps are missing.',missing}); const mods=await registry(); state.company={companyName:draft.companyName,displayName:draft.companyName,phone:draft.phone,supportEmail:draft.supportEmail,serviceArea:draft.serviceArea,websiteUrl:draft.SITE_URL||process.env.SITE_URL||null}; state.theme={...defaultTheme(),...Object.fromEntries(Object.entries(draft).filter(([k,v])=>['mode','primary','accent','background','surface','text','border','button','buttonText','sidebarBackground','sidebarText','sidebarActiveBackground','sidebarActiveText','sidebarHoverBackground','mobileNavBackground','mobileNavActive','mobileNavText'].includes(k)&&v))}; state.homepage={...defaultHomepage(),hero:{headline:draft.heroHeadline||defaultHomepage().hero.headline,subheadline:draft.heroSubheadline||defaultHomepage().hero.subheadline}}; state.services=(draft.services||defaultHomepage().services.join(',')).split(',').map(s=>s.trim()).filter(Boolean); state.users=[{id:'owner-local',fullName:draft.ownerName,email:draft.ownerEmail,phone:draft.ownerPhone,roles:['owner'],active:true}]; state.roles=seedRoles(); state.permissions=mods.flatMap(m=>(m.permissions||[]).map(p=>({...p,moduleId:m.id}))); state.modules=mods.map(m=>({...m,enabled:true})); for(const [k,v] of Object.entries(draft)){if(ENV_METADATA.some(e=>e.key===k)&&v){state.env[k]=SECRET_KEYS.has(k)?{status:'configured',lastFour:String(v).slice(-4)}:{status:'configured',value:v};}}
 state.auditLogs.push({action:'installer.completed',actor:'owner-local',createdAt:now(),metadata:{modules:mods.length}}); state.installation={...state.installation,installation_complete:true,installed_version:'1.0.0',installed_at:now(),installed_by_user_id:'owner-local',current_step:'complete',bootstrap_generated:true,updated_at:now()}; await fs.mkdir('public/config',{recursive:true}); await fs.writeFile('public/config/bootstrap.json',JSON.stringify(publicBootstrap(state),null,2)); try{await fs.mkdir('out/config',{recursive:true}); await fs.writeFile('out/config/bootstrap.json',JSON.stringify(publicBootstrap(state),null,2));}catch{} await writeState(state); return json(200,{ok:true,installationComplete:true,redirectTo:'/dashboard/'});}
 return json(404,{ok:false,code:'INSTALL_ROUTE_NOT_FOUND',message:'Install route not found.'});
}catch(e){return json(200,{ok:false,needsInstall:true,safeMode:true,code:'INSTALL_SAFE_ERROR',message:'Setup can continue in recovery mode.',nextAction:'Open recovery mode'});}}
