import { clean, getSessionToken, hashToken, json, loadDatabase, parseJsonBody, validateEmail } from './auth-utils.mjs';
import { ensureCompanyTables } from './company-settings.mjs';

const permissions = ['dashboard.view.owner','dashboard.view.admin','dashboard.view.manager','dashboard.view.client','dashboard.view.worker','users.manage','users.create','users.edit','users.deactivate','roles.manage','roles.create','roles.edit','roles.delete','ranks.manage','ranks.create','ranks.edit','ranks.delete','permissions.manage','company.manage','branding.manage','requests.manage','quotes.manage','quotes.create','quotes.edit','quotes.send','quotes.delete','workorders.create','invoices.create','invoices.manage','inventory.manage','customers.manage','workers.manage','scheduling.manage','ai.quote.use','ai.quote.manage','ai.troubleshooting.use','ai.knowledge.manage','reports.view','settings.manage','admin.tools','client.tools','worker.tools','admin.users.manage','admin.roles.manage','admin.requests.manage','admin.quotes.manage','admin.invoices.manage','admin.inventory.manage','dashboard.switch_views'];
const roles = ['owner','admin','manager','worker','client','guest'];
const services = ['HVAC','Water Heaters','Plumbing','Electrical','Drywall','Painting','Doors','Windows','Appliances','Handyman','Facilities Maintenance','Property Maintenance','Commercial Maintenance','General Contracting','Tenant Improvements'];
const serviceKey = (name = '') => clean(name, 120).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'service';
const statuses = ['request_new','request_info_needed','quote_draft','quote_sent','quote_changes_requested','quote_declined','quote_accepted','quote_converted','work_order_created','waiting_assignment','assigned','scheduled','in_progress','worker_completed','admin_review','client_review','invoice_ready','invoice_sent','payment_pending','paid','payment_verified','closed','archived','cancelled'];

const tableSeeds = async (db) => {
  await db.sql`create extension if not exists pgcrypto`;
  await db.sql`alter table roles drop constraint if exists roles_key_check`;
  await db.sql`alter table roles add column if not exists is_system boolean not null default false`;
  await db.sql`alter table roles add column if not exists updated_at timestamptz not null default now()`;
  await db.sql`create table if not exists permissions (key text primary key, label text, description text, category text, created_at timestamptz not null default now())`;
  await db.sql`create table if not exists role_permissions (role_id uuid not null references roles(id) on delete cascade, permission_key text not null, enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (role_id, permission_key))`;
  await db.sql`create table if not exists ranks (id uuid primary key default gen_random_uuid(), key text not null unique, name text not null, description text, is_system boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`create table if not exists rank_permissions (rank_id uuid not null references ranks(id) on delete cascade, permission_key text not null, enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (rank_id, permission_key))`;
  await db.sql`create table if not exists user_ranks (user_id uuid not null references app_users(id) on delete cascade, rank_id uuid not null references ranks(id) on delete cascade, created_at timestamptz not null default now(), primary key (user_id, rank_id))`;
  await db.sql`create table if not exists service_categories (id uuid primary key default gen_random_uuid(), category_key text unique, name text not null unique, description text, enabled boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`alter table service_categories add column if not exists category_key text`;
  await db.sql`alter table service_categories add column if not exists description text`;
  await db.sql`alter table service_categories add column if not exists sort_order integer not null default 0`;
  await db.sql`create table if not exists quote_settings (id uuid primary key default gen_random_uuid(), settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`create table if not exists ai_settings (id uuid primary key default gen_random_uuid(), settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`create table if not exists cmms_settings (id uuid primary key default gen_random_uuid(), statuses jsonb not null default '[]'::jsonb, settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`create table if not exists invoice_settings (id uuid primary key default gen_random_uuid(), settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`create table if not exists trade_intelligence_categories (id uuid primary key default gen_random_uuid(), trade text not null unique, library jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
  await db.sql`create table if not exists module_registry (id text primary key, role_key text not null, title text not null, nav_label text not null, permissions jsonb not null default '[]'::jsonb, enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`;
};

const ownerAllowedMaintenance = async (db, request, body = {}) => {
  if (process.env.ALLOW_REINSTALL === 'true') return true;
  const url = new URL(request.url);
  const unlock = process.env.INSTALLER_UNLOCK_TOKEN;
  if (unlock && url.searchParams.get('installer_unlock_token') === unlock) return true;
  if (url.searchParams.get('maintenance') !== '1') return false;
  const token = getSessionToken(request); if (!token) return false;
  const rows = await db.sql`select 1 from auth_sessions join user_roles on user_roles.user_id=auth_sessions.user_id join roles on roles.id=user_roles.role_id where auth_sessions.session_hash=${hashToken(token)} and roles.key='owner' and auth_sessions.revoked_at is null and auth_sessions.expires_at > now() limit 1`;
  return rows.length > 0 && clean(body?.confirmation, 80) === 'RESET INSTALLER';
};

const tradeLibrary = (trade) => { const hvac = trade === 'HVAC'; return ({ requiredInfo: ['site address','requested scope or symptoms','access conditions','safety concerns'], helpfulInfo: hvac ? ['photos','model numbers','measurements','preferred materials/brand','mini split / split system / heat pump / package unit details','furnace, air handler, thermostat, controls, ductwork, IAQ, condensate, and filter details'] : ['photos','model numbers','measurements','preferred materials/brand'], commonQuestions: [`What details are known for ${trade}?`, hvac ? 'For ductless or split-system work, do you know BTU size, voltage, line-set route, and condensate routing?' : 'Are photos available?', 'Is access restricted?', 'Is this urgent or scheduled maintenance?'], commonMaterials: hvac ? ['HVAC equipment','thermostats/controls','ductwork and registers','condensate parts','filters','line sets and pads','standard materials','consumables'] : ['standard materials','trade-specific parts','consumables','disposal/haul-off'], laborRules: hvac ? ['apply minimum charge','include troubleshooting or maintenance labor','include repair/replacement/installation setup','adjust for access, attic/roof work, line-set route, and urgency'] : ['apply minimum charge','include travel/setup','adjust for access and urgency','flag permit/inspection time'], safetyNotes: ['verify site safety','de-energize or isolate hazards','escalate licensed/safety hazards'], permitNotes: ['review permit requirements where applicable'], inspectionNotes: ['document before/after and completion evidence'], pricingRiskFactors: hvac ? ['hidden damage','old equipment','unknown measurements','refrigerant or electrical surprises','condensate routing','after-hours or restricted access'] : ['hidden damage','old equipment','unknown measurements','after-hours or restricted access'], missingInfoPrompts: ['Ask only optional follow-up questions; Admin may continue manually.'] }); };
const title = (key) => key.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
const categoryFor = (permission) => permission.split('.')[0];
const bool = (value, fallback = true) => value === undefined ? fallback : Boolean(value);

export default async (request) => {
  if (request.method !== 'POST') return json(405, { ok: false, message: 'Method not allowed.' });
  const body = await parseJsonBody(request); if (!body) return json(400, { ok: false, message: 'Request body must be valid JSON.' });
  const companyName = clean(body.companyName, 160); const ownerEmail = clean(body.ownerEmail, 254).toLowerCase();
  if (!companyName) return json(422, { ok: false, message: 'Company Name is required.' });
  const emailError = validateEmail(ownerEmail); if (emailError) return json(422, { ok: false, message: emailError });
  try {
    const db = await loadDatabase(); await ensureCompanyTables(db); await tableSeeds(db);
    const [existingInstall] = await db.sql`select installed, installer_locked from platform_install order by created_at desc limit 1`;
    const [existingCompany] = await db.sql`select installation_complete from company_settings order by created_at asc limit 1`;
    if ((existingInstall?.installed || existingCompany?.installation_complete) && !(await ownerAllowedMaintenance(db, request, body))) return json(409, { ok: false, installed: true, message: 'Installation already completed. Public installer is locked.' });
    await db.sql`delete from company_settings`;
    const [company] = await db.sql`insert into company_settings (company_name, legal_name, display_name, website_url, support_email, support_phone, business_phone, business_address, city, state, zip, service_area, timezone, currency, license_number, contractor_license_number, tax_id, business_type, logo_url, favicon_url, primary_color, accent_color, background_color, surface_color, text_color, button_color, success_color, warning_color, danger_color, theme_mode, default_theme, enable_theme_toggle, show_company_name_in_header, installation_complete) values (${companyName}, ${clean(body.legalName,180)||null}, ${clean(body.displayName,160)||companyName}, ${clean(body.websiteUrl,300)||null}, ${clean(body.supportEmail,254)||null}, ${clean(body.supportPhone,60)||null}, ${clean(body.businessPhone,60)||null}, ${clean(body.businessAddress,300)||null}, ${clean(body.city,120)||null}, ${clean(body.state,60)||null}, ${clean(body.zip,40)||null}, ${clean(body.serviceArea,500)||null}, ${clean(body.timezone,80)||'America/Phoenix'}, ${clean(body.currency,8)||'USD'}, ${clean(body.licenseNumber,120)||null}, ${clean(body.contractorLicenseNumber,120)||null}, ${clean(body.taxId,120)||null}, ${clean(body.businessType,120)||null}, ${clean(body.logoUrl,700)||null}, ${clean(body.faviconUrl,700)||null}, ${clean(body.primaryColor,32)||'#2563eb'}, ${clean(body.accentColor,32)||'#22c55e'}, ${clean(body.backgroundColor,32)||'#f8fafc'}, ${clean(body.surfaceColor,32)||'#ffffff'}, ${clean(body.textColor,32)||'#0f172a'}, ${clean(body.buttonColor,32)||clean(body.primaryColor,32)||'#2563eb'}, ${clean(body.successColor,32)||'#16a34a'}, ${clean(body.warningColor,32)||'#f59e0b'}, ${clean(body.dangerColor,32)||'#dc2626'}, ${clean(body.themeMode,20)||'system'}, ${clean(body.defaultTheme,20)||clean(body.themeMode,20)||'system'}, ${bool(body.enableThemeToggle, true)}, ${Boolean(body.showCompanyNameInHeader)}, true) returning *`;
    const licenseKey = clean(body.licenseKey || body.license_key, 240);
    const licenseValidationEnabled = bool(body.licenseValidationEnabled || body.license_validation_enabled, false);
    const licenseProvider = clean(process.env.LICENSE_VERIFY_URL ? 'external' : body.licenseVerificationProvider, 120) || null;
    let licenseStatus = licenseKey ? 'verification_disabled' : 'not_configured';
    let licenseVerifiedAt = null;
    if (licenseValidationEnabled) {
      if (!process.env.LICENSE_VERIFY_URL || !process.env.LICENSE_VERIFY_TOKEN) return json(503, { ok: false, message: 'License validation is enabled but LICENSE_VERIFY_URL or LICENSE_VERIFY_TOKEN is not configured server-side.' });
      const verifyResponse = await fetch(process.env.LICENSE_VERIFY_URL, { method: 'POST', headers: { 'content-type': 'application/json', authorization: `Bearer ${process.env.LICENSE_VERIFY_TOKEN}` }, body: JSON.stringify({ licenseKey }) });
      const verifyBody = await verifyResponse.json().catch(() => ({}));
      if (!verifyResponse.ok || verifyBody.active !== true) return json(403, { ok: false, message: 'License verification failed. Confirm the license is active before completing setup.' });
      licenseStatus = 'active';
      licenseVerifiedAt = new Date().toISOString();
    }
    await db.sql`update company_settings set license_key=${licenseKey || null}, license_status=${licenseStatus}, license_verified_at=${licenseVerifiedAt}::timestamptz, license_verification_provider=${licenseProvider}, license_validation_enabled=${licenseValidationEnabled}, updated_at=now() where id=${company.id}`;
    const selectedPermissions = Array.isArray(body.permissions) && body.permissions.length ? body.permissions.filter((permission) => permissions.includes(permission)) : permissions;
    const [owner] = await db.sql`insert into app_users (auth_provider, auth_subject, email, full_name, phone, is_active) values ('magic_link', ${ownerEmail}, ${ownerEmail}, ${clean(body.ownerFullName,140)||ownerEmail}, ${clean(body.ownerPhone,60)||null}, true) on conflict (email) do update set full_name=excluded.full_name, phone=excluded.phone, is_active=true, updated_at=now() returning id, email`;
    for (const role of roles) {
      await db.sql`insert into roles (key,name,description,is_system) values (${role}, ${title(role)}, ${title(role) + ' role/rank'}, true) on conflict (key) do update set name=excluded.name, description=excluded.description, is_system=true, updated_at=now()`;
      await db.sql`insert into ranks (key,name,description,is_system) values (${role}, ${title(role)}, ${title(role) + ' rank alias'}, true) on conflict (key) do update set name=excluded.name, description=excluded.description, is_system=true, updated_at=now()`;
    }
    for (const permission of permissions) await db.sql`insert into permissions (key,label,description,category) values (${permission}, ${permission}, ${'Permission: ' + permission}, ${categoryFor(permission)}) on conflict (key) do update set label=excluded.label, description=excluded.description, category=excluded.category`;
    const roleRows = (await db.sql`select id,key from roles`).filter((r) => roles.includes(r.key));
    const rankRows = (await db.sql`select id,key from ranks`).filter((r) => roles.includes(r.key));
    for (const role of roleRows) {
      const granted = role.key === 'owner' ? permissions : role.key === 'admin' ? selectedPermissions.filter((p)=>!p.includes('ranks.delete')) : role.key === 'manager' ? ['dashboard.view.admin','requests.manage','quotes.manage','quotes.create','quotes.edit','workorders.create','invoices.create','scheduling.manage','customers.manage','workers.manage','invoices.manage','ai.quote.use'].filter((p)=>selectedPermissions.includes(p)) : role.key === 'worker' ? ['dashboard.view.worker','worker.tools','ai.troubleshooting.use'].filter((p)=>selectedPermissions.includes(p)) : role.key === 'client' ? ['dashboard.view.client','client.tools'].filter((p)=>selectedPermissions.includes(p)) : [];
      for (const permission of granted) await db.sql`insert into role_permissions (role_id, permission_key, enabled) values (${role.id}, ${permission}, true) on conflict (role_id, permission_key) do update set enabled=true, updated_at=now()`;
      if (role.key === 'owner') await db.sql`insert into user_roles (user_id, role_id) values (${owner.id}, ${role.id}) on conflict do nothing`;
    }
    for (const rank of rankRows) if (rank.key === 'owner') await db.sql`insert into user_ranks (user_id, rank_id) values (${owner.id}, ${rank.id}) on conflict do nothing`;
    for (const service of (Array.isArray(body.serviceCategories) && body.serviceCategories.length ? body.serviceCategories : services)) {
      const serviceName = clean(service, 120);
      const categoryKey = serviceKey(serviceName);
      await db.sql`update service_categories set category_key=${categoryKey}, enabled=true, updated_at=now() where category_key=${categoryKey} or lower(name)=lower(${serviceName})`;
      await db.sql`insert into service_categories (category_key, name, enabled) select ${categoryKey}, ${serviceName}, true where not exists (select 1 from service_categories where category_key=${categoryKey} or lower(name)=lower(${serviceName}))`;
    }
    await db.sql`insert into quote_settings (settings) values (${JSON.stringify({ defaultLaborRate: Number(body.defaultLaborRate || 95), defaultMarkupPercentage: Number(body.defaultMarkupPercentage || 25), defaultMaterialMarkup: Number(body.defaultMaterialMarkup || 25), defaultTripCharge: Number(body.defaultTripCharge || 75), defaultTaxRate: Number(body.defaultTaxRate || 0), defaultMinimumJobPrice: Number(body.defaultMinimumJobPrice || 175), defaultQuoteExpirationDays: Number(body.defaultQuoteExpirationDays || 14), adminManualOverride: true })}::jsonb)`;
    await db.sql`insert into ai_settings (settings) values (${JSON.stringify({ enableAiQuoting: bool(body.enableAiQuoting, true), enableFollowUpQuestions: bool(body.enableFollowUpQuestions, true), enableInformationNeededQueue: bool(body.enableInformationNeededQueue, true), requireAdminReview: bool(body.requireAdminReview, true), aiNeverBlocksAdmin: true, openAiApiKey: 'OPENAI_API_KEY server-side only' })}::jsonb)`;
    await db.sql`insert into cmms_settings (statuses, settings) values (${JSON.stringify(statuses)}::jsonb, ${JSON.stringify({ enableWorkerAssignments: bool(body.enableWorkerAssignments, true), enableScheduling: bool(body.enableScheduling, true), enablePhotos: bool(body.enablePhotos, true), enableMaterialTracking: bool(body.enableMaterialTracking, true), enableInventoryReservations: bool(body.enableInventoryReservations, true), enableCustomerApproval: bool(body.enableCustomerApproval, true), enableInvoiceReadiness: bool(body.enableInvoiceReadiness, true) })}::jsonb)`;
    await db.sql`insert into invoice_settings (settings) values (${JSON.stringify({ enableInvoices: bool(body.enableInvoices, true), enableSquarePaymentLinks: bool(body.enableSquarePaymentLinks, true), defaultInvoiceDueDays: Number(body.defaultInvoiceDueDays || 14), defaultPaymentTerms: clean(body.defaultPaymentTerms,200) || 'Due on receipt', defaultTaxRate: Number(body.invoiceDefaultTaxRate || 0), defaultInvoiceFooter: clean(body.defaultInvoiceFooter,500) || 'Thank you for your business.', enableManualPaymentConfirmation: true, enablePaidUnpaidTracking: true, squareVariablesPreserved: ['SQUARE_ACCESS_TOKEN','SQUARE_API_VERSION','SQUARE_ENVIRONMENT','SQUARE_LOCATION_ID','SQUARE_WEBHOOK_SIGNATURE_KEY'] })}::jsonb)`;
    for (const service of services) await db.sql`insert into trade_intelligence_categories (trade, library) values (${service}, ${JSON.stringify(tradeLibrary(service))}::jsonb) on conflict (trade) do update set library=excluded.library, updated_at=now()`;
    const modules = ['admin.overview','admin.quotes','admin.work-orders','admin.schedule','admin.customers','admin.invoices','admin.finance','admin.inventory','admin.users','admin.roles','admin.ai-knowledge','admin.reports','admin.brand-settings','admin.settings','client.overview','client.requests','client.quotes','client.invoices','client.project-updates','client.profile','client.properties','worker.overview','worker.jobs','worker.schedule','worker.materials','worker.photos','worker.notes','worker.troubleshooting'];
    for (const id of modules) { const [role, slug] = id.split('.'); await db.sql`insert into module_registry (id, role_key, title, nav_label, permissions) values (${id}, ${role}, ${title(slug)}, ${title(slug)}, ${JSON.stringify([])}::jsonb) on conflict (id) do update set title=excluded.title, nav_label=excluded.nav_label, enabled=true, updated_at=now()`; }
    await db.sql`insert into platform_install (installed, installed_at, installed_by_user_id, version, setup_summary, installer_locked, locked_at, license_key, license_status, license_verified_at, license_verification_provider, license_validation_enabled) values (true, now(), ${owner.id}, 'clean-white-label-v1', ${JSON.stringify({ companyName, ownerEmail, roles, permissions, services, statuses, environment: { openai: 'OPENAI_API_KEY server-side only', resend: 'RESEND_API_KEY/MAGIC_LINK_FROM_EMAIL/QUOTE_FROM_EMAIL preserved', siteUrls: 'SITE_URL/SITE_URL_ALIASES preserved', square: 'Square variables preserved' } })}::jsonb, true, now(), ${licenseKey || null}, ${licenseStatus}, ${licenseVerifiedAt}::timestamptz, ${licenseProvider}, ${licenseValidationEnabled})`;
    return json(200, { ok: true, companyId: company.id, ownerId: owner.id, redirect: '/login/' });
  } catch (error) { console.error('install failed', error); return json(500, { ok: false, message: 'Installation failed. Check database configuration and migrations.' }); }
};
