-- Core installer, identity, role, permission, module, and configuration schema.
-- Runtime schema creation is idempotently mirrored in netlify/functions/shared/db.mjs.
create extension if not exists pgcrypto;
create table if not exists platform_installation (id text primary key default 'default', installation_complete boolean not null default false, installer_draft jsonb not null default '{}'::jsonb, recovery_mode boolean not null default false, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists company_settings (id text primary key default 'default', company_name text not null default 'Contractor Platform', logo_url text, phone text, email text, address text, theme jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists homepage_settings (id text primary key default 'default', content jsonb not null default '{}'::jsonb, published boolean not null default true, updated_at timestamptz not null default now());
create table if not exists app_users (id uuid primary key default gen_random_uuid(), full_name text not null, email text not null unique, normalized_email text not null unique, phone text, company text, preferred_contact_method text, contact_permission boolean not null default true, active boolean not null default true, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists roles (id uuid primary key default gen_random_uuid(), key text not null unique, label text not null, description text, created_at timestamptz not null default now());
create table if not exists permissions (id uuid primary key default gen_random_uuid(), key text not null unique, label text not null, created_at timestamptz not null default now());
create table if not exists role_permissions (role_key text not null references roles(key) on delete cascade, permission_key text not null references permissions(key) on delete cascade, primary key(role_key, permission_key));
create table if not exists user_roles (user_id uuid not null references app_users(id) on delete cascade, role_key text not null references roles(key) on delete cascade, primary key(user_id, role_key));
create table if not exists workspace_access (user_id uuid not null references app_users(id) on delete cascade, workspace text not null, role_key text not null, primary key(user_id, workspace));
create table if not exists module_registry (id text primary key, label text not null, group_name text not null, icon text, route text not null, permission_key text, enabled boolean not null default true, manifest jsonb not null default '{}'::jsonb, version text not null default '1.0.0', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists module_settings (module_id text primary key references module_registry(id) on delete cascade, settings jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists service_categories (id uuid primary key default gen_random_uuid(), name text not null unique, active boolean not null default true, created_at timestamptz not null default now());
