-- Core CMMS persistence and shared workflow/audit tables.
create table if not exists customers (id uuid primary key default gen_random_uuid(), name text not null, email text, phone text, status text not null default 'active', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists customer_properties (id uuid primary key default gen_random_uuid(), customer_id uuid references customers(id) on delete cascade, label text not null default 'Primary', address text not null, created_at timestamptz not null default now());
create table if not exists estimate_requests (id uuid primary key default gen_random_uuid(), customer_id uuid references customers(id), service_category text, address text, priority text not null default 'normal', notes text, status text not null default 'request.new', photos jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists quotes (id uuid primary key default gen_random_uuid(), request_id uuid references estimate_requests(id), customer_id uuid references customers(id), title text not null, status text not null default 'quote.draft', line_items jsonb not null default '[]'::jsonb, subtotal numeric not null default 0, tax numeric not null default 0, total numeric not null default 0, share_token text unique default encode(gen_random_bytes(16), 'hex'), accepted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists work_orders (id uuid primary key default gen_random_uuid(), quote_id uuid references quotes(id), customer_id uuid references customers(id), assigned_user_id uuid references app_users(id), title text not null, status text not null default 'work_order.ready_to_assign', priority text not null default 'normal', scheduled_start timestamptz, scheduled_end timestamptz, notes text, completion_notes text, materials_used jsonb not null default '[]'::jsonb, photos jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inventory_items (id uuid primary key default gen_random_uuid(), sku text, name text not null, quantity numeric not null default 0, reorder_level numeric not null default 0, location text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inventory_transactions (id uuid primary key default gen_random_uuid(), item_id uuid references inventory_items(id), work_order_id uuid references work_orders(id), type text not null, quantity numeric not null, notes text, created_at timestamptz not null default now());
create table if not exists invoices (id uuid primary key default gen_random_uuid(), work_order_id uuid references work_orders(id), customer_id uuid references customers(id), title text not null, status text not null default 'invoice.draft', line_items jsonb not null default '[]'::jsonb, subtotal numeric not null default 0, tax numeric not null default 0, total numeric not null default 0, paid_total numeric not null default 0, due_at date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists payments (id uuid primary key default gen_random_uuid(), invoice_id uuid references invoices(id), amount numeric not null, method text not null default 'manual', status text not null default 'payment.verified', reference text, created_at timestamptz not null default now());
create table if not exists files (id uuid primary key default gen_random_uuid(), owner_type text not null, owner_id uuid, file_name text not null, content_type text, url text, visibility text not null default 'private', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists workflow_events (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, from_status text, to_status text not null, actor_id uuid, notes text, created_at timestamptz not null default now());
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid, action text not null, entity_type text, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
