import { readFile } from 'node:fs/promises';
import test from 'node:test';
import assert from 'node:assert/strict';

const loadDashboardHtml = () => readFile(new URL('../public/dashboard/index.html', import.meta.url), 'utf8');
const extractInlineScripts = (html) => [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((match) => match[1]);

test('dashboard inline scripts parse without duplicate declarations', async () => {
  const html = await loadDashboardHtml();
  const scripts = extractInlineScripts(html);

  assert.ok(scripts.length > 0, 'expected at least one inline dashboard script');
  scripts.forEach((script) => assert.doesNotThrow(() => new Function(script)));
});

test('dashboard user and role controls have their required handlers', async () => {
  const html = await loadDashboardHtml();
  const [script] = extractInlineScripts(html);

  assert.match(html, /data-request-estimate-link/, 'dashboard request estimate link should target the in-dashboard request form');
  assert.doesNotMatch(html, /href="\/login\/">Client Portal/, 'signed-in dashboard nav should not show the Client Portal link');
  assert.match(html, /data-client-edit-property/, 'clients should have an edit action for saved properties');
  assert.match(html, /data-client-property-modal/, 'property edits should open in a dedicated popup instead of the request form');
  assert.match(html, /My profile &amp; properties|My profile & properties/, 'profile section should organize contact info and properties together');
  assert.match(html, /data-profile-button/, 'top navigation should expose a My Profile button');
  assert.match(html, /data-client-profile-form/, 'clients should have an editable profile form');
  assert.match(html, /data-client-request-edit-form/, 'clients should be able to edit open job requests in a modal');
  assert.match(html, /data-admin-assignment-form/, 'admins should have a worker assignment form');
  assert.match(html, /data-admin-pipeline-summary/, 'admins should have a work order pipeline summary');
  assert.match(html, /data-admin-request-search/, 'admins should be able to search work orders');
  assert.match(html, /data-admin-request-status-filter/, 'admins should be able to filter work orders by status');
  assert.match(html, /data-admin-request-scope-filter/, 'admins should switch between active and completed work order views');
  assert.match(html, /data-admin-work-order-summary/, 'admins should have a work order detail summary panel');
  assert.match(html, /data-admin-quote-id/, 'admin quote form should edit saved quotes by id');
  assert.match(html, /data-client-approve-completion/, 'clients should be able to approve completed work');
  assert.match(html, /value="pending_review"/, 'admins should be able to verify pending-review work');
  assert.doesNotMatch(html, /Secure portal gate/, 'dashboard should not show implementation placeholder cards');
  assert.doesNotMatch(html, /Use one magic-link sign-in/, 'dashboard hero should use production-facing copy');
  assert.match(html, /data-worker-jobs/, 'workers should have an assigned jobs dashboard section');
  assert.match(html, /data-client-invoices/, 'clients should have an invoices and payments dashboard section');
  assert.match(html, /data-admin-invoices/, 'admins should have a payment confirmation dashboard section');
  assert.match(html, /data-admin-activity/, 'admins should have a recent activity audit section');
  assert.match(html, /data-admin-activity-type-filter/, 'admins should filter recent activity by type');
  assert.match(html, /data-admin-activity-search/, 'admins should search recent activity');
  assert.match(html, /data-admin-invoice-summary/, 'admins should have invoice totals before payment confirmation');
  assert.match(html, /data-admin-invoice-status-filter/, 'admins should switch between open and paid invoice views');
  assert.match(html, /data-admin-invoice-search/, 'admins should search invoice records');
  assert.match(html, /data-admin-role-select/, 'role manager should use a single role selector');
  assert.match(html, /data-admin-open-selected-role/, 'selected role edit button should be present');
  assert.doesNotMatch(html, /data-admin-role-list/, 'roles should not render as a separate card list');
  assert.match(script, /const saveClientProfile =/, 'clients should be able to save profile changes');
  assert.match(script, /const bindClientProfileButton =/, 'top My Profile button should open the profile modal');
  assert.match(script, /const bindClientProfileForm =/, 'client profile form should be bound');
  assert.match(script, /const saveClientRequestUpdate =/, 'clients should be able to update an open request');
  assert.match(script, /const approveClientCompletion =/, 'clients should have completed-work approval handler');
  assert.match(script, /quoteMethod = payload.quoteId \? 'PATCH' : 'POST'/, 'saved quotes should be edited instead of recreated');
  assert.match(script, /canSwitchDashboardView && \(user\.roles \|\| \[\]\)\.includes\('admin'\)/, 'role view tabs should be admin-only');
  assert.match(script, /const loadClientInvoices =/, 'clients should load open invoices');
  assert.match(script, /const loadAdminInvoices =/, 'admins should load invoices awaiting payment confirmation');
  assert.match(script, /const renderAdminInvoiceSummary =/, 'admins should render invoice totals');
  assert.match(script, /const renderAdminActivityCard =/, 'admins should render recent audit activity');
  assert.match(script, /const renderAdminActivityList =/, 'admins should render filtered audit activity');
  assert.match(script, /const bindAdminActivityFilters =/, 'admins should bind activity filters');
  assert.match(script, /const loadAdminActivity =/, 'admins should load recent audit activity');
  assert.match(script, /const renderAdminInvoiceList =/, 'admins should render filtered invoice records');
  assert.match(script, /status=\$\{encodeURIComponent\(filter\)\}/, 'admin invoice loading should request the selected invoice status');
  assert.match(script, /const renderAdminPipelineSummary =/, 'admins should render pipeline counts');
  assert.match(script, /const applyAdminRequestFilters =/, 'admins should filter the work order inbox');
  assert.match(script, /currentAdminRequestScope = result\.scope \|\| scope/, 'admin work order view should track the API scope');
  assert.match(script, /scope=\$\{encodeURIComponent\(scope\)\}/, 'admin work order loading should request the selected scope');
  assert.match(script, /fetch\('\/api\/admin\/activity'/, 'admin activity should load from the audit activity endpoint');
  assert.match(script, /const renderAdminWorkOrderSummary =/, 'admins should render a CMMS-style work order summary');
  assert.match(script, /data-admin-work-order-summary-card/, 'work order summary should render a dedicated summary card');
  assert.match(script, /data-admin-confirm-payment/, 'admins should be able to confirm payment from the dashboard');
  assert.match(script, /data-admin-payment-form/, 'admins should capture payment confirmation details from the dashboard');
  assert.match(script, /reference: formData\.get\('reference'\)/, 'admin payment confirmations should send payment reference notes');
  assert.match(script, /invoiceSearch\?\.addEventListener\('input', renderAdminInvoiceList\)/, 'admin invoice search should filter without refetching');
  assert.match(script, /const loadWorkerJobs =/, 'workers should load assigned jobs');
  assert.match(script, /const bindWorkerJobActions =/, 'worker job update controls should be bound');
  assert.match(script, /const saveClientProperty =/, 'clients should be able to save property changes');
  assert.match(script, /const bindClientPropertyActions =/, 'client property edit controls should be bound');
  assert.match(script, /const renderUserProperties =/, 'opening a user profile requires the property renderer to be declared');
  assert.match(script, /renderUserProperties\(user\.properties \|\| \[\]\)/, 'user profile opening should render saved addresses');
  assert.ok(html.indexOf('data-client-profile-form') < html.indexOf('data-client-properties'), 'client properties should live inside/after the profile form, not as a separate earlier section');
});
