BEGIN;
INSERT INTO permissions (key, group_name, description) VALUES
('dashboard.view','dashboard','View dashboard'),('dashboard.manage','dashboard','Manage dashboard'),('settings.view','settings','View settings'),('settings.manage','settings','Manage settings'),('users.view','users','View users'),('users.manage','users','Manage users'),('roles.view','roles','View roles'),('roles.manage','roles','Manage roles'),('permissions.view','permissions','View permissions'),('permissions.manage','permissions','Manage permissions'),('clients.view','clients','View clients'),('clients.manage','clients','Manage clients'),('properties.view','properties','View properties'),('properties.manage','properties','Manage properties'),('requests.view','requests','View requests'),('requests.manage','requests','Manage requests'),('quotes.view','quotes','View quotes'),('quotes.create','quotes','Create quotes'),('quotes.approve','quotes','Approve quotes'),('quotes.manage','quotes','Manage quotes'),('jobs.view','jobs','View jobs'),('jobs.manage','jobs','Manage jobs'),('work_orders.view','work_orders','View work orders'),('work_orders.manage','work_orders','Manage work orders'),('invoices.view','invoices','View invoices'),('invoices.manage','invoices','Manage invoices'),('payments.view','payments','View payments'),('payments.manage','payments','Manage payments'),('cmms.view','cmms','View CMMS'),('cmms.manage','cmms','Manage CMMS'),('messages.view','messages','View messages'),('messages.manage','messages','Manage messages'),('website.view','website','View website'),('website.manage','website','Manage website'),('homepage.manage','homepage','Manage homepage'),('theme.view','theme','View theme'),('theme.manage','theme','Manage theme'),('branding.view','branding','View branding'),('branding.manage','branding','Manage branding'),('service_catalog.view','service_catalog','View service catalog'),('service_catalog.manage','service_catalog','Manage service catalog'),('media.view','media','View media'),('media.manage','media','Manage media'),('audit_logs.view','audit_logs','View audit logs'),('license.view','license','View license'),('license.manage','license','Manage license'),('expansion_packs.view','expansion_packs','View expansion packs'),('expansion_packs.manage','expansion_packs','Manage expansion packs'),('*','system','Wildcard super admin permission')
ON CONFLICT (key) DO UPDATE SET group_name = excluded.group_name, description = excluded.description;
INSERT INTO roles (name, description, system_role) VALUES
('Owner','Full system owner',true),('Admin','Administrative user',true),('Office','Office and customer operations',true),('Dispatcher','Scheduling and dispatch',true),('Technician','Field technician',true),('Client','Client portal user',true),('Vendor','External vendor',true)
ON CONFLICT (name) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name='Owner' ON CONFLICT DO NOTHING;
INSERT INTO service_categories (name, sort_order) VALUES ('HVAC',1),('Plumbing',2),('Electrical',3),('Handyman',4),('Appliance',5),('Maintenance',6),('General Repair',7) ON CONFLICT (name) DO NOTHING;
INSERT INTO theme_settings (mode, tokens, active) VALUES ('system', '{"accent":"#0f766e","radius":"18px"}', true);
INSERT INTO pages (slug, title, status) VALUES ('home','Homepage','published') ON CONFLICT (slug) DO NOTHING;
INSERT INTO payment_provider_settings (provider, enabled, key_mapping) VALUES ('square', true, '{"accessToken":"SQUARE_ACCESS_TOKEN","applicationId":"SQUARE_APPLICATION_ID","locationId":"SQUARE_LOCATION_ID"}'),('manual', true, '{}'),('stripe', false, '{}'),('paypal', false, '{}'),('authorize_net', false, '{}') ON CONFLICT (provider) DO NOTHING;
INSERT INTO expansion_packs (key, name) VALUES ('inventory','Inventory Expansion'),('workforce','Workforce Expansion'),('accounting','Accounting Expansion'),('reporting','Reporting Expansion'),('customer','Customer Expansion') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_settings (key, value) VALUES
('installation.completed', 'false'::jsonb),
('installation.version', '"1.0.0"'::jsonb)
ON CONFLICT (key) DO NOTHING;
COMMIT;
