-- 0001 Initial AI Contractor CMMS platform schema. Never edit after applying.
create table if not exists installation_settings (id boolean primary key default true, installed boolean not null default false, company jsonb not null default '{}'::jsonb, license jsonb not null default '{"validationEnabled":false,"status":"verification_disabled"}'::jsonb, completed_at timestamptz, constraint singleton_installation check (id));
create table if not exists modules (id text primary key, title text not null, version text not null, enabled boolean not null default true, manifest jsonb not null, created_at timestamptz not null default now());
create table if not exists roles (id text primary key, title text not null, permissions jsonb not null default '[]'::jsonb);
create table if not exists users (id uuid primary key default gen_random_uuid(), email text unique not null, name text, role_id text references roles(id), created_at timestamptz not null default now());
create table if not exists homepage_config (id boolean primary key default true, config jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now(), constraint singleton_homepage check (id));
create table if not exists theme_config (id boolean primary key default true, mode text not null default 'system', tokens jsonb not null default '{}'::jsonb, constraint singleton_theme check (id));
create table if not exists requests (id uuid primary key default gen_random_uuid(), client_email text not null, service text, notes text, photos jsonb not null default '[]'::jsonb, status text not null default 'Request', active boolean not null default true, created_at timestamptz not null default now());
create table if not exists ai_runs (id uuid primary key default gen_random_uuid(), request_id uuid, type text not null, model text, input jsonb not null default '{}'::jsonb, output jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists quotes (id uuid primary key default gen_random_uuid(), request_id uuid references requests(id), status text not null default 'AI Quote', total numeric(12,2) not null default 0, public_token text unique, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists work_orders (id uuid primary key default gen_random_uuid(), quote_id uuid references quotes(id), status text not null default 'Work Order', assigned_to uuid references users(id), scheduled_at timestamptz, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists inventory_items (id uuid primary key default gen_random_uuid(), sku text, name text not null, quantity numeric(12,2) not null default 0, reorder_level numeric(12,2) not null default 0);
create table if not exists invoices (id uuid primary key default gen_random_uuid(), work_order_id uuid references work_orders(id), status text not null default 'Invoice', total numeric(12,2) not null default 0, public_token text unique, square_payment_id text, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists payments (id uuid primary key default gen_random_uuid(), invoice_id uuid references invoices(id), provider text not null default 'square', status text not null default 'created', amount numeric(12,2) not null default 0, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists workflow_events (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid not null, from_state text, to_state text not null, actor_id uuid, created_at timestamptz not null default now());
insert into roles(id,title,permissions) values ('owner','Owner','["*"]'),('admin','Admin','["admin-dashboard:read","work-orders:write","quote-center:write"]'),('manager','Manager','["manager-dashboard:read","scheduling:write"]'),('worker','Worker','["worker-dashboard:read","work-orders:write"]'),('client','Client','["client-dashboard:read","client-portal:read"]') on conflict (id) do nothing;
