import { useState } from 'react';
import { AppLayout, Protected } from '../components/Layout';
import { Link } from '../components/Router';
import { defaultRoles, defaultSections, defaultWidgets, foundationComponents, permissions, sampleInvoices, sampleJobs, sampleQuotes, sampleRequests, sampleThreads, serviceCategories } from '../data/foundation';
import { getTheme, saveTheme } from '../lib/theme';
import { loadJson, saveJson } from '../lib/storage';
import type { DashboardWidget, PageSection } from '../types/domain';

export function DashboardPage() {
  const [widgets, setWidgets] = useState(loadJson<DashboardWidget[]>('contractoros.dashboard.widgets', defaultWidgets));
  const save = (next: DashboardWidget[]) => { setWidgets(next); saveJson('contractoros.dashboard.widgets', next); };
  return <Protected permission="settings.view"><AppLayout title="Dashboard"><div className="toolbar"><button className="button" onClick={() => save([...widgets, { id: crypto.randomUUID(), title: 'New widget', type: 'metric', x: 0, y: widgets.length, w: 1, h: 1 }])}>Add widget</button><p>Widgets support add, remove, move, resize, and saved user layout.</p></div><div className="dashboard-grid">{widgets.map((w, i) => <article className="card widget" key={w.id} style={{ gridColumn: `span ${w.w}` }}><input value={w.title} onChange={(e) => save(widgets.map((x) => x.id === w.id ? { ...x, title: e.target.value } : x))}/><strong>{w.type === 'metric' ? i + 1 : '•'}</strong><div className="widget-actions"><button onClick={() => save(widgets.map((x) => x.id === w.id ? { ...x, w: x.w === 1 ? 2 : 1 } : x))}>Resize</button><button onClick={() => i > 0 && save(widgets.map((x, idx, arr) => idx === i - 1 ? arr[i] : idx === i ? arr[i - 1] : x))}>Move up</button><button onClick={() => save(widgets.filter((x) => x.id !== w.id))}>Remove</button></div></article>)}</div></AppLayout></Protected>;
}

export function PortalPage() { return <AppLayout title="Client portal"><div className="grid cards"><WorkflowCard title="My properties" items={['Primary property']}/><WorkflowCard title="My requests" items={sampleRequests.map((r) => `${r.id} · ${r.status}`)}/><WorkflowCard title="My quotes" items={sampleQuotes.map((q) => `${q.id} · ${q.status}`)}/><WorkflowCard title="My invoices" items={sampleInvoices.map((i) => `${i.id} · $${i.balance}`)}/><WorkflowCard title="My messages" items={sampleThreads.map((t) => t.subject)}/></div></AppLayout>; }
function WorkflowCard({ title, items }: { title: string; items: string[] }) { return <article className="card"><h3>{title}</h3>{items.map((item) => <p key={item}>{item}</p>)}</article>; }

export function RequestsPage() { return <Protected permission="requests.view"><AppLayout title="Work requests"><Table rows={sampleRequests.map((r) => [r.id,r.client,r.service,r.status,r.priority])}/><Link href="/requests/new" className="button">New request</Link></AppLayout></Protected>; }
export function QuotesPage() { return <Protected permission="quotes.view"><AppLayout title="Quotes"><Table rows={sampleQuotes.map((q) => [q.id,q.client,q.status,`$${q.total}`])}/><div className="card"><h3>Approval workflow</h3><p>Client approval converts approved quotes to jobs and saves communication history.</p></div></AppLayout></Protected>; }
export function JobsPage() { return <Protected permission="jobs.view"><AppLayout title="Jobs and dispatch"><Table rows={sampleJobs.map((j) => [j.id,j.client,j.status,j.technician])}/></AppLayout></Protected>; }
export function InvoicesPage() { return <Protected permission="invoices.view"><AppLayout title="Invoices and payments"><Table rows={sampleInvoices.map((i) => [i.id,i.client,i.status,`$${i.balance}`])}/><div className="card"><h3>Payment framework</h3><p>Square is default; Stripe, PayPal, Authorize.net, manual cash/check, and configure-later are structured as provider adapters.</p></div></AppLayout></Protected>; }
export function MessagesPage() { return <Protected permission="messages.view"><AppLayout title="Advanced messaging"><div className="grid cards">{sampleThreads.map((t) => <article className="card" key={t.id}><h3>{t.subject}</h3><p>{t.participants.join(' ↔ ')}</p><span className="pill">{t.visibility}</span><textarea placeholder="Customer-visible reply or internal note"/></article>)}</div></AppLayout></Protected>; }
export function AssetsPage() { return <Protected permission="cmms.view"><AppLayout title="CMMS assets"><div className="card"><h3>Asset foundation</h3><p>Assets, equipment, service history, PM shell, notes, documents, and property relationships are included.</p></div></AppLayout></Protected>; }

function Table({ rows }: { rows: string[][] }) { return <div className="table">{rows.map((row) => <div className="tr" key={row.join('-')}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div>; }

export function SettingsPage({ area = 'settings' }: { area?: string }) {
  const [theme, setTheme] = useState(getTheme());
  const [sections, setSections] = useState(loadJson<PageSection[]>('contractoros.homepage.sections.draft', defaultSections));
  const publish = () => { saveJson('contractoros.homepage.sections.draft', sections); saveJson('contractoros.homepage.sections.published', sections); };
  return <Protected permission="settings.view"><AppLayout title={`Settings / ${area.replace('settings/','')}`}><div className="settings-grid"><nav className="card settings-nav">{['company','theme','users','roles','permissions','foundation','expansion-packs','payment','email','license','media','homepage-builder'].map((s) => <Link href={`/settings/${s}`} key={s}>{s}</Link>)}</nav><section className="card settings-panel">{area.endsWith('theme') ? <><h2>Theme</h2><select value={theme.mode} onChange={(e) => { const next = { ...theme, mode: e.target.value as typeof theme.mode }; setTheme(next); saveTheme(next); }}><option>system</option><option>light</option><option>dark</option><option>preset</option><option>custom</option></select><input type="color" value={theme.custom.accent} onChange={(e) => { const next = { ...theme, mode: 'custom' as const, custom: { ...theme.custom, accent: e.target.value } }; setTheme(next); saveTheme(next); }}/></> : area.endsWith('homepage-builder') ? <><h2>Homepage builder</h2><p>Drag-and-drop page builder shell with add/remove/reorder, templates, mobile preview, draft/save/publish, and database-ready persistence.</p>{sections.map((section, i) => <div className="builder-row" draggable key={section.id}><input value={section.title} onChange={(e) => setSections(sections.map((s) => s.id === section.id ? { ...s, title: e.target.value } : s))}/><button onClick={() => i > 0 && setSections(sections.map((s, idx, arr) => idx === i - 1 ? arr[i] : idx === i ? arr[i - 1] : s))}>↑</button><button onClick={() => setSections(sections.filter((s) => s.id !== section.id))}>Remove</button></div>)}<button className="button secondary" onClick={() => setSections([...sections, { id: crypto.randomUUID(), type: 'cta', title: 'New section', body: 'Section body' }])}>Add section</button><button className="button" onClick={publish}>Publish</button><div className="mobile-preview">Mobile preview</div></> : area.endsWith('roles') ? <><h2>Roles</h2>{defaultRoles.map((r) => <details key={r.name}><summary>{r.name}</summary><p>{r.permissions.length} permissions</p></details>)}</> : area.endsWith('permissions') ? <><h2>Permissions</h2><div className="permission-list">{permissions.map((p) => <code key={p.key}>{p.key}</code>)}</div></> : area.endsWith('foundation') ? <><h2>Foundation package</h2>{foundationComponents.map((c) => <p key={c}>✓ {c}</p>)}</> : area.endsWith('payment') ? <><h2>Payment providers</h2><p>Square default with Stripe, PayPal, Authorize.net, manual payment, and configure-later adapter slots.</p></> : area.endsWith('media') ? <><h2>Media storage</h2><p>Business logic uses a storage service abstraction for Netlify Blobs, Supabase Storage, local development, or future S3-compatible providers.</p></> : <><h2>{area}</h2><p>Company settings, users, email, license, expansion packs, and provider configuration live here.</p><p>Default service categories: {serviceCategories.join(', ')}</p></>}</section></div></AppLayout></Protected>;
}
