import { useState } from 'react';
import { AppLayout, Protected } from '../components/Layout';
import { Link } from '../components/Router';
import { defaultRoles, defaultSections, defaultWidgets, foundationComponents, permissions, sampleInvoices, sampleJobs, sampleQuotes, sampleRequests, sampleThreads } from '../data/foundation';
import { getTheme, saveTheme } from '../lib/theme';
import { loadJson, saveJson } from '../lib/storage';
import { ActionCard, Badge, Button, EmptyState, MetricCard, PageHeader, StatusBadge } from '../components/ui';
import type { DashboardWidget, PageSection } from '../types/domain';

export function DashboardPage() {
  const [widgets, setWidgets] = useState(loadJson<DashboardWidget[]>('contractoros.dashboard.widgets', defaultWidgets));
  const save = (next: DashboardWidget[]) => { setWidgets(next); saveJson('contractoros.dashboard.widgets', next); };
  return <Protected permission="settings.view"><AppLayout title="Dashboard"><PageHeader eyebrow="Live command center" title="Today at a glance" description="A polished operations cockpit for revenue, scheduling, requests, and field health." action={<Button onClick={() => save([...widgets, { id: crypto.randomUUID(), title: 'New widget', type: 'metric', x: 0, y: widgets.length, w: 1, h: 1 }])}>Add widget</Button>}/><div className="metric-grid"><MetricCard label="Open requests" value={sampleRequests.length} detail="2 require follow-up"/><MetricCard label="Active jobs" value={sampleJobs.length} detail="Dispatch balanced"/><MetricCard label="Quote pipeline" value={`$${sampleQuotes.reduce((sum, q) => sum + q.total, 0)}`} detail="Awaiting approvals"/><MetricCard label="Invoice balance" value={`$${sampleInvoices.reduce((sum, i) => sum + i.balance, 0)}`} detail="Payment-ready"/></div><div className="dashboard-grid">{widgets.map((w, i) => <article className="card widget" key={w.id} style={{ gridColumn: `span ${w.w}` }}><input value={w.title} onChange={(e) => save(widgets.map((x) => x.id === w.id ? { ...x, title: e.target.value } : x))}/><strong>{w.type === 'metric' ? i + 1 : '•'}</strong><p className="muted">Saved user layout widget</p><div className="widget-actions"><button onClick={() => save(widgets.map((x) => x.id === w.id ? { ...x, w: x.w === 1 ? 2 : 1 } : x))}>Resize</button><button onClick={() => i > 0 && save(widgets.map((x, idx, arr) => idx === i - 1 ? arr[i] : idx === i ? arr[i - 1] : x))}>Move up</button><button onClick={() => save(widgets.filter((x) => x.id !== w.id))}>Remove</button></div></article>)}</div></AppLayout></Protected>;
}

export function PortalPage() { return <AppLayout title="Client portal"><PageHeader eyebrow="Customer experience" title="A branded client portal" description="Properties, requests, quotes, invoices, and conversations share the same premium design system."/><div className="grid cards"><WorkflowCard title="My properties" items={['Primary property']}/><WorkflowCard title="My requests" items={sampleRequests.map((r) => `${r.id} · ${r.status}`)}/><WorkflowCard title="My quotes" items={sampleQuotes.map((q) => `${q.id} · ${q.status}`)}/><WorkflowCard title="My invoices" items={sampleInvoices.map((i) => `${i.id} · $${i.balance}`)}/><WorkflowCard title="My messages" items={sampleThreads.map((t) => t.subject)}/></div></AppLayout>; }
function WorkflowCard({ title, items }: { title: string; items: string[] }) { return <ActionCard title={title} description={`${items.length} item${items.length === 1 ? '' : 's'}`}>{items.map((item) => <p key={item}>{item}</p>)}</ActionCard>; }

export function RequestsPage() { return <Protected permission="requests.view"><AppLayout title="Work requests"><PageHeader eyebrow="CRM intake" title="Work requests" description="Triage customer needs with status-aware cards and table rows." action={<Link href="/requests/new" className="button">New request</Link>}/><DataTable rows={sampleRequests.map((r) => [r.id,r.client,r.service,r.status,r.priority])}/></AppLayout></Protected>; }
export function QuotesPage() { return <Protected permission="quotes.view"><AppLayout title="Quotes"><PageHeader eyebrow="Estimating" title="Quotes" description="Track approvals, totals, and conversion to scheduled jobs."/><DataTable rows={sampleQuotes.map((q) => [q.id,q.client,q.status,`$${q.total}`])}/><ActionCard title="Approval workflow" description="Client approval converts approved quotes to jobs and saves communication history."/></AppLayout></Protected>; }
export function JobsPage() { return <Protected permission="jobs.view"><AppLayout title="Jobs and dispatch"><PageHeader eyebrow="Operations" title="Jobs and dispatch" description="Technician assignments, work orders, and job status in one polished surface."/><DataTable rows={sampleJobs.map((j) => [j.id,j.client,j.status,j.technician])}/></AppLayout></Protected>; }
export function InvoicesPage() { return <Protected permission="invoices.view"><AppLayout title="Invoices and payments"><PageHeader eyebrow="Financial" title="Invoices and payments" description="Balances and payment providers are styled consistently across desktop and mobile."/><DataTable rows={sampleInvoices.map((i) => [i.id,i.client,i.status,`$${i.balance}`])}/><ActionCard title="Payment framework" description="Square is default; Stripe, PayPal, Authorize.net, manual cash/check, and configure-later are structured as provider adapters."/></AppLayout></Protected>; }
export function MessagesPage() { return <Protected permission="messages.view"><AppLayout title="Advanced messaging"><PageHeader eyebrow="Communications" title="Advanced messaging" description="Customer-visible replies and internal notes live together without visual clutter."/><div className="grid cards">{sampleThreads.map((t) => <article className="card" key={t.id}><h3>{t.subject}</h3><p>{t.participants.join(' ↔ ')}</p><Badge tone="accent">{t.visibility}</Badge><textarea placeholder="Customer-visible reply or internal note"/></article>)}</div></AppLayout></Protected>; }
export function AssetsPage() { return <Protected permission="cmms.view"><AppLayout title="CMMS assets"><PageHeader eyebrow="Maintenance" title="CMMS assets" description="Asset history, PM shell, notes, documents, and property relationships are ready."/><EmptyState title="Asset foundation" description="Add equipment, service history, recurring maintenance, and property context when CMMS is enabled."/></AppLayout></Protected>; }

function DataTable({ rows }: { rows: string[][] }) { return <div className="table">{rows.map((row) => <div className="tr" key={row.join('-')}>{row.map((cell, index) => <span key={`${cell}-${index}`}>{index === 2 ? <StatusBadge status={cell}/> : cell}</span>)}</div>)}</div>; }

export function SettingsPage({ area = 'settings' }: { area?: string }) {
  const [theme, setTheme] = useState(getTheme());
  const [sections, setSections] = useState(loadJson<PageSection[]>('contractoros.homepage.sections.draft', defaultSections));
  const publish = () => { saveJson('contractoros.homepage.sections.draft', sections); saveJson('contractoros.homepage.sections.published', sections); };
  return <Protected permission="settings.view"><AppLayout title={`Settings / ${area.replace('settings/','')}`}><div className="settings-grid"><nav className="card settings-nav">{['company','theme','users','roles','permissions','foundation','expansion-packs','payment','email','license','media','homepage-builder'].map((s) => <Link href={`/settings/${s}`} key={s}>{s}</Link>)}</nav><section className="card settings-panel">{area.endsWith('theme') ? <><h2>Theme</h2><select value={theme.mode} onChange={(e) => { const next = { ...theme, mode: e.target.value as typeof theme.mode }; setTheme(next); saveTheme(next); }}><option>system</option><option>light</option><option>dark</option><option>preset</option><option>custom</option></select></> : area.endsWith('roles') ? <><h2>Roles</h2>{defaultRoles.map((r) => <p key={r.name}><strong>{r.name}</strong> — {r.permissions.length} permissions</p>)}</> : area.endsWith('permissions') ? <><h2>Permissions</h2><div className="permission-list">{permissions.map((p) => <Badge key={p.key}>{p.key}</Badge>)}</div></> : area.endsWith('foundation') ? <><h2>Foundation components</h2>{foundationComponents.map((c) => <p key={c}>{c}</p>)}</> : area.endsWith('homepage-builder') ? <><h2>Homepage builder</h2>{sections.map((section) => <div className="builder-row" key={section.id}><input value={section.title} onChange={(e) => setSections(sections.map((s) => s.id === section.id ? { ...s, title: e.target.value } : s))}/><button onClick={() => setSections(sections.filter((s) => s.id !== section.id))}>Remove</button></div>)}<Button onClick={publish}>Publish</Button></> : <><PageHeader eyebrow="Settings" title="Configuration center" description="Company, users, roles, foundation modules, payments, email, media, and homepage settings inherit the same premium UI."/><div className="mobile-preview"><h3>Mobile preview</h3><p>Bottom navigation, cards, forms, badges, and tables are responsive by default.</p></div></>}</section></div></AppLayout></Protected>;
}
