import { Link } from './Router';
import type { HomepageButton, HomepageDraft, HomepageItem, HomepageMedia, HomepageSection } from '../lib/homepage-builder';
import { normalizeGlobalStyles, normalizeSections } from '../lib/homepage-builder';

const deviceClass = (section: HomepageSection) => [section.visibility.desktop ? '' : 'hide-desktop', section.visibility.tablet ? '' : 'hide-tablet', section.visibility.mobile ? '' : 'hide-mobile'].filter(Boolean).join(' ');

export function HomepageRenderer({ draft, editable = false, selectedId = '', onSelect, onTextChange, device = 'desktop' }: { draft: HomepageDraft; editable?: boolean; selectedId?: string; onSelect?: (id: string) => void; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void; device?: 'desktop' | 'tablet' | 'mobile' }) {
  const globalStyles = normalizeGlobalStyles(draft.globalStyles);
  const design = globalStyles.design;
  const sections = normalizeSections(draft.sections).filter((section) => section.enabled && section.visibility.public);
  const background = 'var(--site-background)';
  return <div className={`homepage-renderer homepage-device-${device} design-${design.themePreset} cards-${design.cards.style} buttons-${design.buttons.style}`} style={{ background, ['--homepage-max' as string]: `${globalStyles.maxPageWidth}px`, ['--homepage-radius' as string]: `${globalStyles.cardRadius}px` }}>
    {sections.length ? sections.map((section) => <RenderedSection key={section.id} section={section} editable={editable} selected={selectedId === section.id} onSelect={onSelect} onTextChange={onTextChange}/>) : <section className="public-home-section"><div className="public-home-inner empty-render">No published homepage sections yet.</div></section>}
  </div>;
}

function RenderedSection({ section, editable, selected, onSelect, onTextChange }: { section: HomepageSection; editable: boolean; selected: boolean; onSelect?: (id: string) => void; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) {
  const s = section.styles || {};
  const mode = s.styleMode || 'inherit';
  const tokenBackground = mode === 'custom' ? (s.backgroundColor || s.background || 'var(--surface-section)') : mode === 'alternate' ? 'var(--surface-section-alt)' : mode === 'primary-accent' ? 'var(--site-primary)' : mode === 'accent-feature' ? 'var(--site-accent)' : mode === 'dark-contrast' ? 'var(--surface-dark)' : mode === 'light-contrast' ? 'var(--surface-light)' : 'var(--surface-section)';
  const tokenText = mode === 'custom' ? (s.textColor || 'var(--site-text)') : mode === 'primary-accent' ? 'var(--site-primary-contrast)' : mode === 'accent-feature' ? 'var(--site-accent-contrast)' : mode === 'dark-contrast' ? 'var(--surface-dark-text)' : mode === 'light-contrast' ? 'var(--surface-light-text)' : 'var(--site-text)';
  const style = { backgroundColor: tokenBackground, color: tokenText, paddingTop: `${s.spacingTop ?? 82}px`, paddingBottom: `${s.spacingBottom ?? 82}px`, ['--section-accent' as string]: mode === 'custom' ? (s.accentColor || 'var(--site-primary)') : mode === 'dark-contrast' || mode === 'primary-accent' ? 'var(--site-accent)' : 'var(--site-primary)', ['--section-card' as string]: mode === 'custom' ? (s.cardBackground || 'var(--surface-card)') : mode === 'primary-accent' || mode === 'accent-feature' || mode === 'dark-contrast' ? 'var(--surface-glass)' : 'var(--surface-card)', ['--section-card-hover' as string]: 'var(--surface-card-hover)', ['--section-border' as string]: mode === 'custom' ? (s.borderColor || 'var(--site-border)') : 'var(--site-border)', ['--section-radius' as string]: `${s.borderRadius || 24}px`, backgroundImage: s.backgroundImage?.url ? `linear-gradient(var(--site-overlay), var(--site-overlay)), url(${s.backgroundImage.url})` : section.type === 'hero' ? 'var(--surface-hero)' : undefined };
  const className = `public-home-section type-${section.type} section-mode-${mode} ${deviceClass(section)} ${selected ? 'builder-selected-section' : ''} ${section.advanced.cssClass || ''}`;
  return <section id={section.advanced.anchorId || undefined} className={className} style={style} onClick={(event) => { if (editable) { event.stopPropagation(); onSelect?.(section.id); } }}>
    <div className={`public-home-inner align-${s.alignment || 'left'} variant-${s.layoutVariant || 'standard'}`} style={{ maxWidth: s.maxWidth || 'var(--homepage-max)' }}><SectionBody section={section} editable={editable} onTextChange={onTextChange}/></div>
  </section>;
}

function EditableText({ section, field, as = 'p', children, editable, onTextChange }: { section: HomepageSection; field: 'heading' | 'subheading' | 'body'; as?: 'h1' | 'h2' | 'p' | 'div'; children?: string; editable: boolean; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) {
  const Tag = as;
  return <Tag contentEditable={editable} suppressContentEditableWarning className={editable ? 'inline-editable' : undefined} onBlur={(event) => editable && onTextChange?.(section.id, field, event.currentTarget.textContent || '')}>{children}</Tag>;
}

function SectionBody({ section, editable, onTextChange }: { section: HomepageSection; editable: boolean; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) {
  const c = section.content;
  const s = section.styles || {};
  const items = c.items || [];
  if (section.type === 'hero') return <div className="home-hero-layout"><div className="home-copy"><Header section={section} editable={editable} onTextChange={onTextChange} hero/><TrustBadges badges={c.trustBadges}/><ButtonRow buttons={c.buttons}/>{c.phone && <p className="service-line">Serving local homes and businesses · {c.phone}</p>}</div><HeroMedia section={section}/></div>;
  if (section.type === 'request-estimate-form') return <div className="estimate-embed"><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="mini-form"><input placeholder="Name" aria-label="Name"/><input placeholder="Phone" aria-label="Phone"/><input placeholder="Service needed" aria-label="Service needed"/><button className="button">Request Estimate</button></div></div>;
  if (section.type === 'contact-block') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="home-card-grid cols-3"><InfoCard title="Call" text={c.phone || 'Fast phone support for estimates and scheduling.'}/><InfoCard title="Email" text={c.email || 'Send project details and photos for a clear next step.'}/><InfoCard title="Visit" text={c.address || 'Local crews serving nearby homes and commercial properties.'}/></div><ButtonRow buttons={c.buttons}/></div>;
  if (section.type === 'custom-image-text' || section.type === 'about' || section.type === 'team-owner-intro') return <div className="home-split"><MediaFrame image={c.image} fallback="Local contractor team"/><div><Header section={section} editable={editable} onTextChange={onTextChange}/><CardGrid items={items} columns={1}/><ButtonRow buttons={c.buttons}/></div></div>;
  if (section.type === 'custom-rich-text') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="rich-content" dangerouslySetInnerHTML={{ __html: c.richText || c.body || '' }}/></div>;
  if (section.type === 'call-to-action' || section.type === 'emergency-banner' || section.type === 'financing-banner') return <div className="home-cta"><Header section={section} editable={editable} onTextChange={onTextChange}/><TrustBadges badges={c.trustBadges || ['Licensed team','Clear estimates','Warranty-backed work']}/><ButtonRow buttons={c.buttons}/></div>;
  if (section.type === 'before-after-gallery') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className={`before-after-grid cols-${s.columns || 2}`}>{makeBeforeAfterItems(c.images, items).map((pair, index) => <BeforeAfter key={index} before={pair.before} after={pair.after}/>)}</div></div>;
  if (section.type === 'featured-projects' || section.type === 'project-showcase') { const projectItems = items.length ? items : [{ id: 'p1', title: 'Kitchen-to-finish transformation', text: 'Use project cards to show location, category, before/after proof, and scope.', icon: 'Featured' }, { id: 'p2', title: 'Emergency repair completed fast', text: 'Show response time, finished result, and customer impact.', icon: 'Before/After' }, { id: 'p3', title: 'Commercial maintenance upgrade', text: 'Promote contract work and reliability for property managers.', icon: 'Commercial' }]; return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className={`project-showcase mode-${c.displayMode || 'slider'} cols-${s.columns || 3}`}>{projectItems.slice(0, c.projectLimit || 6).map((item) => <ProjectCard key={item.id} item={item}/>)}</div></div>; }
  if (section.type === 'testimonials' || section.type === 'google-reviews') { const reviewItems = items.length ? items : [{ id: 'r1', title: 'Sarah M.', text: 'Fast response, clean work, and clear options before anything started.', rating: 5 }, { id: 'r2', title: 'David R.', text: 'Professional from estimate through cleanup. The crew treated our property with respect.', rating: 5 }, { id: 'r3', title: 'Monica T.', text: 'Easy scheduling, great communication, and premium results.', rating: 5 }]; return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="review-summary"><strong>4.9</strong><span>Google-ready proof · cached reviews supported</span></div><div className={`review-grid mode-${c.displayMode || 'carousel'}`}>{reviewItems.map((item) => <ReviewCard key={item.id} item={item}/>)}</div></div>; }
  if (section.type === 'faq') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="faq-list">{items.map((item) => <details key={item.id}><summary>{item.title}</summary><p>{item.text}</p></details>)}</div></div>;
  if (section.type === 'logo-brand-strip' || section.type === 'brands-we-service') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="logo-strip">{(items.length ? items : [{ id: '1', title: 'Licensed' }, { id: '2', title: 'Insured' }, { id: '3', title: 'Warranty' }]).map((item) => <span key={item.id}>{item.title}</span>)}</div></div>;
  return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><CardGrid items={items} columns={s.columns || 3}/><ButtonRow buttons={c.buttons}/></div>;
}
function Header({ section, editable, onTextChange, hero = false }: { section: HomepageSection; editable: boolean; hero?: boolean; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) { const c = section.content; return <div className="home-section-head">{c.eyebrow && <p className="home-eyebrow">{c.eyebrow}</p>}{c.heading && <EditableText section={section} field="heading" as={hero ? 'h1' : 'h2'} editable={editable} onTextChange={onTextChange}>{c.heading}</EditableText>}{c.subheading && <EditableText section={section} field="subheading" editable={editable} onTextChange={onTextChange}>{c.subheading}</EditableText>}{c.body && <EditableText section={section} field="body" editable={editable} onTextChange={onTextChange}>{c.body}</EditableText>}</div>; }
function ButtonRow({ buttons = [] }: { buttons?: HomepageButton[] }) { if (!buttons.length) return null; return <div className="home-buttons">{buttons.map((button) => <Link key={button.id} href={button.href || '#'} className={`button ${button.style === 'secondary' ? 'secondary' : button.style === 'ghost' ? 'ghost' : ''}`}>{button.label || 'Button'}</Link>)}</div>; }
function TrustBadges({ badges = [] }: { badges?: string[] }) { if (!badges.length) return null; return <div className="trust-pill-row">{badges.map((badge) => <span key={badge}>{badge}</span>)}</div>; }
function CardGrid({ items, columns }: { items: HomepageItem[]; columns: number }) { const safe = items.length ? items : [{ id: 'empty', title: 'Warranty-backed work', text: 'Add service proof, guarantees, team standards, or next steps from section settings.' }]; return <div className={`home-card-grid cols-${columns}`}>{safe.map((item) => <InfoCard key={item.id} title={item.value ? `${item.value} ${item.title}` : item.title} text={item.text || item.label || ''} icon={item.icon}/>)}</div>; }
function InfoCard({ title, text, icon }: { title: string; text?: string; icon?: string }) { return <article className="home-card"><span className="home-card-icon">{icon || '✦'}</span><h3>{title}</h3>{text && <p>{text}</p>}</article>; }
function MediaFrame({ image, fallback = 'Project image' }: { image?: HomepageMedia; fallback?: string }) { return <div className="home-media-frame">{image?.url ? <img loading="lazy" src={image.url} alt={image.alt || fallback}/> : <div className="media-placeholder"><span>{fallback}</span></div>}</div>; }
function HeroMedia({ section }: { section: HomepageSection }) { const c = section.content; if (c.videoUrl) return <div className="home-media-frame hero-video"><video src={c.videoUrl} controls={false} autoPlay muted loop playsInline preload="none"/></div>; return <div className="hero-proof-stack"><MediaFrame image={c.image || section.styles.backgroundImage} fallback="Premium project proof"/><div className="floating-proof"><strong>4.9★</strong><span>Trusted local service</span></div></div>; }
function makeBeforeAfterItems(images: HomepageMedia[] = [], items: HomepageItem[]) { if (items.some((item) => item.beforeImage || item.afterImage)) return items.map((item) => ({ before: item.beforeImage, after: item.afterImage })); const pairs = []; for (let index = 0; index < Math.max(images.length, 2); index += 2) pairs.push({ before: images[index], after: images[index + 1] }); return pairs.length ? pairs : [{ before: undefined, after: undefined }]; }
function BeforeAfter({ before, after }: { before?: HomepageMedia; after?: HomepageMedia }) { return <div className="before-after"><MediaFrame image={before} fallback="Before"/><div className="after-layer"><MediaFrame image={after} fallback="After"/></div><input aria-label="Before and after comparison" type="range" min="0" max="100" defaultValue="52"/></div>; }
function ProjectCard({ item }: { item: HomepageItem }) { return <article className="project-card"><MediaFrame image={item.image} fallback={item.icon || 'Project'}/><div><span>{item.label || item.icon || 'Featured project'}</span><h3>{item.title}</h3>{item.text && <p>{item.text}</p>}</div></article>; }
function ReviewCard({ item }: { item: HomepageItem }) { return <article className="review-card"><div className="stars">{'★'.repeat(Math.max(1, Math.min(5, item.rating || 5)))}</div><p>“{item.text || 'Outstanding service from start to finish.'}”</p><strong>{item.title}</strong></article>; }
