import { Link } from './Router';
import type { HomepageButton, HomepageDraft, HomepageItem, HomepageMedia, HomepageSection } from '../lib/homepage-builder';
import { normalizeGlobalStyles, normalizeSections } from '../lib/homepage-builder';

const deviceClass = (section: HomepageSection) => [section.visibility.desktop ? '' : 'hide-desktop', section.visibility.tablet ? '' : 'hide-tablet', section.visibility.mobile ? '' : 'hide-mobile'].filter(Boolean).join(' ');

export function HomepageRenderer({ draft, editable = false, selectedId = '', onSelect, onTextChange, device = 'desktop' }: { draft: HomepageDraft; editable?: boolean; selectedId?: string; onSelect?: (id: string) => void; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void; device?: 'desktop' | 'tablet' | 'mobile' }) {
  const globalStyles = normalizeGlobalStyles(draft.globalStyles);
  const design = globalStyles.design;
  const sections = normalizeSections(draft.sections).filter((section) => section.enabled && section.visibility.public);
  const background = design.background.type === 'gradient' ? design.background.gradient : design.background.type === 'image' && design.background.imageUrl ? `linear-gradient(rgba(0,0,0,.42), rgba(0,0,0,.42)), url(${design.background.imageUrl})` : design.background.color || globalStyles.background;
  return <div className={`homepage-renderer homepage-device-${device} design-${design.themePreset} cards-${design.cards.style} buttons-${design.buttons.style}`} style={{ background, ['--homepage-max' as string]: `${globalStyles.maxPageWidth}px`, ['--homepage-radius' as string]: `${globalStyles.cardRadius}px`, ['--site-primary' as string]: design.colors.primary, ['--site-secondary' as string]: design.colors.secondary, ['--site-accent' as string]: design.colors.accent, ['--site-background' as string]: design.colors.background, ['--site-card' as string]: design.colors.card, ['--site-text' as string]: design.colors.text, ['--site-muted' as string]: design.colors.muted, ['--site-radius' as string]: design.radius, ['--site-shadow' as string]: design.shadow }}>
    {sections.length ? sections.map((section) => <RenderedSection key={section.id} section={section} editable={editable} selected={selectedId === section.id} onSelect={onSelect} onTextChange={onTextChange}/>) : <section className="public-home-section"><div className="public-home-inner empty-render">No published homepage sections yet.</div></section>}
  </div>;
}

function RenderedSection({ section, editable, selected, onSelect, onTextChange }: { section: HomepageSection; editable: boolean; selected: boolean; onSelect?: (id: string) => void; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) {
  const s = section.styles || {};
  const style = { backgroundColor: s.backgroundColor || 'transparent', color: s.textColor || 'var(--site-text)', paddingTop: `${s.spacingTop ?? 72}px`, paddingBottom: `${s.spacingBottom ?? 72}px`, backgroundImage: s.backgroundImage?.url ? `linear-gradient(rgba(0,0,0,${(s.overlayOpacity || 0) / 100}), rgba(0,0,0,${(s.overlayOpacity || 0) / 100})), url(${s.backgroundImage.url})` : undefined };
  const className = `public-home-section type-${section.type} ${deviceClass(section)} ${selected ? 'builder-selected-section' : ''} ${section.advanced.cssClass || ''}`;
  return <section id={section.advanced.anchorId || undefined} className={className} style={style} onClick={(event) => { if (editable) { event.stopPropagation(); onSelect?.(section.id); } }}>
    <div className={`public-home-inner align-${s.alignment || 'left'} variant-${s.layoutVariant || 'standard'}`} style={{ maxWidth: s.maxWidth || 'var(--homepage-max)' }}><SectionBody section={section} editable={editable} onTextChange={onTextChange}/></div>
  </section>;
}

function EditableText({ section, field, as = 'p', children, editable, onTextChange }: { section: HomepageSection; field: 'heading' | 'subheading' | 'body'; as?: 'h1' | 'h2' | 'p' | 'div'; children?: string; editable: boolean; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) { const Tag = as; return <Tag contentEditable={editable} suppressContentEditableWarning className={editable ? 'inline-editable' : undefined} onBlur={(event) => editable && onTextChange?.(section.id, field, event.currentTarget.textContent || '')}>{children}</Tag>; }

function SectionBody({ section, editable, onTextChange }: { section: HomepageSection; editable: boolean; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) {
  const c = section.content || {}; const s = section.styles || {}; const items = Array.isArray(c.items) ? c.items : [];
  if (section.type === 'hero') return <div className="home-hero-layout"><div className="home-copy">{c.emergencyEnabled && <span className="emergency-pill">24/7 Emergency Available</span>}{c.eyebrow && <p className="home-eyebrow">{c.eyebrow}</p>}{c.heading && <EditableText section={section} field="heading" as="h1" editable={editable} onTextChange={onTextChange}>{c.heading}</EditableText>}{c.subheading && <EditableText section={section} field="subheading" editable={editable} onTextChange={onTextChange}>{c.subheading}</EditableText>}<ButtonRow buttons={c.buttons}/>{c.trustBadges?.length ? <div className="trust-row">{c.trustBadges.map((badge) => <span key={badge}>✓ {badge}</span>)}</div> : null}</div><HeroMedia section={section}/></div>;
  if (section.type === 'request-estimate-form') return <div className="estimate-embed premium-wizard"><Header section={section} editable={editable} onTextChange={onTextChange}/><ol className="estimate-steps">{['Contact Information','Property Information','Service Needed','Photo Uploads','Review','Submit'].map((step, index) => <li key={step}><span>{index + 1}</span>{step}</li>)}</ol><div className="mini-form"><input placeholder="Name"/><input placeholder="Phone"/><input placeholder="Service needed"/><label className="upload-drop">Drag & drop photos or tap to upload<input type="file" multiple accept="image/*"/></label><Link href="/request-estimate" className="button">Open full estimate wizard</Link></div></div>;
  if (section.type === 'contact-block') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="home-card-grid cols-3"><InfoCard title="Call" text={c.phone || 'Phone coming soon'}/><InfoCard title="Email" text={c.email || 'Email coming soon'}/><InfoCard title="Visit" text={c.address || 'Service address coming soon'}/></div><ButtonRow buttons={c.buttons}/></div>;
  if (section.type === 'custom-image-text') return <div className="home-split"><MediaFrame image={c.image}/><div><Header section={section} editable={editable} onTextChange={onTextChange}/><ButtonRow buttons={c.buttons}/></div></div>;
  if (section.type === 'custom-rich-text') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="rich-content" dangerouslySetInnerHTML={{ __html: c.richText || c.body || '' }}/></div>;
  if (section.type === 'call-to-action' || section.type === 'emergency-banner' || section.type === 'financing-banner') return <div className="home-cta"><Header section={section} editable={editable} onTextChange={onTextChange}/><ButtonRow buttons={c.buttons}/></div>;
  if (section.type === 'before-after-gallery') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className={`before-after-grid cols-${s.columns || 2}`}>{makeBeforeAfterItems(c.images, items).map((pair, index) => <BeforeAfter key={index} before={pair.before} after={pair.after}/>)}</div></div>;
  if (section.type === 'featured-projects' || section.type === 'project-showcase') { const projectItems = items.length ? items : [{ id: 'p1', title: 'Your completed projects will appear here.', text: 'Feature finished jobs from Marketing → Project Showcase.', icon: 'Before' }, { id: 'p2', title: 'Professional project gallery', text: 'Add categories, locations, before images, after images, and photo galleries.', icon: 'After' }, { id: 'p3', title: 'Featured homepage slider', text: 'Mark projects as featured to promote your best work automatically.', icon: 'Featured' }]; return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className={`project-showcase mode-${c.displayMode || 'slider'} cols-${s.columns || 3}`}>{projectItems.slice(0, c.projectLimit || 6).map((item) => <ProjectCard key={item.id} item={item}/>)}</div></div>; }
  if (section.type === 'testimonials' || section.type === 'google-reviews') { const reviewItems = items.length ? items : [{ id: 'r1', title: 'Google Business preview', text: 'Connect your Google API Key and Place ID in Settings → Integrations → Google Business.', rating: 5 }, { id: 'r2', title: 'Manual testimonial fallback', text: 'If Google is unavailable, curated testimonials keep this section live.', rating: 5 }, { id: 'r3', title: 'Average rating ready', text: 'Cached reviews, refresh status, average rating, and review count appear here.', rating: 5 }]; return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="review-summary"><strong>4.9</strong><span>Preview average rating · Google setup ready</span></div><div className={`review-grid mode-${c.displayMode || 'carousel'}`}>{reviewItems.map((item) => <ReviewCard key={item.id} item={item}/>)}</div></div>; }
  if (section.type === 'faq') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="faq-list">{items.map((item) => <details key={item.id}><summary>{item.title}</summary><p>{item.text}</p></details>)}</div></div>;
  if (section.type === 'logo-brand-strip' || section.type === 'brands-we-service') return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><div className="logo-strip">{(items.length ? items : [{ id: '1', title: 'Licensed' }, { id: '2', title: 'Insured' }, { id: '3', title: 'Warranty' }]).map((item) => <span key={item.id}>{item.title}</span>)}</div></div>;
  return <div><Header section={section} editable={editable} onTextChange={onTextChange}/><CardGrid items={items} columns={s.columns || 3}/><ButtonRow buttons={c.buttons}/></div>;
}
function Header({ section, editable, onTextChange }: { section: HomepageSection; editable: boolean; onTextChange?: (id: string, key: 'heading' | 'subheading' | 'body', value: string) => void }) { const c = section.content; return <div className="home-section-head">{c.eyebrow && <p className="home-eyebrow">{c.eyebrow}</p>}{c.heading && <EditableText section={section} field="heading" as="h2" editable={editable} onTextChange={onTextChange}>{c.heading}</EditableText>}{c.subheading && <EditableText section={section} field="subheading" editable={editable} onTextChange={onTextChange}>{c.subheading}</EditableText>}{c.body && <EditableText section={section} field="body" editable={editable} onTextChange={onTextChange}>{c.body}</EditableText>}</div>; }
function ButtonRow({ buttons = [] }: { buttons?: HomepageButton[] }) { if (!buttons.length) return null; return <div className="home-buttons">{buttons.map((button) => <Link key={button.id} href={button.href || '#'} className={`button ${button.style === 'secondary' ? 'secondary' : button.style === 'ghost' ? 'ghost' : ''}`}>{button.label || 'Button'}</Link>)}</div>; }
function CardGrid({ items, columns }: { items: HomepageItem[]; columns: number }) { const safe = items.length ? items : [{ id: 'empty', title: 'Editable card', text: 'Add list items/cards from the selected section settings.' }]; return <div className={`home-card-grid cols-${columns}`}>{safe.map((item) => <InfoCard key={item.id} title={item.value ? `${item.value} ${item.title}` : item.title} text={item.text || item.label || ''} icon={item.icon}/>)}</div>; }
function InfoCard({ title, text, icon }: { title: string; text?: string; icon?: string }) { return <article className="home-card"><span className="home-card-icon">{icon || '✦'}</span><h3>{title}</h3>{text && <p>{text}</p>}</article>; }
function MediaFrame({ image, fallback = 'Project image' }: { image?: HomepageMedia; fallback?: string }) { return <div className="home-media-frame">{image?.url ? <img loading="lazy" src={image.url} alt={image.alt || fallback}/> : <div className="media-placeholder">{fallback}</div>}</div>; }
function HeroMedia({ section }: { section: HomepageSection }) { const c = section.content; if (c.videoUrl) return <div className="home-media-frame hero-video"><video src={c.videoUrl} controls={false} autoPlay muted loop playsInline preload="none"/></div>; return <MediaFrame image={c.image || section.styles.backgroundImage} fallback="Fast local service"/>; }
function makeBeforeAfterItems(images: HomepageMedia[] = [], items: HomepageItem[]) { if (items.some((item) => item.beforeImage || item.afterImage)) return items.map((item) => ({ before: item.beforeImage, after: item.afterImage })); const pairs = []; for (let index = 0; index < Math.max(images.length, 2); index += 2) pairs.push({ before: images[index], after: images[index + 1] }); return pairs.length ? pairs : [{ before: undefined, after: undefined }]; }
function BeforeAfter({ before, after }: { before?: HomepageMedia; after?: HomepageMedia }) { return <div className="before-after"><MediaFrame image={before} fallback="Before"/><div className="after-layer"><MediaFrame image={after} fallback="After"/></div><input aria-label="Before and after comparison" type="range" min="0" max="100" defaultValue="52"/></div>; }
function ProjectCard({ item }: { item: HomepageItem }) { return <article className="project-card"><MediaFrame image={item.image} fallback={item.icon || 'Project'}/><div><span>{item.label || item.icon || 'Featured project'}</span><h3>{item.title}</h3>{item.text && <p>{item.text}</p>}</div></article>; }
function ReviewCard({ item }: { item: HomepageItem }) { return <article className="review-card"><div className="stars">{'★'.repeat(Math.max(1, Math.min(5, item.rating || 5)))}</div><p>“{item.text || 'Outstanding service from start to finish.'}”</p><strong>{item.title}</strong></article>; }
