export const defaultRoles = ['owner','admin','manager','worker','client'];
export const permissions = ['dashboard.view','customers.view','customers.manage','requests.view','requests.manage','quotes.view','quotes.manage','workorders.view','workorders.manage','workorders.assign','schedule.view','schedule.manage','inventory.view','inventory.manage','invoices.view','invoices.manage','finance.view','finance.manage','users.view','users.manage','roles.manage','modules.view','modules.manage','theme.manage','homepage.manage','system.view','system.manage','audit.view','impersonation.use'];
export const rolePermissions = {
  owner: permissions,
  admin: ['dashboard.view','customers.view','customers.manage','requests.view','requests.manage','quotes.view','quotes.manage','workorders.view','workorders.manage','schedule.view','schedule.manage','inventory.view','inventory.manage','invoices.view','invoices.manage','finance.view','users.view','modules.view','system.view'],
  manager: ['dashboard.view','customers.view','customers.manage','requests.view','requests.manage','quotes.view','quotes.manage','workorders.view','workorders.manage','workorders.assign','schedule.view','schedule.manage','inventory.view'],
  worker: ['dashboard.view','workorders.view','schedule.view','inventory.view'],
  client: ['dashboard.view','requests.view','requests.manage','quotes.view','invoices.view','finance.view']
};
export const coreModules = [
  ['dashboard-overview','Dashboard / Overview','Main'],['customers','Customers / Clients','Operations'],['request-estimate','Request Estimate','Operations'],['estimate-quote-center','Estimate & Quote Center','Operations'],['work-orders','Work Orders','Operations'],['schedule-calendar','Schedule / Calendar','Operations'],['inventory','Inventory','Operations'],['invoices','Invoices','Financial'],['finance','Finance','Financial'],['payments','Payments','Financial'],['worker-jobs','Worker Jobs','People'],['users-roles','Users & Roles','People'],['ai-photo-estimate','AI Photo Estimate','AI Tools'],['ai-quote-builder','AI Quote Builder','AI Tools'],['ai-troubleshooting','AI Troubleshooting','AI Tools'],['file-manager','File / Photo Manager','System'],['homepage-editor','Homepage Editor','System'],['theme-manager','Theme Manager','System'],['module-manager','Module Manager','System'],['system-center','System Center','System'],['platform-health','Platform Health','System'],['audit-logs','Audit Logs','System'],['cache-manager','Cache Manager','System'],['backup-restore','Backup / Restore','System'],['environment-integrations','Environment & Integrations','System'],['licensing','Licensing','System']
];
export const defaultServices = ['General Contracting','Plumbing','Electrical','HVAC','Roofing','Painting','Flooring','Landscaping','Emergency Repair'];
