import { useState, type FormEvent } from 'react';
import { ModulePageFrame, apiJson, asArray } from './moduleData';
import { Badge, Button, EmptyState } from '../../components/ui';
import { Link } from '../../components/Router';

export function AiQuotingPage() {
  const [requestId, setRequestId] = useState('');
  const [data, setData] = useState<any>(null);
  const [status, setStatus] = useState('');
  const load = async (id = requestId) => { if (!id) return; setData(await apiJson(`/api/ai/quote/request/${id}`)); };
  const run = async () => { setStatus('Running AI quote draft…'); const result = await apiJson<any>(`/api/ai/quote/request/${requestId}/run`, { method:'POST', body:'{}' }); setStatus(result.ok ? 'AI draft created. Human review required.' : `${result.code}: ${result.error}`); await load(requestId); };
  const draft = asArray<any>(data?.drafts)[0];
  return <ModulePageFrame permission="quotes.view" title="AI Quoting" eyebrow="Premium AI module" description="AI quote queue, draft estimates, low-confidence review, approved drafts, and source-backed estimator notes.">
    <section className="card"><h2>AI Quote Queue</h2><div className="form-grid"><input placeholder="Work request ID" value={requestId} onChange={(e)=>setRequestId(e.target.value)}/><Button onClick={()=>load()}>Load</Button><Button onClick={run}>Run AI</Button></div>{status && <p className="muted">{status}</p>}</section>
    {draft ? <section className="card"><div className="section-heading"><div><p className="eyebrow">AI Draft — needs human review</p><h2>{draft.summary || draft.output?.summary}</h2></div><Badge>{draft.confidence || 'low'} confidence</Badge></div><AiQuoteOutput output={draft.output}/><div className="button-row"><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/create-quote`,{method:'POST',body:'{}'})))}>Create/update quote</Button><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/approve`,{method:'POST',body:'{}'})))}>Approve draft</Button><Button variant="secondary" onClick={run}>Rerun AI</Button></div></section> : <EmptyState title="No AI drafts loaded" description="Enter a request ID or open the AI Estimate tab on a request detail to review drafts."/>}
    <section className="card"><h2>Sources reviewed</h2>{asArray<any>(data?.sources).map((s)=><p key={s.id || s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title || s.url}</a><br/><span className="muted">{s.snippet}</span></p>)}{!asArray(data?.sources).length && <p className="muted">Sources and search terms appear after SerpAPI research runs.</p>}</section>
  </ModulePageFrame>;
}

function AiQuoteOutput({ output }: { output:any }) { return <div className="drawer-grid"><section><h3>Scope</h3>{asArray<string>(output?.recommendedScope).map(x=><p key={x}>{x}</p>)}<h3>Questions</h3>{asArray<string>(output?.questionsForClient).map(x=><p key={x}>{x}</p>)}</section><section><h3>Labor</h3>{asArray<any>(output?.labor).map((x,i)=><p key={i}><strong>{x.task}</strong> {x.hoursLow}–{x.hoursHigh} hrs<br/><span className="muted">{x.notes}</span></p>)}</section><section><h3>Materials</h3>{asArray<any>(output?.materials).map((x,i)=><p key={i}><strong>{x.name}</strong> {x.quantity} — ${x.estimatedTotalCost || x.estimatedUnitCost || 0}<br/><span className="muted">{x.source} {x.notes}</span></p>)}</section><section><h3>Risk / price</h3><p>{output?.priceRange ? `$${output.priceRange.low}–$${output.priceRange.high}` : 'No range yet'}</p>{asArray<string>(output?.riskFactors).map(x=><p key={x}>{x}</p>)}</section></div>; }

export function AiTroubleshootingPage() {
  const [result, setResult] = useState<any>(null); const [status,setStatus]=useState('');
  const submit = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const f=new FormData(event.currentTarget); const body=Object.fromEntries(f.entries()); setStatus('Running diagnosis…'); const data=await apiJson<any>('/api/ai/troubleshooting/run',{method:'POST',body:JSON.stringify(body)}); setResult(data); setStatus(data.ok?'Diagnosis ready.':'Diagnosis failed.'); };
  const out=result?.output;
  return <ModulePageFrame permission="jobs.view" title="AI Troubleshooting" eyebrow="Premium AI module" description="Safety-first worker diagnostics with OpenAI, SerpAPI sources, step-by-step checks, and saved reports.">
    <form className="card form" onSubmit={submit}><h2>New troubleshooting diagnosis</h2><div className="form-grid"><input name="jobId" placeholder="Job ID (optional)"/><input name="workRequestId" placeholder="Work request ID (optional)"/><input name="equipmentType" placeholder="Equipment type"/><input name="make" placeholder="Make"/><input name="model" placeholder="Model"/><input name="serialNumber" placeholder="Serial number"/><input name="errorCode" placeholder="Error code"/><input name="urgency" placeholder="Urgency"/><textarea name="issue" placeholder="Issue description, symptoms, readings, prior repairs, power/voltage info, environment/location"/></div><Button>Run diagnosis</Button>{status && <p className="muted">{status}</p>}</form>
    {out && <section className="card"><div className="section-heading"><div><p className="eyebrow">AI troubleshooting is assistance only. Follow company procedures, codes, manufacturer documentation, and safety requirements.</p><h2>{out.workerSummary || 'Diagnostic report'}</h2></div><Badge>{out.confidence || 'low'} confidence</Badge></div><div className="drawer-grid"><section><h3>Safety warnings</h3>{asArray<string>(out.safetyWarnings).map(x=><p key={x}>{x}</p>)}<h3>Likely causes</h3>{asArray<any>(out.likelyCauses).map((x,i)=><p key={i}><strong>{x.cause}</strong> <Badge>{x.probability}</Badge><br/>{x.why}</p>)}</section><section><h3>Step-by-step diagnostics</h3>{asArray<any>(out.stepByStepDiagnostics).map((x,i)=><p key={i}><strong>Step {x.step}: {x.action}</strong><br/>Expected: {x.expectedResult}<br/>Pass: {x.ifPass}<br/>Fail: {x.ifFail}</p>)}</section><section><h3>Parts / measurements</h3>{asArray<string>(out.partsPossiblyNeeded).map(x=><p key={x}>{x}</p>)}{asArray<string>(out.measurementsToTake).map(x=><p key={x}>{x}</p>)}</section><section><h3>Sources reviewed</h3>{asArray<any>(out.sources).map((s)=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><br/><span className="muted">{s.snippet}</span></p>)}</section></div><div className="button-row"><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/troubleshooting/${result.id}/save-to-job`,{method:'POST',body:JSON.stringify({})})))}>Save to work order</Button><Button variant="secondary" onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/troubleshooting/${result.id}/create-checklist`,{method:'POST',body:'{}'})))}>Create checklist</Button><Link className="button secondary" href={`/jobs?aiTroubleshooting=${result.id}`}>Share with worker</Link></div></section>}
  </ModulePageFrame>;
}
