import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent } from 'react';
import { ModulePageFrame, apiJson, asArray } from './moduleData';
import { Badge, Button, EmptyState } from '../../components/ui';
import { Link } from '../../components/Router';

type JobOption = { id:string; displayId:string; title:string; clientName:string; clientId:string; propertyAddress:string; propertyId:string; status:string; scope:string; quoteId?:string; requestId?:string; createdAt:string; scheduledAt?:string; assignedTechnician?:string; equipment?:{type?:string; make?:string; model?:string; serial?:string} };
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

type WorkRequestOption = { id:string; displayId:string; title:string; clientName:string; clientEmail?:string; phone?:string; address:string; status:string; serviceCategory:string; createdAt:string; descriptionPreview:string; hasAiQuote:boolean; aiStatus:'not_run'|'draft'|'approved'|'failed' };

export function AiQuotingPage() {
  const [selectedRequest, setSelectedRequest] = useState<WorkRequestOption | null>(null);
  const [data, setData] = useState<any>(null);
  const [activeDraftId, setActiveDraftId] = useState('');
  const [status, setStatus] = useState('Select a work request to begin.');
  const requestId = selectedRequest?.id || '';
  const load = async (id = requestId) => { if (!id) return; try { setData(await apiJson(`/api/ai/quote/request/${id}`)); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Unable to load AI quote.'; setStatus(message.includes('AI_NOT_CONFIGURED') ? 'OpenAI is not configured. Add OPENAI_API_KEY in AI settings before running quotes.' : message); } };
  const run = async () => { if (!requestId) { setStatus('Choose a work request first.'); return; } setStatus('AI quote is queued.'); try { const result = await apiJson<any>(`/api/ai/quote/request/${requestId}/run`, { method:'POST', body:'{}' }); const draftId = result.draftId; if (!draftId || !uuidPattern.test(draftId)) { setStatus('AI quoting did not return a valid draft id. Please retry.'); return; } setActiveDraftId(draftId); await load(requestId); setStatus(result.message || 'AI quote is queued.'); void apiJson<any>(`/api/ai/quote/${draftId}/process`, { method:'POST', body:'{}' }).then(async () => { await load(requestId); setStatus('AI draft ready for human review.'); }).catch((caught) => { const message = caught instanceof Error ? caught.message : 'Processing failed.'; setStatus(message.includes('AI_TIMEOUT') ? 'AI quote timed out. Retry AI when ready, or create a manual quote.' : `AI quote processing failed: ${message}`); }); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Request failed.'; setStatus(message.includes('AI_NOT_CONFIGURED') ? 'OpenAI is not configured. Open Settings → AI to finish setup.' : `AI quoting could not run: ${message}`); } };
  const draft = asArray<any>(data?.drafts)[0];
  useEffect(() => { const draftId = activeDraftId || draft?.id; if (!requestId || !draftId || !['queued','running'].includes(draft?.status || 'queued')) return; const timer = setInterval(async () => { try { const statusResult = await apiJson<any>(`/api/ai/quote/${draftId}/status`); await load(requestId); if (statusResult?.draft?.status === 'needs_review') { setStatus('AI draft ready for human review.'); clearInterval(timer); } if (statusResult?.draft?.status === 'failed') { setStatus(`${statusResult.draft.errorMessage || 'AI quote failed.'} Retry AI or create a manual quote.`); clearInterval(timer); } } catch { await load(requestId); } }, 3000); return () => clearInterval(timer); }, [requestId, activeDraftId, draft?.id, draft?.status]);
  return <ModulePageFrame permission="quotes.view" title="AI Quoting" eyebrow="Premium AI module" description="Search work requests, review request context, and run AI quote drafts without pasting UUIDs.">
    <section className="card ai-quote-picker-card"><div className="section-heading"><div><h2>Work Request Picker</h2><p className="muted">Search by request number, customer, email, phone, address, title, service, status, date, or description.</p></div><Badge>{selectedRequest ? selectedRequest.displayId : 'Recent requests'}</Badge></div><WorkRequestPicker value={selectedRequest} onChange={(request) => { setSelectedRequest(request); setData(null); setActiveDraftId(''); setStatus(request ? 'Request selected. Confirm when you are ready to run AI.' : 'Selection cleared.'); if (request) load(request.id); }}/>{status && <p className="muted ai-status-message">{status} {status.includes('OpenAI') && <Link href="/settings/ai">Open AI settings</Link>}</p>}</section>
    {selectedRequest ? <RequestPreview request={selectedRequest} draft={draft} onRun={run} onCreateQuote={async()=> draft && setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/create-quote`,{method:'POST',body:'{}'})))}/> : <EmptyState title="No work request selected" description="Click the picker to browse recent requests or search by customer, address, request number, status, date, or description."/>}
    {draft ? <section className="card"><div className="section-heading"><div><p className="eyebrow">AI Draft — needs human review</p><h2>{draft.summary || draft.output?.summary}</h2></div><Badge>{draft.confidence || 'low'} confidence</Badge></div><AiQuoteOutput output={draft.output}/><div className="button-row"><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/create-quote`,{method:'POST',body:'{}'})))}>Create Quote Draft</Button><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/approve`,{method:'POST',body:'{}'})))}>Approve draft</Button><Button variant="secondary" onClick={run}>Rerun AI</Button></div></section> : selectedRequest ? <EmptyState title="AI has not run for this request" description="Review the request preview and choose Run AI Quote when ready. Public auto-AI estimate workflows remain unchanged."/> : null}
    <section className="card"><h2>Sources reviewed</h2>{asArray<any>(data?.sources).map((s)=><p key={s.id || s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title || s.url}</a><br/><span className="muted">{s.snippet}</span></p>)}{!asArray(data?.sources).length && <p className="muted">Sources and search terms appear after SerpAPI research runs.</p>}</section>
  </ModulePageFrame>;
}

function WorkRequestPicker({ value, onChange }: { value: WorkRequestOption | null; onChange: (request: WorkRequestOption | null) => void }) {
  const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [requests,setRequests]=useState<WorkRequestOption[]>([]); const [active,setActive]=useState(0); const box=useRef<HTMLDivElement>(null);
  const search = async (term = q) => { setLoading(true); try { const p = await apiJson<{ok:boolean;requests:WorkRequestOption[]}>(`/api/ai/quote/requests/search?q=${encodeURIComponent(term)}&limit=20`); setRequests(p.requests || []); } catch (e) { setRequests([]); } finally { setLoading(false); } };
  useEffect(() => { if (open) search(q); }, [open]);
  useEffect(() => { if (!open) return; const t=setTimeout(()=>search(q),220); return ()=>clearTimeout(t); }, [q]);
  useEffect(() => { const fn=(e:MouseEvent)=>{ if(box.current&&!box.current.contains(e.target as Node)) setOpen(false); }; document.addEventListener('mousedown',fn); return()=>document.removeEventListener('mousedown',fn); }, []);
  const choose=(r:WorkRequestOption)=>{ onChange(r); setQ(''); setOpen(false); };
  const key=(e:KeyboardEvent<HTMLInputElement>)=>{ if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive((x)=>Math.min(x+1,requests.length-1));} if(e.key==='ArrowUp'){e.preventDefault();setActive((x)=>Math.max(x-1,0));} if(e.key==='Enter'&&open&&requests[active]){e.preventDefault();choose(requests[active]);} if(e.key==='Escape')setOpen(false); };
  return <div className="work-request-combobox" ref={box}><div className="work-request-input-row" role="combobox" aria-expanded={open}><input onFocus={()=>setOpen(true)} onKeyDown={key} value={q || (open ? '' : value ? `${value.displayId} · ${value.title}` : '')} onChange={(e)=>{setQ(e.target.value);setOpen(true);setActive(0);}} placeholder="Search recent work requests…"/>{value && <button type="button" onClick={()=>onChange(null)}>Clear</button>}</div>{open && <div className="work-request-menu" role="listbox">{loading && <p className="muted">Searching requests…</p>}{!loading && !requests.length && <EmptyState title="No work requests found" description="New estimate submissions will appear here."/>}{requests.map((r,i)=><button type="button" role="option" aria-selected={i===active} className={i===active?'active':''} key={r.id} onMouseEnter={()=>setActive(i)} onClick={()=>choose(r)}><span><strong>{r.title}</strong><em>{r.clientName} · {r.address}</em><small><Badge>{r.status}</Badge> Submitted {formatDate(r.createdAt)} · {r.serviceCategory}</small><small>{r.descriptionPreview || 'No description provided.'}</small></span><Badge tone={r.aiStatus==='not_run'?'warning':r.aiStatus==='approved'?'success':undefined}>AI: {r.aiStatus.replace('_',' ')}</Badge></button>)}</div>}</div>;
}
function RequestPreview({ request, draft, onRun, onCreateQuote }: { request: WorkRequestOption; draft:any; onRun:()=>void; onCreateQuote:()=>void }) { return <section className="card request-preview-card"><div><p className="eyebrow">Selected request</p><h2>{request.title}</h2><p>{request.clientName} · {request.address}</p><p className="muted">{request.descriptionPreview || 'No description provided.'}</p></div><div className="request-preview-meta"><Badge>{request.status}</Badge><Badge>{request.serviceCategory}</Badge><Badge tone={request.aiStatus==='not_run'?'warning':'success'}>AI: {request.aiStatus.replace('_',' ')}</Badge><span>Submitted {formatDate(request.createdAt)}</span><span>{request.clientEmail} {request.phone}</span><span>Photos/files appear on the full request when uploaded.</span></div><div className="button-row"><Button onClick={onRun}>Run AI Quote</Button><Link className="button secondary" href={`/requests/${request.id}`}>View Full Request</Link>{draft && <Button variant="secondary" onClick={onCreateQuote}>Create Quote Draft if AI result exists</Button>}</div></section>; }
function formatDate(value:string){ try { return new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}); } catch { return value; } }

function AiQuoteOutput({ output }: { output:any }) { const safe = { recommendedScope: [], questionsForClient: [], labor: [], materials: [], riskFactors: [], priceRange: null, confidence: 'low', ...(output || {}) }; const empty = !output || !Object.keys(output || {}).length; if (empty) return <EmptyState title="AI quote is researching…" description="Scope, questions, labor, materials, risk, price, and sources will populate automatically."/>; return <div className="drawer-grid"><section><h3>Scope</h3>{asArray<string>(safe.recommendedScope).map(x=><p key={x}>{x}</p>)}{!asArray(safe.recommendedScope).length && <p className="muted">No scope items yet.</p>}<h3>Questions</h3>{asArray<string>(safe.questionsForClient).map(x=><p key={x}>{x}</p>)}</section><section><h3>Labor</h3>{asArray<any>(safe.labor).map((x,i)=><p key={i}><strong>{x.task}</strong> {x.hoursLow}–{x.hoursHigh} hrs<br/><span className="muted">{x.notes}</span></p>)}</section><section><h3>Materials</h3>{asArray<any>(safe.materials).map((x,i)=><p key={i}><strong>{x.name}</strong> {x.quantity} — ${x.estimatedTotalCost || x.estimatedUnitCost || 0}<br/><span className="muted">{x.source} {x.notes}</span></p>)}</section><section><h3>Risk / price</h3><p>{safe.priceRange ? `$${safe.priceRange.low}–$${safe.priceRange.high}` : 'No range yet'}</p>{asArray<string>(safe.riskFactors).map(x=><p key={x}>{x}</p>)}</section></div>; }

export function AiTroubleshootingPage() {
  const [result, setResult] = useState<any>(null); const [status,setStatus]=useState(''); const [aiRunId,setAiRunId]=useState(''); const [selectedJob,setSelectedJob]=useState<JobOption|null>(null); const mounted=useRef(true);
  useEffect(() => () => { mounted.current=false; }, []);
  const safeStatus=(message:string)=>{ if(mounted.current) setStatus(message); };
  const refreshReport = async (id:string) => { if (!uuidPattern.test(id)) { safeStatus('AI troubleshooting did not return a valid report id.'); return null; } const data=await apiJson<any>(`/api/ai/troubleshooting/${id}`); const current=data.report || data.record || data; if (mounted.current) setResult(current); if (current?.status === 'complete') safeStatus('Diagnosis ready.'); else if (current?.status === 'failed') safeStatus(current.error_message === 'AI_TIMEOUT' ? 'AI troubleshooting could not run: AI_TIMEOUT' : `AI troubleshooting could not run: ${current.error_message || 'Request failed.'}`); else safeStatus('AI is researching and building diagnostics…'); return current; };
  const submit = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const form=event.currentTarget; const f=new FormData(form); const body:any=Object.fromEntries(f.entries()); if(selectedJob) body.jobId=selectedJob.id; Object.keys(body).forEach((k)=>{ if(body[k]==='') delete body[k]; }); if(!body.jobId && !body.issue) { safeStatus('Describe the issue or select a job.'); return; } safeStatus('Queuing diagnosis…'); setResult(null); try { const queued=await apiJson<any>('/api/ai/troubleshooting/run',{method:'POST',body:JSON.stringify(body)}); if (queued?.ok === false) { safeStatus(queued.error || 'AI troubleshooting could not run.'); return; } const id=queued.reportId || queued.aiRunId; if (!id || !uuidPattern.test(id)) { safeStatus('AI troubleshooting did not return a valid report id.'); return; } setAiRunId(id); safeStatus(queued.message || 'AI troubleshooting has started.'); void apiJson<any>(`/api/ai/troubleshooting/${id}/process`,{method:'POST',body:'{}'}).then((data)=>{ const current=data.report || data.record; if(current && mounted.current) setResult(current); if(current?.status==='complete') safeStatus('Diagnosis ready.'); }).catch((caught)=>{ const message=caught instanceof Error ? caught.message : 'Processing failed.'; safeStatus(message.includes('AI_TIMEOUT') ? 'AI troubleshooting could not run: AI_TIMEOUT' : `AI troubleshooting could not run: ${message}`); }); await refreshReport(id); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Request failed.'; safeStatus(message.includes('AI_NOT_CONFIGURED') ? 'AI is not configured. Add OPENAI_API_KEY in settings/environment.' : `AI troubleshooting could not run: ${message}`); } };
  useEffect(() => { if (!aiRunId) return; const timer=setInterval(() => { refreshReport(aiRunId).then((report) => { if (['complete','failed'].includes(report?.status)) clearInterval(timer); }).catch((caught)=>safeStatus(caught instanceof Error ? caught.message : 'Unable to refresh AI status.')); }, 3000); return () => clearInterval(timer); }, [aiRunId]);
  const out=result?.output || result?.record?.output; const reportId=result?.id;
  return <ModulePageFrame permission="jobs.view" title="AI Troubleshooting" eyebrow="Premium AI module" description="Safety-first worker diagnostics with OpenAI, SerpAPI sources, step-by-step checks, and saved reports.">
    <form className="card form" onSubmit={submit}><h2>New troubleshooting diagnosis</h2><JobPicker value={selectedJob} onChange={(job)=>{ setSelectedJob(job); if(job) safeStatus(`${job.displayId} selected. Scope and equipment will be included.`); }}/><div className="form-grid" key={selectedJob?.id || 'manual'}><input name="equipmentType" placeholder="Equipment type" defaultValue={selectedJob?.equipment?.type || ''}/><input name="make" placeholder="Make" defaultValue={selectedJob?.equipment?.make || ''}/><input name="model" placeholder="Model" defaultValue={selectedJob?.equipment?.model || ''}/><input name="serialNumber" placeholder="Serial number" defaultValue={selectedJob?.equipment?.serial || ''}/><input name="errorCode" placeholder="Error code"/><input name="urgency" placeholder="Urgency"/><textarea name="issue" placeholder="Issue description, symptoms, readings, prior repairs, power/voltage info, environment/location" defaultValue={selectedJob ? (selectedJob.scope || selectedJob.title) : ''}/><textarea name="notes" placeholder="Additional technician notes"/></div><Button>Run diagnosis</Button>{status && <p className="muted">{status}</p>}</form>
    {out && <section className="card"><div className="section-heading"><div><p className="eyebrow">AI troubleshooting is assistance only. Follow company procedures, codes, manufacturer documentation, and safety requirements.</p><h2>{out.workerSummary || 'Diagnostic report'}</h2></div><Badge>{out.confidence || 'low'} confidence</Badge></div><div className="drawer-grid"><section><h3>Safety warnings</h3>{asArray<string>(out.safetyWarnings).map(x=><p key={x}>{x}</p>)}<h3>Likely causes</h3>{asArray<any>(out.likelyCauses).map((x,i)=><p key={i}><strong>{x.cause}</strong> <Badge>{x.probability}</Badge><br/>{x.why}</p>)}</section><section><h3>Step-by-step diagnostics</h3>{asArray<any>(out.stepByStepDiagnostics).map((x,i)=><p key={i}><strong>Step {x.step}: {x.action}</strong><br/>Expected: {x.expectedResult}<br/>Pass: {x.ifPass}<br/>Fail: {x.ifFail}</p>)}</section><section><h3>Parts / measurements</h3>{asArray<string>(out.partsPossiblyNeeded).map(x=><p key={x}>{x}</p>)}{asArray<string>(out.measurementsToTake).map(x=><p key={x}>{x}</p>)}</section><section><h3>Sources reviewed</h3>{asArray<any>(out.sources).map((s)=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><br/><span className="muted">{s.snippet}</span></p>)}</section></div>{reportId && <div className="button-row"><Button onClick={async()=>{try{safeStatus(JSON.stringify(await apiJson(`/api/ai/troubleshooting/${reportId}/save-to-job`,{method:'POST',body:JSON.stringify({jobId:selectedJob?.id})})))}catch(caught){safeStatus(caught instanceof Error ? caught.message : 'Save failed.')}}}>Save to work order</Button><Button variant="secondary" onClick={async()=>{try{safeStatus(JSON.stringify(await apiJson(`/api/ai/troubleshooting/${reportId}/create-checklist`,{method:'POST',body:'{}'})))}catch(caught){safeStatus(caught instanceof Error ? caught.message : 'Checklist failed.')}}}>Create checklist</Button><Link className="button secondary" href={`/jobs?aiTroubleshooting=${reportId}`}>Share with worker</Link></div>}</section>}
  </ModulePageFrame>;
}

function JobPicker({ value, onChange }: { value: JobOption | null; onChange: (job: JobOption | null) => void }) {
  const [q,setQ]=useState(''); const [filter,setFilter]=useState('active'); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [jobs,setJobs]=useState<JobOption[]>([]); const box=useRef<HTMLDivElement>(null);
  const search=async(term=q, status=filter)=>{ setLoading(true); try { const p=await apiJson<{ok:boolean;jobs:JobOption[]}>(`/api/ai/troubleshooting/jobs/search?q=${encodeURIComponent(term)}&status=${encodeURIComponent(status)}&limit=20`); setJobs(p.jobs||[]); } catch { setJobs([]); } finally { setLoading(false); } };
  useEffect(()=>{ if(open) search(q,filter); },[open,filter]); useEffect(()=>{ if(!open) return; const t=setTimeout(()=>search(q,filter),220); return()=>clearTimeout(t); },[q]);
  useEffect(()=>{ const fn=(e:MouseEvent)=>{ if(box.current&&!box.current.contains(e.target as Node)) setOpen(false); }; document.addEventListener('mousedown',fn); return()=>document.removeEventListener('mousedown',fn); },[]);
  const choose=(j:JobOption)=>{ onChange(j); setQ(''); setOpen(false); };
  return <div className="work-request-combobox job-picker-premium" ref={box}><label>Job / Work Order</label><div className="job-filter-tabs">{['active','scheduled','in_progress','waiting','completed','all'].map((x)=><button type="button" key={x} className={filter===x?'active':''} onClick={()=>{setFilter(x);setOpen(true);}}>{x.replace('_',' ')}</button>)}</div><div className="work-request-input-row" role="combobox" aria-expanded={open}><input onFocus={()=>setOpen(true)} value={q || (open ? '' : value ? `${value.displayId} · ${value.title}` : '')} onChange={(e)=>{setQ(e.target.value);setOpen(true);}} placeholder="Search job title, work order #, client, address, status, technician, quote, or request…"/>{value && <button type="button" onClick={()=>onChange(null)}>Clear</button>}</div>{open && <div className="work-request-menu" role="listbox">{loading && <p className="muted">Searching jobs…</p>}{!loading && !jobs.length && <EmptyState title="No jobs found" description="Active jobs and work orders appear by default. Use Completed or All if needed."/>}{jobs.map((j)=><button type="button" role="option" key={j.id} onClick={()=>choose(j)}><span><strong>{j.title}</strong><em>{j.clientName} · {j.propertyAddress}</em><small><Badge>{j.status}</Badge> Tech: {j.assignedTechnician || 'Unassigned'} · {j.scheduledAt ? `Scheduled ${formatDate(j.scheduledAt)}` : `Created ${formatDate(j.createdAt)}`} {j.quoteId ? `· Quote ${j.quoteId.slice(0,8)}` : ''} {j.requestId ? `· Request ${j.requestId.slice(0,8)}` : ''}</small><small>{j.scope || 'No scope provided.'}</small></span></button>)}</div>}{value && <section className="job-selected-preview"><div><p className="eyebrow">Selected work order</p><h3>{value.title}</h3><p>{value.clientName} · {value.propertyAddress}</p></div><Badge>{value.status}</Badge><p>{value.scope || 'No scope on file.'}</p><small>Technician: {value.assignedTechnician || 'Unassigned'} · Quote: {value.quoteId?.slice(0,8) || '—'} · Request: {value.requestId?.slice(0,8) || '—'}</small>{value.equipment && <small>Equipment: {[value.equipment.type,value.equipment.make,value.equipment.model,value.equipment.serial].filter(Boolean).join(' · ') || 'No linked asset'}</small>}</section>}</div>;
}
