import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent } from 'react';
import { ModulePageFrame, apiJson, asArray } from './moduleData';
import { Badge, Button, EmptyState } from '../../components/ui';
import { Link } from '../../components/Router';

type WorkRequestOption = { id:string; displayId:string; title:string; clientName:string; clientEmail?:string; phone?:string; address:string; status:string; serviceCategory:string; createdAt:string; descriptionPreview:string; hasAiQuote:boolean; aiStatus:'not_run'|'draft'|'approved'|'failed' };

export function AiQuotingPage() {
  const [selectedRequest, setSelectedRequest] = useState<WorkRequestOption | null>(null);
  const [data, setData] = useState<any>(null);
  const [status, setStatus] = useState('Select a work request to begin.');
  const requestId = selectedRequest?.id || '';
  const load = async (id = requestId) => { if (!id) return; try { setData(await apiJson(`/api/ai/quote/request/${id}`)); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Unable to load AI quote.'; setStatus(message.includes('AI_NOT_CONFIGURED') ? 'OpenAI is not configured. Add OPENAI_API_KEY in AI settings before running quotes.' : message); } };
  const run = async () => { if (!requestId) { setStatus('Choose a work request first.'); return; } setStatus('Running AI quote draft…'); try { const result = await apiJson<any>(`/api/ai/quote/request/${requestId}/run`, { method:'POST', body:'{}' }); setStatus(result.ok ? 'AI draft created. Human review required.' : `${result.code}: ${result.error}`); await load(requestId); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Request failed.'; setStatus(message.includes('AI_NOT_CONFIGURED') ? 'OpenAI is not configured. Open Settings → AI to finish setup.' : `AI quoting could not run: ${message}`); } };
  const draft = asArray<any>(data?.drafts)[0];
  return <ModulePageFrame permission="quotes.view" title="AI Quoting" eyebrow="Premium AI module" description="Search work requests, review request context, and run AI quote drafts without pasting UUIDs.">
    <section className="card ai-quote-picker-card"><div className="section-heading"><div><h2>Work Request Picker</h2><p className="muted">Search by request number, customer, email, phone, address, title, service, status, date, or description.</p></div><Badge>{selectedRequest ? selectedRequest.displayId : 'Recent requests'}</Badge></div><WorkRequestPicker value={selectedRequest} onChange={(request) => { setSelectedRequest(request); setData(null); setStatus(request ? 'Request selected. Confirm when you are ready to run AI.' : 'Selection cleared.'); if (request) load(request.id); }}/>{status && <p className="muted ai-status-message">{status} {status.includes('OpenAI') && <Link href="/settings/ai">Open AI settings</Link>}</p>}</section>
    {selectedRequest ? <RequestPreview request={selectedRequest} draft={draft} onRun={run} onCreateQuote={async()=> draft && setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/create-quote`,{method:'POST',body:'{}'})))}/> : <EmptyState title="No work request selected" description="Click the picker to browse recent requests or search by customer, address, request number, status, date, or description."/>}
    {draft ? <section className="card"><div className="section-heading"><div><p className="eyebrow">AI Draft — needs human review</p><h2>{draft.summary || draft.output?.summary}</h2></div><Badge>{draft.confidence || 'low'} confidence</Badge></div><AiQuoteOutput output={draft.output}/><div className="button-row"><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/create-quote`,{method:'POST',body:'{}'})))}>Create Quote Draft</Button><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/quote/${draft.id}/approve`,{method:'POST',body:'{}'})))}>Approve draft</Button><Button variant="secondary" onClick={run}>Rerun AI</Button></div></section> : selectedRequest ? <EmptyState title="AI has not run for this request" description="Review the request preview and choose Run AI Quote when ready. Public auto-AI estimate workflows remain unchanged."/> : null}
    <section className="card"><h2>Sources reviewed</h2>{asArray<any>(data?.sources).map((s)=><p key={s.id || s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title || s.url}</a><br/><span className="muted">{s.snippet}</span></p>)}{!asArray(data?.sources).length && <p className="muted">Sources and search terms appear after SerpAPI research runs.</p>}</section>
  </ModulePageFrame>;
}

function WorkRequestPicker({ value, onChange }: { value: WorkRequestOption | null; onChange: (request: WorkRequestOption | null) => void }) {
  const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [requests,setRequests]=useState<WorkRequestOption[]>([]); const [active,setActive]=useState(0); const box=useRef<HTMLDivElement>(null);
  const search = async (term = q) => { setLoading(true); try { const p = await apiJson<{ok:boolean;requests:WorkRequestOption[]}>(`/api/ai/quote/requests/search?q=${encodeURIComponent(term)}&limit=20`); setRequests(p.requests || []); } catch (e) { setRequests([]); } finally { setLoading(false); } };
  useEffect(() => { if (open) search(q); }, [open]);
  useEffect(() => { if (!open) return; const t=setTimeout(()=>search(q),220); return ()=>clearTimeout(t); }, [q]);
  useEffect(() => { const fn=(e:MouseEvent)=>{ if(box.current&&!box.current.contains(e.target as Node)) setOpen(false); }; document.addEventListener('mousedown',fn); return()=>document.removeEventListener('mousedown',fn); }, []);
  const choose=(r:WorkRequestOption)=>{ onChange(r); setQ(''); setOpen(false); };
  const key=(e:KeyboardEvent<HTMLInputElement>)=>{ if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive((x)=>Math.min(x+1,requests.length-1));} if(e.key==='ArrowUp'){e.preventDefault();setActive((x)=>Math.max(x-1,0));} if(e.key==='Enter'&&open&&requests[active]){e.preventDefault();choose(requests[active]);} if(e.key==='Escape')setOpen(false); };
  return <div className="work-request-combobox" ref={box}><div className="work-request-input-row" role="combobox" aria-expanded={open}><input onFocus={()=>setOpen(true)} onKeyDown={key} value={q || (open ? '' : value ? `${value.displayId} · ${value.title}` : '')} onChange={(e)=>{setQ(e.target.value);setOpen(true);setActive(0);}} placeholder="Search recent work requests…"/>{value && <button type="button" onClick={()=>onChange(null)}>Clear</button>}</div>{open && <div className="work-request-menu" role="listbox">{loading && <p className="muted">Searching requests…</p>}{!loading && !requests.length && <EmptyState title="No work requests found" description="New estimate submissions will appear here."/>}{requests.map((r,i)=><button type="button" role="option" aria-selected={i===active} className={i===active?'active':''} key={r.id} onMouseEnter={()=>setActive(i)} onClick={()=>choose(r)}><span><strong>{r.title}</strong><em>{r.clientName} · {r.address}</em><small><Badge>{r.status}</Badge> Submitted {formatDate(r.createdAt)} · {r.serviceCategory}</small><small>{r.descriptionPreview || 'No description provided.'}</small></span><Badge tone={r.aiStatus==='not_run'?'warning':r.aiStatus==='approved'?'success':undefined}>AI: {r.aiStatus.replace('_',' ')}</Badge></button>)}</div>}</div>;
}
function RequestPreview({ request, draft, onRun, onCreateQuote }: { request: WorkRequestOption; draft:any; onRun:()=>void; onCreateQuote:()=>void }) { return <section className="card request-preview-card"><div><p className="eyebrow">Selected request</p><h2>{request.title}</h2><p>{request.clientName} · {request.address}</p><p className="muted">{request.descriptionPreview || 'No description provided.'}</p></div><div className="request-preview-meta"><Badge>{request.status}</Badge><Badge>{request.serviceCategory}</Badge><Badge tone={request.aiStatus==='not_run'?'warning':'success'}>AI: {request.aiStatus.replace('_',' ')}</Badge><span>Submitted {formatDate(request.createdAt)}</span><span>{request.clientEmail} {request.phone}</span><span>Photos/files appear on the full request when uploaded.</span></div><div className="button-row"><Button onClick={onRun}>Run AI Quote</Button><Link className="button secondary" href={`/requests/${request.id}`}>View Full Request</Link>{draft && <Button variant="secondary" onClick={onCreateQuote}>Create Quote Draft if AI result exists</Button>}</div></section>; }
function formatDate(value:string){ try { return new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}); } catch { return value; } }

function AiQuoteOutput({ output }: { output:any }) { return <div className="drawer-grid"><section><h3>Scope</h3>{asArray<string>(output?.recommendedScope).map(x=><p key={x}>{x}</p>)}<h3>Questions</h3>{asArray<string>(output?.questionsForClient).map(x=><p key={x}>{x}</p>)}</section><section><h3>Labor</h3>{asArray<any>(output?.labor).map((x,i)=><p key={i}><strong>{x.task}</strong> {x.hoursLow}–{x.hoursHigh} hrs<br/><span className="muted">{x.notes}</span></p>)}</section><section><h3>Materials</h3>{asArray<any>(output?.materials).map((x,i)=><p key={i}><strong>{x.name}</strong> {x.quantity} — ${x.estimatedTotalCost || x.estimatedUnitCost || 0}<br/><span className="muted">{x.source} {x.notes}</span></p>)}</section><section><h3>Risk / price</h3><p>{output?.priceRange ? `$${output.priceRange.low}–$${output.priceRange.high}` : 'No range yet'}</p>{asArray<string>(output?.riskFactors).map(x=><p key={x}>{x}</p>)}</section></div>; }

export function AiTroubleshootingPage() {
  const [result, setResult] = useState<any>(null); const [status,setStatus]=useState('');
  const submit = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const f=new FormData(event.currentTarget); const body=Object.fromEntries(f.entries()); setStatus('Running diagnosis…'); try { const data=await apiJson<any>('/api/ai/troubleshooting/run',{method:'POST',body:JSON.stringify(body)}); setResult(data); setStatus(data.ok ? (data.warnings?.includes('SERPAPI_NOT_CONFIGURED') ? 'Diagnosis ready. Web research is not configured, so only OpenAI was used.' : 'Diagnosis ready.') : `AI troubleshooting could not run: ${data.error || 'Request failed.'}`); } catch (caught) { const message = caught instanceof Error ? caught.message : 'Request failed.'; setStatus(message.includes('AI_NOT_CONFIGURED') ? 'AI is not configured. Add OPENAI_API_KEY in settings/environment.' : `AI troubleshooting could not run: ${message}`); } };
  const out=result?.output;
  return <ModulePageFrame permission="jobs.view" title="AI Troubleshooting" eyebrow="Premium AI module" description="Safety-first worker diagnostics with OpenAI, SerpAPI sources, step-by-step checks, and saved reports.">
    <form className="card form" onSubmit={submit}><h2>New troubleshooting diagnosis</h2><div className="form-grid"><input name="jobId" placeholder="Job ID (optional)"/><input name="workRequestId" placeholder="Work request ID (optional)"/><input name="equipmentType" placeholder="Equipment type"/><input name="make" placeholder="Make"/><input name="model" placeholder="Model"/><input name="serialNumber" placeholder="Serial number"/><input name="errorCode" placeholder="Error code"/><input name="urgency" placeholder="Urgency"/><textarea name="issue" placeholder="Issue description, symptoms, readings, prior repairs, power/voltage info, environment/location"/></div><Button>Run diagnosis</Button>{status && <p className="muted">{status}</p>}</form>
    {out && <section className="card"><div className="section-heading"><div><p className="eyebrow">AI troubleshooting is assistance only. Follow company procedures, codes, manufacturer documentation, and safety requirements.</p><h2>{out.workerSummary || 'Diagnostic report'}</h2></div><Badge>{out.confidence || 'low'} confidence</Badge></div><div className="drawer-grid"><section><h3>Safety warnings</h3>{asArray<string>(out.safetyWarnings).map(x=><p key={x}>{x}</p>)}<h3>Likely causes</h3>{asArray<any>(out.likelyCauses).map((x,i)=><p key={i}><strong>{x.cause}</strong> <Badge>{x.probability}</Badge><br/>{x.why}</p>)}</section><section><h3>Step-by-step diagnostics</h3>{asArray<any>(out.stepByStepDiagnostics).map((x,i)=><p key={i}><strong>Step {x.step}: {x.action}</strong><br/>Expected: {x.expectedResult}<br/>Pass: {x.ifPass}<br/>Fail: {x.ifFail}</p>)}</section><section><h3>Parts / measurements</h3>{asArray<string>(out.partsPossiblyNeeded).map(x=><p key={x}>{x}</p>)}{asArray<string>(out.measurementsToTake).map(x=><p key={x}>{x}</p>)}</section><section><h3>Sources reviewed</h3>{asArray<any>(out.sources).map((s)=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><br/><span className="muted">{s.snippet}</span></p>)}</section></div><div className="button-row"><Button onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/troubleshooting/${result.id}/save-to-job`,{method:'POST',body:JSON.stringify({})})))}>Save to work order</Button><Button variant="secondary" onClick={async()=>setStatus(JSON.stringify(await apiJson(`/api/ai/troubleshooting/${result.id}/create-checklist`,{method:'POST',body:'{}'})))}>Create checklist</Button><Link className="button secondary" href={`/jobs?aiTroubleshooting=${result.id}`}>Share with worker</Link></div></section>}
  </ModulePageFrame>;
}
