import { useState } from 'react';
import { Badge, Button } from '../../components/ui';
import { apiJson, asArray, dateTime, DetailDrawer, DetailFacts, dollarsToCents, ModulePageFrame, ModuleStatus, money, RecordsTable, submitForm, text, Toolbar, useCanManage, useModuleRecords, useRecordDetail, WorkflowBoard, WorkflowButtons, type Row } from './moduleData';

type InvoiceRow = Row & { status?: string; client?: string; job?: string; total?: number; deposit?: number; paid?: number; balance?: number; dueAt?: string; items?: Row[]; payments?: Row[]; jobId?: string; quoteId?: string };
const statuses = ['draft','sent','partially_paid','paid','overdue','void'];

export function InvoicesPage() {
  const [query, setQuery] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState<string>();
  const [notice, setNotice] = useState('');
  const canManage = useCanManage('invoices.manage');
  const collection = useModuleRecords<InvoiceRow>('/api/invoices', query);
  const detail = useRecordDetail<InvoiceRow>('/api/invoices', selectedId);
  const selected = detail.record || collection.records.find((record) => record.id === selectedId);
  const workflow = async (path: string, message: string) => { await apiJson(path, { method: 'POST', body: JSON.stringify({}) }); setNotice(message); await collection.reload(); if (selectedId) await detail.reload(selectedId); };
  return <ModulePageFrame permission="invoices.view" title="Invoices" eyebrow="Standalone receivables" description="Create, send, collect, and inspect real invoices with balances, line items, payments, and receivable workflow actions." action={<Badge>{money(asArray(collection.records).reduce((sum, row) => sum + Number(row.balance || 0), 0))} outstanding</Badge>}>
    <Toolbar query={query} onQuery={setQuery} canManage={canManage} createLabel="Create Invoice" onCreate={() => setShowCreate(!showCreate)} secondary={<select aria-label="Invoice status filter" onChange={(event) => setQuery(event.target.value)}><option value="">All invoices</option>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select>}/>
    {notice && <p className="muted">{notice}</p>}
    {showCreate && <InvoiceCreateForm onSaved={async () => { setShowCreate(false); await collection.reload(); }}/>}
    <ModuleStatus loading={collection.loading} error={collection.error}/>
    {!collection.loading && !collection.error && <><WorkflowBoard records={collection.records} statuses={statuses} onSelect={(row) => setSelectedId(row.id)} titleFor={(row) => `${row.client || 'Invoice'} · ${money(row.balance)}`}/><section className="card"><div className="section-heading"><div><p className="eyebrow">A/R ledger</p><h2>Invoice list</h2></div><Button variant="secondary" onClick={collection.reload}>Refresh</Button></div><RecordsTable records={collection.records} emptyTitle="No invoices yet" onSelect={(row) => setSelectedId(row.id)} columns={[{ key: 'client', label: 'Client' }, { key: 'job', label: 'Job' }, { key: 'status', label: 'Status', kind: 'status' }, { key: 'total', label: 'Total', kind: 'money' }, { key: 'paid', label: 'Paid', kind: 'money' }, { key: 'balance', label: 'Balance', kind: 'money' }, { key: 'dueAt', label: 'Due', kind: 'date' }]}/></section></>}
    {selected && <DetailDrawer eyebrow="Invoice detail" title={`${selected.client || 'Invoice'} ${selected.id}`} onClose={() => setSelectedId(undefined)} loading={detail.loading} error={detail.error}><section className="card"><h3>Balance</h3><DetailFacts rows={[["Status", selected.status], ["Client", selected.client], ["Job", selected.job], ["Total", money(selected.total)], ["Deposit", money(selected.deposit)], ["Paid", money(selected.paid)], ["Balance", money(selected.balance)], ["Due", dateTime(selected.dueAt)]]}/></section><section className="card"><h3>Receivable workflow</h3><WorkflowButtons disabled={!canManage} actions={[{ label: 'Send invoice', onClick: () => workflow(`/api/invoices/${selected.id}/send`, 'Invoice sent.') }, { label: 'Mark paid', onClick: () => workflow(`/api/invoices/${selected.id}/mark-paid`, 'Invoice marked paid.') }, { label: 'Void invoice', variant: 'danger', onClick: async () => { await apiJson(`/api/invoices/${selected.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'void', total: selected.total, deposit: selected.deposit, paid: selected.paid, items: selected.items || [] }) }); setNotice('Invoice voided.'); await collection.reload(); await detail.reload(selected.id); } }]}/></section><section className="card"><h3>Line items and payments</h3>{asArray(selected.items).map((item) => <p key={item.id}>{item.description} · {item.quantity || 1} × {money(item.unitPrice)}</p>)}{!asArray(selected.items).length && <p className="muted">No invoice line items returned.</p>}{asArray(selected.payments).map((payment) => <p key={payment.id}><Badge>{payment.status || 'completed'}</Badge> {payment.method} · {money(payment.amount)}</p>)}</section></DetailDrawer>}
  </ModulePageFrame>;
}

function InvoiceCreateForm({ onSaved }: { onSaved: () => Promise<void> }) {
  const [status, setStatus] = useState('');
  const save = submitForm(async (form) => { const total = dollarsToCents(form.get('total')); const deposit = dollarsToCents(form.get('deposit')); const paid = dollarsToCents(form.get('paid')); setStatus('Creating invoice…'); await apiJson('/api/invoices', { method: 'POST', body: JSON.stringify({ clientId: text(form, 'clientId'), jobId: text(form, 'jobId'), quoteId: text(form, 'quoteId'), status: 'draft', total, deposit, paid, dueAt: text(form, 'dueAt'), items: [{ description: text(form, 'lineDescription') || 'Service work', quantity: Number(form.get('quantity') || 1), unitPrice: dollarsToCents(form.get('unitPrice')) || total }] }) }); setStatus('Invoice created.'); await onSaved(); });
  return <form className="card module-form" onSubmit={save}><div className="section-heading"><div><p className="eyebrow">Invoice form</p><h2>New invoice</h2></div>{status && <Badge>{status}</Badge>}</div><input name="clientId" placeholder="Client ID"/><input name="jobId" placeholder="Job ID"/><input name="quoteId" placeholder="Quote ID"/><input name="total" type="number" step="0.01" required placeholder="Total (dollars)"/><input name="deposit" type="number" step="0.01" placeholder="Deposit applied (dollars)"/><input name="paid" type="number" step="0.01" placeholder="Already paid (dollars)"/><input name="dueAt" type="date"/><input name="lineDescription" placeholder="Primary line description"/><input name="quantity" type="number" step="0.01" placeholder="Qty"/><input name="unitPrice" type="number" step="0.01" placeholder="Unit price (dollars)"/><Button>Create invoice</Button></form>;
}
