import { useMemo, useState } from 'react';
import { Badge, Button } from '../../components/ui';
import { apiJson, asArray, dateTime, DetailDrawer, DetailFacts, dollarsToCents, EmptyWorkflow, ModuleMetrics, ModulePageFrame, ModuleStatus, money, RecordsTable, submitForm, TabbedDetail, text, TimelineList, Toolbar, useCanManage, useModuleRecords, type Row } from './moduleData';

type PaymentRow = Row & { status?: string; client?: string; invoice?: string; invoiceId?: string; job?: string; jobId?: string; method?: string; amount?: number; provider?: string; reference?: string; note?: string; receivedAt?: string };
type ProviderRow = Row & { provider?: string; enabled?: boolean; settings?: Record<string, unknown> };
const statuses = ['completed','pending','failed','refunded'];
const methods = ['cash','check','card external','ACH','other'];

export function PaymentsPage() {
  const [query, setQuery] = useState('');
  const [method, setMethod] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState<string>();
  const [notice, setNotice] = useState('');
  const canManage = useCanManage('payments.manage');
  const collection = useModuleRecords<PaymentRow>('/api/payments', query);
  const providers = useModuleRecords<ProviderRow>('/api/payment-providers', '');
  const records = useMemo(() => collection.records.filter((row) => !method || row.method === method), [collection.records, method]);
  const selected = records.find((record) => record.id === selectedId);
  const total = records.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const refund = async () => { if (!selected) return; await apiJson(`/api/payments/${selected.id}/refund`, { method: 'POST', body: JSON.stringify({ amount: selected.amount, reason: 'Requested from ledger' }) }); setNotice('Refund placeholder recorded for provider follow-up.'); await collection.reload(); };
  return <ModulePageFrame permission="payments.view" title="Payments" eyebrow="Payment ledger" description="Record manual payments, apply them to invoices, watch provider status, and audit linked client/job/invoice receipts." action={<Badge>{money(total)} recorded</Badge>}>
    <ModuleMetrics metrics={[{ label: 'Collected', value: money(total), detail: 'Filtered ledger total' }, { label: 'Manual receipts', value: records.filter((r) => (r.provider || 'manual') === 'manual').length, detail: 'Cash/check/external' }, { label: 'Failed/pending', value: records.filter((r) => ['failed','pending'].includes(r.status || '')).length, detail: 'Needs review' }, { label: 'Refunded', value: records.filter((r) => r.status === 'refunded').length, detail: 'Refund audit' }]}/>
    <section className="provider-grid">{asArray((providers.meta.providers as ProviderRow[]) || providers.records).map((provider) => <article className="card provider-card" key={provider.provider || provider.id}><strong>{provider.provider || provider.id}</strong><Badge tone={provider.enabled ? 'success' : 'warning'}>{provider.enabled ? 'enabled' : 'not configured'}</Badge><p className="muted">Provider status card for reconciliation and default payment routing.</p></article>)}</section>
    <Toolbar query={query} onQuery={setQuery} canManage={canManage} createLabel="Record Payment" onCreate={() => setShowCreate(!showCreate)} secondary={<><select value={method} onChange={(event) => setMethod(event.target.value)} aria-label="Payment method filter"><option value="">All methods</option>{methods.map((item) => <option key={item}>{item}</option>)}</select></>}/>
    {notice && <p className="notice">{notice}</p>}{showCreate && <PaymentCreateForm onSaved={async () => { setShowCreate(false); setNotice('Payment recorded and invoice balance recalculated.'); await collection.reload(); }}/>}<ModuleStatus loading={collection.loading} error={collection.error}/>
    {!collection.loading && !collection.error && (records.length ? <section className="card"><div className="section-heading"><div><p className="eyebrow">Payment ledger</p><h2>Applied receipts</h2></div><Button variant="secondary" onClick={collection.reload}>Refresh</Button></div><RecordsTable records={records} emptyTitle="No payments match these filters" onSelect={(row) => setSelectedId(row.id)} columns={[{ key: 'client', label: 'Client' }, { key: 'invoice', label: 'Invoice' }, { key: 'method', label: 'Method' }, { key: 'status', label: 'Status', kind: 'status' }, { key: 'amount', label: 'Amount', kind: 'money' }, { key: 'receivedAt', label: 'Received', kind: 'date' }]}/></section> : <EmptyWorkflow title="No payments recorded" description="Record a manual payment, select invoice/client, choose cash/check/card external/ACH/other, add amount, reference number, and notes. ContractorOS updates invoice balance/status after applying the payment." action={canManage && <Button onClick={() => setShowCreate(true)}>Record first payment</Button>}/>) }
    {selected && <DetailDrawer eyebrow="Payment detail" title={`${selected.method || 'Payment'} · ${money(selected.amount)}`} onClose={() => setSelectedId(undefined)}><TabbedDetail tabs={[{ id: 'overview', label: 'Overview', content: <section className="card"><h3>Application</h3><DetailFacts rows={[["Status", selected.status], ["Client", selected.client], ["Invoice", selected.invoice || selected.invoiceId], ["Job", selected.job || selected.jobId], ["Amount", money(selected.amount)], ["Method", selected.method], ["Reference/check #", selected.reference], ["Received", dateTime(selected.receivedAt)]]}/></section> }, { id: 'provider', label: 'Provider', content: <section className="card"><h3>Provider and reconciliation</h3><DetailFacts rows={[["Provider", selected.provider || 'manual'], ["Method", selected.method], ["Note", selected.note]]}/><p className="muted">Manual and external-provider receipts stay in one ledger for accounting review.</p></section> }, { id: 'linked', label: 'Linked Invoice / Client / Job', content: <section className="card"><h3>Linked records</h3><DetailFacts rows={[["Invoice", selected.invoice || selected.invoiceId], ["Client", selected.client], ["Job", selected.job || selected.jobId]]}/></section> }, { id: 'refund', label: 'Refund', content: <section className="card"><h3>Refund placeholder</h3><p className="muted">Use this placeholder to record a refund intent until live provider refunds are configured.</p><Button variant="secondary" disabled={!canManage} onClick={refund}>Create refund placeholder</Button></section> }, { id: 'timeline', label: 'Timeline', content: <section className="card"><h3>Payment timeline</h3><TimelineList events={[selected]}/></section> }]}/></DetailDrawer>}
  </ModulePageFrame>;
}
function PaymentCreateForm({ onSaved }: { onSaved: () => Promise<void> }) { const [status, setStatus] = useState(''); const save = submitForm(async (form) => { setStatus('Recording payment…'); await apiJson('/api/payments/manual', { method: 'POST', body: JSON.stringify({ invoiceId: text(form, 'invoiceId'), clientId: text(form, 'clientId'), amount: dollarsToCents(form.get('amount')), method: text(form, 'method') || 'cash', reference: text(form, 'reference'), note: text(form, 'note'), status: 'completed' }) }); setStatus('Payment recorded.'); await onSaved(); }); return <form className="card module-form" onSubmit={save}><div className="section-heading"><div><p className="eyebrow">Manual payment flow</p><h2>Record and apply payment</h2></div>{status && <Badge>{status}</Badge>}</div><input name="invoiceId" placeholder="Invoice ID to apply balance"/><input name="clientId" placeholder="Client ID (optional if invoice selected)"/><select name="method">{methods.map((item) => <option key={item}>{item}</option>)}</select><input name="amount" type="number" step="0.01" required placeholder="Amount"/><input name="reference" placeholder="Reference / check number"/><textarea name="note" placeholder="Internal accounting notes"/><Button>Record real payment</Button></form>; }
