import { useState } from 'react';
import { Badge, Button } from '../../components/ui';
import { apiJson, asArray, dateTime, DetailDrawer, DetailFacts, dollarsToCents, ModulePageFrame, ModuleStatus, money, RecordsTable, submitForm, text, Toolbar, useCanManage, useModuleRecords, useRecordDetail, WorkflowBoard, WorkflowButtons, type Row } from './moduleData';

type QuoteRow = Row & { status?: string; client?: string; request?: string; property?: string; subtotal?: number; tax?: number; total?: number; deposit?: number; createdAt?: string; items?: Row[]; jobs?: Row[]; invoices?: Row[] };
const statuses = ['draft','sent','viewed','approved','declined','expired','converted'];

export function QuotesPage() {
  const [query, setQuery] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState<string>();
  const [notice, setNotice] = useState('');
  const canManage = useCanManage('quotes.manage');
  const collection = useModuleRecords<QuoteRow>('/api/quotes', query);
  const detail = useRecordDetail<QuoteRow>('/api/quotes', selectedId);
  const selected = detail.record || collection.records.find((record) => record.id === selectedId);
  const workflow = async (path: string, message: string) => { await apiJson(path, { method: 'POST', body: JSON.stringify({}) }); setNotice(message); await collection.reload(); if (selectedId) await detail.reload(selectedId); };
  return <ModulePageFrame permission="quotes.view" title="Quotes / Estimates" eyebrow="Standalone estimating" description="Build, send, approve, decline, and convert real estimates without moduleConfigs or realModules." action={<Badge>{money(asArray(collection.records).reduce((sum, row) => sum + Number(row.total || 0), 0))} pipeline value</Badge>}>
    <Toolbar query={query} onQuery={setQuery} canManage={canManage} createLabel="Create Quote" onCreate={() => setShowCreate(!showCreate)} secondary={<select aria-label="Quote status filter" onChange={(event) => setQuery(event.target.value)}><option value="">All quotes</option>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select>}/>
    {notice && <p className="muted">{notice}</p>}
    {showCreate && <QuoteCreateForm onSaved={async () => { setShowCreate(false); await collection.reload(); }}/>}
    <ModuleStatus loading={collection.loading} error={collection.error}/>
    {!collection.loading && !collection.error && <><WorkflowBoard records={collection.records} statuses={statuses} onSelect={(row) => setSelectedId(row.id)} titleFor={(row) => `${row.client || 'Quote'} · ${money(row.total)}`}/><section className="card"><div className="section-heading"><div><p className="eyebrow">Estimate table</p><h2>Quotes and approvals</h2></div><Button variant="secondary" onClick={collection.reload}>Refresh</Button></div><RecordsTable records={collection.records} emptyTitle="No quotes yet" onSelect={(row) => setSelectedId(row.id)} columns={[{ key: 'client', label: 'Client' }, { key: 'request', label: 'Request' }, { key: 'status', label: 'Status', kind: 'status' }, { key: 'subtotal', label: 'Subtotal', kind: 'money' }, { key: 'tax', label: 'Tax', kind: 'money' }, { key: 'total', label: 'Total', kind: 'money' }, { key: 'createdAt', label: 'Created', kind: 'date' }]}/></section></>}
    {selected && <DetailDrawer eyebrow="Estimate detail" title={`${selected.client || 'Quote'} ${selected.id}`} onClose={() => setSelectedId(undefined)} loading={detail.loading} error={detail.error}><section className="card"><h3>Estimate totals</h3><DetailFacts rows={[["Status", selected.status], ["Client", selected.client], ["Request", selected.request], ["Subtotal", money(selected.subtotal)], ["Tax", money(selected.tax)], ["Total", money(selected.total)], ["Created", dateTime(selected.createdAt)]]}/></section><section className="card"><h3>Approval workflow</h3><WorkflowButtons disabled={!canManage} actions={[{ label: 'Send quote', onClick: () => workflow(`/api/quotes/${selected.id}/send`, 'Quote marked sent and workflow event recorded.') }, { label: 'Approve manually', onClick: () => workflow(`/api/quotes/${selected.id}/approve`, 'Quote approved.') }, { label: 'Decline', variant: 'danger', onClick: () => workflow(`/api/quotes/${selected.id}/decline`, 'Quote declined.') }, { label: 'Convert to job', onClick: () => workflow(`/api/quotes/${selected.id}/convert-to-job`, 'Job created from approved quote.') }]}/></section><section className="card"><h3>Line items and linked records</h3>{asArray(selected.items).map((item) => <p key={item.id}>{item.description} · {item.quantity || 1} × {money(item.unitPrice)}</p>)}{!asArray(selected.items).length && <p className="muted">No line items returned for this quote yet.</p>}{asArray(selected.jobs).map((job) => <p key={job.id}><Badge>{job.status}</Badge> Job {job.id}</p>)}{asArray(selected.invoices).map((invoice) => <p key={invoice.id}><Badge>{invoice.status}</Badge> Invoice {invoice.id}</p>)}</section></DetailDrawer>}
  </ModulePageFrame>;
}

function QuoteCreateForm({ onSaved }: { onSaved: () => Promise<void> }) {
  const [status, setStatus] = useState('');
  const save = submitForm(async (form) => { const labor = dollarsToCents(form.get('laborTotal')); const materials = dollarsToCents(form.get('materialTotal')); const fees = dollarsToCents(form.get('serviceFees')); const discount = dollarsToCents(form.get('discount')); const subtotal = Math.max(0, labor + materials + fees - discount); const tax = Math.round(subtotal * (Number(form.get('taxRate') || 0) / 100)); setStatus('Creating quote…'); await apiJson('/api/quotes', { method: 'POST', body: JSON.stringify({ clientId: text(form, 'clientId'), propertyId: text(form, 'propertyId'), requestId: text(form, 'requestId'), status: 'draft', subtotal, tax, total: subtotal + tax, deposit: dollarsToCents(form.get('deposit')), terms: text(form, 'terms'), customerNotes: text(form, 'customerNotes'), items: [{ type: 'labor', description: text(form, 'scope') || 'Labor', quantity: 1, unitPrice: labor }, { type: 'materials', description: 'Materials', quantity: 1, unitPrice: materials }] }) }); setStatus('Quote created.'); await onSaved(); });
  return <form className="card module-form" onSubmit={save}><div className="section-heading"><div><p className="eyebrow">Estimate builder</p><h2>New quote</h2></div>{status && <Badge>{status}</Badge>}</div><input name="clientId" required placeholder="Client ID"/><input name="propertyId" placeholder="Property ID"/><input name="requestId" placeholder="Linked request ID"/><textarea name="scope" placeholder="Scope of work"/><textarea name="terms" placeholder="Terms and approval language"/><textarea name="customerNotes" placeholder="Customer-visible notes"/><input name="laborTotal" type="number" step="0.01" placeholder="Labor total (dollars)"/><input name="materialTotal" type="number" step="0.01" placeholder="Materials total (dollars)"/><input name="serviceFees" type="number" step="0.01" placeholder="Service fees (dollars)"/><input name="discount" type="number" step="0.01" placeholder="Discount (dollars)"/><input name="taxRate" type="number" step="0.01" placeholder="Tax rate %"/><input name="deposit" type="number" step="0.01" placeholder="Deposit required (dollars)"/><Button>Create calculated quote</Button></form>;
}
