import { useMemo, useState } from 'react';
import { Badge, Button } from '../../components/ui';
import { apiJson, asArray, dateTime, DetailDrawer, DetailFacts, dollarsToCents, EmptyWorkflow, ModuleMetrics, ModulePageFrame, ModuleStatus, money, RecordsTable, submitForm, TabbedDetail, text, TimelineList, Toolbar, useCanManage, useModuleRecords, useRecordDetail, WorkflowBoard, WorkflowButtons, type Row } from './moduleData';

type QuoteRow = Row & { status?: string; client?: string; request?: string; requestId?: string; property?: string; propertyId?: string; subtotal?: number; tax?: number; total?: number; deposit?: number; serviceFees?: number; discount?: number; terms?: string; customerNotes?: string; createdAt?: string; sentAt?: string; items?: Row[]; jobs?: Row[]; invoices?: Row[]; timeline?: Row[] };
const statuses = ['draft','ready','sent','viewed','approved','declined','expired','converted','void'];

export function QuotesPage() {
  const [query, setQuery] = useState('');
  const [stage, setStage] = useState('');
  const [view, setView] = useState<'board'|'list'>('board');
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState<string>();
  const [notice, setNotice] = useState('');
  const canManage = useCanManage('quotes.manage');
  const collection = useModuleRecords<QuoteRow>('/api/quotes', query);
  const detail = useRecordDetail<QuoteRow>('/api/quotes', selectedId);
  const records = useMemo(() => collection.records.filter((row) => !stage || row.status === stage), [collection.records, stage]);
  const selected = detail.record || records.find((record) => record.id === selectedId);
  const totalValue = records.reduce((sum, row) => sum + Number(row.total || 0), 0);
  const workflow = async (path: string, message: string) => { try { await apiJson(path, { method: path.match(/\/api\/quotes\/[^/]+$/) ? 'PATCH' : 'POST', body: JSON.stringify(message.includes('ready') ? { status: 'ready' } : message.includes('voided') ? { status: 'void' } : message.includes('reopened') ? { status: 'draft' } : {}) }); setNotice(message); await collection.reload(); if (selectedId) await detail.reload(selectedId); } catch (caught) { setNotice(caught instanceof Error ? caught.message : 'Workflow action failed.'); } };
  const quoteActions = (quote: QuoteRow) => { const status = quote.status || 'draft'; if (status === 'draft') return [{ label: 'Mark Ready', onClick: () => workflow(`/api/quotes/${quote.id}`, 'Quote marked ready.') }, { label: 'Send Quote', onClick: () => workflow(`/api/quotes/${quote.id}/send`, 'Quote marked sent and workflow event recorded.') }, { label: 'Approve Internally', onClick: () => workflow(`/api/quotes/${quote.id}/approve`, 'Quote approved.') }, { label: 'Decline', onClick: () => workflow(`/api/quotes/${quote.id}/decline`, 'Quote declined.') }]; if (status === 'ready') return [{ label: 'Send Quote', onClick: () => workflow(`/api/quotes/${quote.id}/send`, 'Quote marked sent and workflow event recorded.') }, { label: 'Approve', onClick: () => workflow(`/api/quotes/${quote.id}/approve`, 'Quote approved.') }, { label: 'Decline', onClick: () => workflow(`/api/quotes/${quote.id}/decline`, 'Quote declined.') }]; if (['sent','viewed'].includes(status)) return [{ label: 'Approve', onClick: () => workflow(`/api/quotes/${quote.id}/approve`, 'Quote approved.') }, { label: 'Decline', onClick: () => workflow(`/api/quotes/${quote.id}/decline`, 'Quote declined.') }]; if (status === 'approved') return [{ label: 'Convert to Job', onClick: () => workflow(`/api/quotes/${quote.id}/convert-to-job`, 'Job created from quote.') }, { label: 'Void', onClick: () => workflow(`/api/quotes/${quote.id}`, 'Quote voided.') }]; if (status === 'declined') return [{ label: 'Reopen Draft', onClick: () => workflow(`/api/quotes/${quote.id}`, 'Quote reopened as draft.') }]; return []; };

  return <ModulePageFrame permission="quotes.view" title="Quotes / Estimates" eyebrow="Estimate builder" description="Build itemized estimates with labor, materials, service fees, terms, deposits, approval workflow, and downstream job/invoice conversion." action={<Badge>{money(totalValue)} pipeline value</Badge>}>
    <ModuleMetrics metrics={[{ label: 'Drafts', value: records.filter((r) => r.status === 'draft').length, detail: 'Need build/send' }, { label: 'Sent', value: records.filter((r) => r.status === 'sent').length, detail: 'Awaiting customer' }, { label: 'Approved', value: records.filter((r) => r.status === 'approved').length, detail: 'Ready for work order' }, { label: 'Avg quote', value: money(records.length ? totalValue / records.length : 0), detail: 'From live totals' }]}/>
    <Toolbar query={query} onQuery={setQuery} canManage={canManage} createLabel="Create Quote" onCreate={() => setShowCreate(!showCreate)} secondary={<><select value={stage} onChange={(event) => setStage(event.target.value)} aria-label="Quote pipeline filter"><option value="">All stages</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><div className="segmented"><button type="button" className={view === 'board' ? 'active' : ''} onClick={() => setView('board')}>Pipeline</button><button type="button" className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}>List</button></div></>}/>
    {notice && <p className="notice">{notice}</p>}
    {showCreate && <QuoteCreateForm onSaved={async () => { setShowCreate(false); await collection.reload(); }}/>}<ModuleStatus loading={collection.loading} error={collection.error}/>
    {!collection.loading && !collection.error && (records.length ? <>{view === 'board' && <WorkflowBoard records={records} statuses={statuses} onSelect={(row) => setSelectedId(row.id)} titleFor={(row) => `${row.client || 'Quote'} · ${money(row.total)}`}/>}<section className="card"><div className="section-heading"><div><p className="eyebrow">Estimate table</p><h2>Quotes and approvals</h2></div><Button variant="secondary" onClick={collection.reload}>Refresh</Button></div><RecordsTable records={records} emptyTitle="No quotes match these filters" onSelect={(row) => setSelectedId(row.id)} columns={[{ key: 'client', label: 'Client' }, { key: 'request', label: 'Request' }, { key: 'status', label: 'Status', kind: 'status' }, { key: 'subtotal', label: 'Subtotal', kind: 'money' }, { key: 'tax', label: 'Tax', kind: 'money' }, { key: 'total', label: 'Total', kind: 'money' }, { key: 'createdAt', label: 'Created', kind: 'date' }]}/></section></> : <EmptyWorkflow title="No estimates yet" description="Create a quote from scratch or convert a work request. Add labor, materials, fees, discounts, taxes, deposit, terms, and customer notes before sending for approval." action={canManage && <Button onClick={() => setShowCreate(true)}>Build first quote</Button>}/>) }
    {selected && <DetailDrawer eyebrow="Quote detail" title={`${selected.client || 'Quote'} · ${money(selected.total)}`} onClose={() => setSelectedId(undefined)} loading={detail.loading} error={detail.error}><TabbedDetail tabs={[{ id: 'overview', label: 'Overview', content: <><section className="card"><h3>Estimate totals</h3><DetailFacts rows={[["Status", selected.status], ["Client", selected.client], ["Request", selected.request || selected.requestId], ["Subtotal", money(selected.subtotal)], ["Tax", money(selected.tax)], ["Deposit", money(selected.deposit)], ["Total", money(selected.total)], ["Created", dateTime(selected.createdAt)]]}/></section><section className="card"><h3>Approval workflow</h3><WorkflowButtons disabled={!canManage} actions={quoteActions(selected)}/></section></> }, { id: 'line-items', label: 'Line Items', content: <><QuoteLineItemForm id={selected.id} onSaved={() => detail.reload(selected.id)}/><LineItemList items={asArray(selected.items)} type="all"/></> }, { id: 'labor', label: 'Labor', content: <LineItemList items={asArray(selected.items)} type="labor"/> }, { id: 'materials', label: 'Materials', content: <LineItemList items={asArray(selected.items)} type="material"/> }, { id: 'terms', label: 'Terms', content: <section className="card"><h3>Terms and deposit</h3><p>{selected.terms || 'No terms returned yet. Add terms in the builder so the customer sees scope limits, warranty, expiry, and deposit requirements.'}</p><DetailFacts rows={[["Required deposit", money(selected.deposit)], ["Expires", dateTime(selected.expiresAt)]]}/></section> }, { id: 'notes', label: 'Customer Notes', content: <section className="card"><h3>Customer-facing estimate note</h3><p>{selected.customerNotes || 'No customer note captured yet.'}</p></section> }, { id: 'timeline', label: 'Timeline', content: <section className="card"><h3>Estimate timeline</h3><TimelineList events={asArray(selected.timeline)}/></section> }, { id: 'linked', label: 'Linked Job / Invoice', content: <section className="card"><h3>Linked records</h3>{asArray(selected.jobs).map((job) => <p key={job.id}><Badge>{job.status}</Badge> Job {job.id}</p>)}{asArray(selected.invoices).map((invoice) => <p key={invoice.id}><Badge>{invoice.status}</Badge> Invoice {invoice.id}</p>)}{!asArray(selected.jobs).length && !asArray(selected.invoices).length && <p className="muted">Approve and convert the estimate to create downstream job and invoice records.</p>}</section> }, { id: 'preview', label: 'Quote Preview', content: <section className="card quote-preview"><p className="eyebrow">Customer preview</p><h2>{selected.client || 'Customer estimate'}</h2><p>{selected.customerNotes || 'Thank you for the opportunity. Please review the itemized estimate below.'}</p><LineItemList items={asArray(selected.items)} type="all"/><strong>Total due: {money(selected.total)}</strong></section> }]}/></DetailDrawer>}
  </ModulePageFrame>;
}

function LineItemList({ items, type }: { items: Row[]; type: string }) {
  const filtered = type === 'all' ? items : items.filter((item) => String(item.type || '').includes(type));
  return <section className="card"><h3>{type === 'all' ? 'Editable estimate items' : type}</h3>{filtered.map((item) => <p key={item.id}>{item.description} · {item.quantity || 1} × {money(item.unitPrice)} = {money(item.total || Number(item.quantity || 1) * Number(item.unitPrice || 0))}</p>)}{!filtered.length && <p className="muted">No {type} items returned yet.</p>}</section>;
}

function QuoteLineItemForm({ id, onSaved }: { id: string; onSaved: () => void }) {
  const save = submitForm(async (form) => { await apiJson(`/api/quotes/${id}/line-items`, { method: 'POST', body: JSON.stringify({ type: text(form, 'type'), description: text(form, 'description'), quantity: Number(form.get('quantity') || 1), unitPrice: dollarsToCents(form.get('unitPrice')) }) }); onSaved(); });
  return <form className="card module-form compact" onSubmit={save}><h3>Add estimate line</h3><select name="type"><option value="labor">Labor</option><option value="material">Material</option><option value="fee">Service fee</option><option value="discount">Discount</option></select><input name="description" required placeholder="Description"/><input name="quantity" type="number" step="0.01" defaultValue="1"/><input name="unitPrice" type="number" step="0.01" placeholder="Unit price"/><Button>Add line item</Button></form>;
}

function QuoteCreateForm({ onSaved }: { onSaved: () => Promise<void> }) {
  const [status, setStatus] = useState('');
  const save = submitForm(async (form) => { const labor = dollarsToCents(form.get('laborTotal')); const materials = dollarsToCents(form.get('materialTotal')); const fees = dollarsToCents(form.get('serviceFees')); const discount = dollarsToCents(form.get('discount')); const subtotal = Math.max(0, labor + materials + fees - discount); const tax = Math.round(subtotal * (Number(form.get('taxRate') || 0) / 100)); setStatus('Creating quote…'); await apiJson('/api/quotes', { method: 'POST', body: JSON.stringify({ clientId: text(form, 'clientId'), propertyId: text(form, 'propertyId'), requestId: text(form, 'requestId'), status: 'draft', subtotal, tax, total: subtotal + tax, deposit: dollarsToCents(form.get('deposit')), terms: text(form, 'terms'), customerNotes: text(form, 'customerNotes'), items: [{ type: 'labor', description: text(form, 'laborDescription') || 'Labor', quantity: 1, unitPrice: labor }, { type: 'material', description: text(form, 'materialDescription') || 'Materials', quantity: 1, unitPrice: materials }, { type: 'fee', description: 'Service fees', quantity: 1, unitPrice: fees }, { type: 'discount', description: 'Discount', quantity: 1, unitPrice: -discount }] }) }); setStatus('Quote created.'); await onSaved(); });
  return <form className="card module-form" onSubmit={save}><div className="section-heading"><div><p className="eyebrow">Quote builder</p><h2>New itemized estimate</h2></div>{status && <Badge>{status}</Badge>}</div><input name="clientId" placeholder="Client ID"/><input name="propertyId" placeholder="Property ID"/><input name="requestId" placeholder="Linked request ID"/><input name="laborDescription" placeholder="Labor scope"/><input name="laborTotal" type="number" step="0.01" placeholder="Labor total"/><input name="materialDescription" placeholder="Materials summary"/><input name="materialTotal" type="number" step="0.01" placeholder="Materials total"/><input name="serviceFees" type="number" step="0.01" placeholder="Service fees"/><input name="discount" type="number" step="0.01" placeholder="Discount"/><input name="taxRate" type="number" step="0.01" placeholder="Tax rate %"/><input name="deposit" type="number" step="0.01" placeholder="Deposit required"/><textarea name="terms" placeholder="Terms, exclusions, warranty, expiration"/><textarea name="customerNotes" placeholder="Customer-visible note"/><Button>Create quote draft</Button></form>;
}
