import { useState } from 'react';
import { Badge, Button } from '../../components/ui';
import { apiJson, asArray, dateTime, DetailDrawer, DetailFacts, ModulePageFrame, ModuleStatus, RecordsTable, submitForm, text, Toolbar, useCanManage, useModuleRecords, useRecordDetail, WorkflowBoard, WorkflowButtons, type Row } from './moduleData';

type RequestRow = Row & { title?: string; status?: string; priority?: string; description?: string; client?: string; property?: string; service?: string; createdAt?: string; internalNotes?: string; quotes?: Row[]; attachments?: Row[] };
const statuses = ['new','reviewing','needs_info','quoted','approved','scheduled','in_progress','completed','closed','cancelled'];

export function RequestsPage() {
  const [query, setQuery] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState<string>();
  const [notice, setNotice] = useState('');
  const canManage = useCanManage('requests.manage');
  const collection = useModuleRecords<RequestRow>('/api/requests', query);
  const detail = useRecordDetail<RequestRow>('/api/requests', selectedId);
  const selected = detail.record || collection.records.find((record) => record.id === selectedId);
  const act = async (path: string, message: string, payload: Record<string, unknown> = {}) => { await apiJson(path, { method: 'POST', body: JSON.stringify(payload) }); setNotice(message); await collection.reload(); if (selectedId) await detail.reload(selectedId); };
  return <ModulePageFrame permission="requests.view" title="Work Requests" eyebrow="Standalone intake" description="Triage customer work requests with real intake, assignment, conversion, notes, linked quotes, and request-specific workflow actions." action={<Badge>{collection.records.length} live requests</Badge>}>
    <Toolbar query={query} onQuery={setQuery} canManage={canManage} createLabel="Create Work Request" onCreate={() => setShowCreate(!showCreate)} secondary={<select aria-label="Request status filter" onChange={(event) => setQuery(event.target.value)}><option value="">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select>}/>
    {notice && <p className="muted">{notice}</p>}
    {showCreate && <RequestCreateForm onSaved={async () => { setShowCreate(false); await collection.reload(); }}/>}
    <ModuleStatus loading={collection.loading} error={collection.error}/>
    {!collection.loading && !collection.error && <><WorkflowBoard records={collection.records} statuses={statuses} onSelect={(row) => setSelectedId(row.id)} titleFor={(row) => row.title || row.client || row.id}/><section className="card"><div className="section-heading"><div><p className="eyebrow">Request queue</p><h2>Intake list</h2></div><Button variant="secondary" onClick={collection.reload}>Refresh</Button></div><RecordsTable records={collection.records} emptyTitle="No work requests yet" onSelect={(row) => setSelectedId(row.id)} columns={[{ key: 'title', label: 'Request' }, { key: 'client', label: 'Client' }, { key: 'property', label: 'Property' }, { key: 'service', label: 'Service' }, { key: 'priority', label: 'Priority', kind: 'badge' }, { key: 'status', label: 'Status', kind: 'status' }, { key: 'createdAt', label: 'Created', kind: 'date' }]}/></section></>}
    {selected && <DetailDrawer eyebrow="Request detail" title={selected.title || selected.client || selected.id} onClose={() => setSelectedId(undefined)} loading={detail.loading} error={detail.error}><section className="card"><h3>Customer issue</h3><DetailFacts rows={[["Status", selected.status], ["Priority", selected.priority], ["Client", selected.client], ["Property", selected.property], ["Service", selected.service], ["Created", dateTime(selected.createdAt)]]}/><p>{selected.description || 'No customer description captured yet.'}</p></section><section className="card"><h3>Workflow actions</h3><WorkflowButtons disabled={!canManage} actions={[{ label: 'Convert to quote', onClick: () => act(`/api/requests/${selected.id}/convert-to-quote`, 'Quote draft created from request.') }, { label: 'Mark reviewing', onClick: async () => { await apiJson(`/api/requests/${selected.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'reviewing', title: selected.title, priority: selected.priority, description: selected.description, internalNotes: selected.internalNotes }) }); setNotice('Request moved to reviewing.'); await collection.reload(); await detail.reload(selected.id); } }, { label: 'Close request', variant: 'danger', onClick: async () => { await apiJson(`/api/requests/${selected.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'closed', title: selected.title, priority: selected.priority, description: selected.description, internalNotes: selected.internalNotes }) }); setNotice('Request closed.'); await collection.reload(); await detail.reload(selected.id); } }]}/></section><section className="card"><h3>Linked quotes and files</h3>{asArray(selected.quotes).map((quote) => <p key={quote.id}><Badge>{quote.status || 'draft'}</Badge> Quote {quote.id}</p>)}{!asArray(selected.quotes).length && <p className="muted">No linked quotes yet.</p>}{asArray(selected.attachments).map((file) => <p key={file.id}>{file.name}</p>)}</section></DetailDrawer>}
  </ModulePageFrame>;
}

function RequestCreateForm({ onSaved }: { onSaved: () => Promise<void> }) {
  const [status, setStatus] = useState('');
  const save = submitForm(async (form) => { setStatus('Creating request…'); await apiJson('/api/requests', { method: 'POST', body: JSON.stringify({ clientId: text(form, 'clientId'), propertyId: text(form, 'propertyId'), serviceCategory: text(form, 'serviceCategory'), requestType: text(form, 'requestType'), priority: text(form, 'priority') || 'normal', title: text(form, 'title'), description: text(form, 'description'), accessNotes: text(form, 'accessNotes'), internalNotes: text(form, 'internalNotes') }) }); setStatus('Request created.'); await onSaved(); });
  return <form className="card module-form" onSubmit={save}><div className="section-heading"><div><p className="eyebrow">Create intake</p><h2>New work request</h2></div>{status && <Badge>{status}</Badge>}</div><input name="clientId" required placeholder="Client ID or new client name"/><input name="propertyId" placeholder="Property ID or new property address"/><select name="serviceCategory"><option>HVAC</option><option>Plumbing</option><option>Electrical</option><option>Handyman</option><option>Maintenance</option></select><select name="requestType"><option>repair</option><option>replacement</option><option>maintenance</option><option>quote only</option></select><select name="priority"><option>normal</option><option>high</option><option>urgent</option><option>emergency</option></select><input name="title" required placeholder="Request title"/><textarea name="description" placeholder="Customer description"/><textarea name="accessNotes" placeholder="Access notes"/><textarea name="internalNotes" placeholder="Internal triage notes"/><Button>Create real request</Button></form>;
}
