-- Compatibility placeholder for databases that applied the former
-- 0004_custom_roles_permissions migration name before the role/permission
-- changes were renumbered to 0005_custom_roles_permissions.sql.
--
-- Do not remove this file. Netlify Database validates that every applied
-- migration name is still present in later deploys. The real, idempotent
-- schema changes live in 0005_custom_roles_permissions.sql for fresh databases.
