-- Compatibility placeholder for databases that applied the former
-- 0012_quote_payment_completion_controls migration name before invoice/payment
-- status controls were consolidated into 0010_invoices_payments.sql.
--
-- Do not remove this file. Netlify Database validates that every applied
-- migration name is still present in later deploys. The real, idempotent
-- invoice/payment schema changes live in 0010_invoices_payments.sql for fresh databases.
