-- Company/admin settings storage.
-- 0036 is the first migration that references company_settings, so keep it
-- self-contained for fresh Netlify databases where every migration is pending.
create extension if not exists pgcrypto;

create table if not exists company_settings (
  id uuid primary key default gen_random_uuid(),
  company_name text,
  legal_name text,
  display_name text,
  website_url text,
  support_email text,
  support_phone text,
  business_phone text,
  business_address text,
  city text,
  state text,
  zip text,
  service_area text,
  timezone text default 'America/Phoenix',
  currency text default 'USD',
  license_number text,
  contractor_license_number text,
  tax_id text,
  business_type text,
  logo_url text,
  favicon_url text,
  primary_color text,
  accent_color text,
  background_color text,
  surface_color text,
  text_color text,
  button_color text,
  success_color text,
  warning_color text,
  danger_color text,
  theme_mode text default 'system',
  default_theme text default 'system',
  enable_theme_toggle boolean default true,
  show_company_name_in_header boolean default false,
  installation_complete boolean default false,
  homepage_content jsonb default '{}'::jsonb,
  homepage_gallery jsonb default '[]'::jsonb,
  admin_settings jsonb default '{}'::jsonb,
  quote_settings jsonb default '{}'::jsonb,
  ai_settings jsonb default '{}'::jsonb,
  cmms_settings jsonb default '{}'::jsonb,
  notification_settings jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table if exists company_settings
  add column if not exists company_name text,
  add column if not exists legal_name text,
  add column if not exists display_name text,
  add column if not exists website_url text,
  add column if not exists support_email text,
  add column if not exists support_phone text,
  add column if not exists business_phone text,
  add column if not exists business_address text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists zip text,
  add column if not exists service_area text,
  add column if not exists timezone text default 'America/Phoenix',
  add column if not exists currency text default 'USD',
  add column if not exists license_number text,
  add column if not exists contractor_license_number text,
  add column if not exists tax_id text,
  add column if not exists business_type text,
  add column if not exists logo_url text,
  add column if not exists favicon_url text,
  add column if not exists primary_color text,
  add column if not exists accent_color text,
  add column if not exists background_color text,
  add column if not exists surface_color text,
  add column if not exists text_color text,
  add column if not exists button_color text,
  add column if not exists success_color text,
  add column if not exists warning_color text,
  add column if not exists danger_color text,
  add column if not exists theme_mode text default 'system',
  add column if not exists default_theme text default 'system',
  add column if not exists enable_theme_toggle boolean default true,
  add column if not exists show_company_name_in_header boolean default false,
  add column if not exists installation_complete boolean default false,
  add column if not exists homepage_content jsonb default '{}'::jsonb,
  add column if not exists homepage_gallery jsonb default '[]'::jsonb,
  add column if not exists admin_settings jsonb not null default '{}'::jsonb,
  add column if not exists quote_settings jsonb default '{}'::jsonb,
  add column if not exists ai_settings jsonb default '{}'::jsonb,
  add column if not exists cmms_settings jsonb default '{}'::jsonb,
  add column if not exists notification_settings jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();
