window.TAModules = window.TAModules || { modules:new Map(), register(m){this.modules.set(m.id,m)} };
const app=document.getElementById('app'); let bootstrap, active, workspace='owner';
async function loadBootstrap(){ const res=await fetch('/api/dashboard-bootstrap',{cache:'no-store'}); if(res.status===423){location.replace('/install/'); return null;} return res.json(); }
function applyTheme(t={}){ for (const [k,v] of Object.entries({primary:t.primary,accent:t.accent,background:t.background,surface:t.surface,text:t.text})) if(v) document.documentElement.style.setProperty(`--${k}`,v); }
async function loadModule(mod){ active=mod.id; const root=document.getElementById('module-root'); root.innerHTML='<p class="muted">Loading module…</p>'; if(!window.TAModules.modules.has(mod.id)){ await new Promise((resolve,reject)=>{ const s=document.createElement('script'); s.type='module'; s.src=`${mod.frontend.basePath}/${mod.frontend.entry}`; s.onload=resolve; s.onerror=reject; document.head.appendChild(s); }); }
 const module=window.TAModules.modules.get(mod.id); await module.mount({root,api:{},auth:{},user:bootstrap.user,company:bootstrap.company,permissions:bootstrap.permissions,workspace,module:mod,router:{go:loadModule},workflow:{transition},eventBus:new EventTarget(),ui:{},config:bootstrap,signal:null}); renderNav(); }
async function transition(event){ return fetch('/api/workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(event)}).then(r=>r.json()); }
function renderNav(){ document.querySelectorAll('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module===active)); }
function render(){ const c=bootstrap.company||{}, mods=bootstrap.modules||[]; app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand"><div class="logo">${(c.displayName||'C')[0]}</div><span>${c.displayName||'Platform Dashboard'}</span></div><div><select id="workspace">${bootstrap.user.workspaces.map(w=>`<option ${w===workspace?'selected':''}>${w}</option>`).join('')}</select> <button class="secondary" id="impersonate">Impersonation</button></div></header><div id="banner"></div><main class="layout"><aside class="sidebar"><h3>Modules</h3>${mods.map(m=>`<button data-module="${m.id}">${m.icon} ${m.nav?.label||m.title}</button>`).join('')}<hr><button data-action="workflow">Simulate Workflow</button></aside><section class="content"><div id="module-root" class="card"></div></section></main><nav class="mobile-nav">${mods.map(m=>`<button data-module="${m.id}">${m.icon} ${m.nav?.mobileLabel||m.title}</button>`).join('')}</nav></div>`; document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>loadModule(mods.find(m=>m.id===b.dataset.module))); document.getElementById('workspace').onchange=e=>{workspace=e.target.value; document.getElementById('banner').innerHTML=workspace.includes('public')?`<div class="banner">Owner previewing ${workspace}. Owner bypass remains active for testing.</div>`:'';}; document.getElementById('impersonate').onclick=()=>{document.getElementById('banner').innerHTML='<div class="banner">Viewing as Sample Client (Client) <button class="ghost" onclick="this.closest(\'.banner\').remove()">Exit Impersonation</button></div>'}; document.querySelector('[data-action="workflow"]').onclick=async()=>{ const events=['request.created','quote.drafted','quote.sent','quote.accepted','quote.converted','workorder.created','workorder.assigned','workorder.scheduled','workorder.completed','admin.reviewed','invoice.sent','payment.received','payment.verified','archive']; const results=[]; for(const ev of events) results.push((await transition({entityType:'simulation',entityId:'owner-test',event:ev})).data.status); document.getElementById('module-root').innerHTML=`<h2>Workflow Simulation</h2><p>${results.join(' → ')}</p><p class="muted">Terminal statuses leave active queues.</p>`;}; if(mods[0]) loadModule(mods[0]); }
(async()=>{ bootstrap=await loadBootstrap(); if(!bootstrap?.ok) return; applyTheme(bootstrap.theme); render(); })();
