const $=s=>document.querySelector(s); const state={registry:null,install:null,workflow:null,home:null};
const defaultHome={companyName:'Your Contractor Company',tagline:'AI-powered estimates, work orders, scheduling, invoices, and client approvals in one polished contractor operating system.',cta:'Request an Estimate',heroVisible:true,services:['Repairs','Renovations','Maintenance'],projects:[],gallery:[],contact:'Use the estimate form and our team will follow up quickly.',footer:'Built for modern contractor operations.'};
async function safeJson(url, fallback){try{const r=await fetch(url); if(!r.ok) throw new Error(r.status); return await r.json()}catch{return fallback}}
async function boot(){state.registry=await safeJson('/generated/module-registry.json',{modules:[],sidebar:[],permissions:{},managerList:[]});state.install=await safeJson('/api/install-status',{installed:false});state.home=JSON.parse(localStorage.getItem('homepageConfig')||'null')||defaultHome;route();addEventListener('popstate',route)}
function nav(path){history.pushState(null,'',path);route()} window.nav=nav;
function shell(content){return `<div class="public-shell"><header class="topbar"><a class="brand" onclick="nav('/')"><span class="logo">AI</span><span>${escapeHtml(state.home.companyName)}</span></a><nav class="nav"><a onclick="nav('/request')">Estimate</a><a onclick="nav('/portal')">Client Portal</a><a onclick="nav('/dashboard')">Dashboard</a><a onclick="nav('/install')">Install</a></nav><button class="btn" onclick="nav('/request')">${escapeHtml(state.home.cta)}</button></header>${content}</div>`}
function route(){const p=location.pathname;if(p.startsWith('/install')) return renderInstall(); if(p.startsWith('/dashboard')) return renderDashboard(p); if(p.startsWith('/portal')) return renderPortal(); if(p.startsWith('/quote/')) return renderPublicDoc('Quote',p.split('/').pop()); if(p.startsWith('/invoice/')) return renderPublicDoc('Invoice',p.split('/').pop()); if(p.startsWith('/request')) return renderRequest(); return renderHome()}
function renderHome(){const h=state.home; $('#app').innerHTML=shell(`<main>${h.heroVisible?`<section class="hero"><div><span class="badge">White-label AI Contractor CMMS</span><h1>${escapeHtml(h.companyName)} runs jobs from first photo to final payment.</h1><p>${escapeHtml(h.tagline)}</p><button class="btn" onclick="nav('/request')">${escapeHtml(h.cta)}</button> <button class="btn secondary" onclick="nav('/portal')">Client Portal</button></div><div class="panel"><h2>AI Estimate Preview</h2><div class="dropzone">Upload real project photos to generate a scoped estimate.</div><p class="muted">Secure Netlify Functions keep AI, email, Square, and license secrets server-side.</p></div></section>`:''}<section class="grid">${h.services.map(s=>`<article class="card"><h3>${escapeHtml(s)}</h3><p class="muted">Configurable in Homepage Editor with visibility and ordering controls.</p></article>`).join('')}</section><section class="section"><div class="panel"><h2>Contact</h2><p>${escapeHtml(h.contact)}</p></div></section><footer class="section muted">${escapeHtml(h.footer)}</footer></main>`)}
function renderRequest(){ $('#app').innerHTML=shell(`<main class="section"><div class="panel"><h1>Request an AI Estimate</h1><p class="muted">Upload photos from your device; the browser sends them only to secure functions.</p><form onsubmit="submitEstimate(event)" class="form-grid"><label>Name<input required name="name"></label><label>Email<input required type="email" name="email"></label><label>Service<select name="service">${state.home.services.map(s=>`<option>${escapeHtml(s)}</option>`).join('')}</select></label><label>Photos<input type="file" name="photos" accept="image/*" multiple></label><label style="grid-column:1/-1">Project Notes<textarea name="notes"></textarea></label><button class="btn">Generate Estimate Request</button></form><pre id="estimateResult"></pre></div></main>`)}
window.submitEstimate=async e=>{e.preventDefault(); const fd=new FormData(e.target); const r=await fetch('/api/ai',{method:'POST',body:fd}); $('#estimateResult').textContent=JSON.stringify(await r.json(),null,2)};
function renderPortal(){ $('#app').innerHTML=shell(`<main class="section"><div class="panel"><h1>Client Portal</h1><p class="muted">Magic-link access to quotes, work orders, approvals, invoices, and payment links.</p><form onsubmit="sendMagic(event)" class="form-grid"><label>Email<input required type="email" name="email"></label><button class="btn">Send Magic Link</button></form><div id="magic"></div></div></main>`)}
window.sendMagic=async e=>{e.preventDefault(); const r=await fetch('/api/auth-magic-link',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target))),headers:{'content-type':'application/json'}}); $('#magic').innerHTML=`<p class="badge">${(await r.json()).message}</p>`};
function renderDashboard(path){const active=path.split('/').pop()==='dashboard'?'owner-dashboard':path.split('/').pop();const mod=state.registry.modules.find(m=>m.id===active)||state.registry.modules.find(m=>m.id==='owner-dashboard')||state.registry.modules[0];$('#app').innerHTML=`<div class="dashboard"><aside class="sidebar"><div class="brand"><span class="logo">AI</span><span>CMMS</span></div><hr>${state.registry.sidebar.map(n=>`<a class="side-link ${n.moduleId===mod?.id?'active':''}" onclick="nav('${n.path}')"><span>${n.icon}</span>${n.label}</a>`).join('')}</aside><main class="main"><div class="toolbar"><div><h1>${escapeHtml(mod?.title||'Dashboard')}</h1><p class="muted">Manifest-driven workspace. No core router edits are required for module folders.</p></div><button class="btn secondary" onclick="toggleTheme()">Theme</button></div>${dashboardContent(mod)}</main></div>`}
function dashboardContent(mod){if(!mod)return '<div class="panel">No modules registered.</div>'; if(mod.id==='installer') return installerPanel(); if(mod.id==='module-manager') return moduleManager(); if(mod.id==='homepage-editor') return homepageEditor(); if(mod.id==='theme-manager') return themeManager(); if(mod.id==='workflow-engine'||mod.id==='work-orders') return workflowBoard(); if(mod.id.includes('ai')) return aiPanel(mod); if(mod.id==='invoices'||mod.id==='square-integration'||mod.id==='public-invoice-viewer') return invoicePanel(); return `<div class="stats"><div class="card stat"><span>Active</span><strong>12</strong></div><div class="card stat"><span>Awaiting Review</span><strong>4</strong></div><div class="card stat"><span>Scheduled</span><strong>9</strong></div><div class="card stat"><span>Closed</span><strong>31</strong></div></div><section class="panel" style="margin-top:18px"><h2>${escapeHtml(mod.title)}</h2><p>${escapeHtml(mod.description)}</p><span class="badge">${escapeHtml(mod.workspace)} · ${escapeHtml(mod.category)}</span></section>`}
function installerPanel(){return `<div class="panel"><h2>Installer Summary</h2><p>18-step first-run installer with license placeholder, environment checks, database checks, owner account, homepage, modules, permissions, Square, AI, and final review.</p><button class="btn" onclick="nav('/install')">Open Installer</button></div>`}
function moduleManager(){return `<div class="panel"><h2>Module Manager</h2><table><tr><th>Module</th><th>Workspace</th><th>Permissions</th><th>Status</th></tr>${state.registry.managerList.map(m=>`<tr><td>${m.icon} ${escapeHtml(m.title)}<br><span class="muted">${escapeHtml(m.description)}</span></td><td>${m.workspace}</td><td>${(state.registry.permissions[m.id]||[]).length}</td><td><span class="badge">${m.enabledByDefault?'Enabled':'Disabled'}</span></td></tr>`).join('')}</table></div>`}
function homepageEditor(){return `<div class="panel"><h2>Homepage Editor</h2><form onsubmit="saveHome(event)" class="form-grid"><label>Company<input name="companyName" value="${escapeAttr(state.home.companyName)}"></label><label>CTA<input name="cta" value="${escapeAttr(state.home.cta)}"></label><label style="grid-column:1/-1">Tagline<textarea name="tagline">${escapeHtml(state.home.tagline)}</textarea></label><label>Services CSV<input name="services" value="${escapeAttr(state.home.services.join(', '))}"></label><label>Contact<input name="contact" value="${escapeAttr(state.home.contact)}"></label><button class="btn">Save Homepage</button></form></div>`}
window.saveHome=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.home={...state.home,...d,services:d.services.split(',').map(s=>s.trim()).filter(Boolean)};localStorage.setItem('homepageConfig',JSON.stringify(state.home));renderDashboard('/dashboard/homepage-editor')};
function themeManager(){return `<div class="panel"><h2>Theme Manager</h2><p>Theme is applied before first paint and all UI uses CSS variables.</p><button class="btn" onclick="setTheme('light')">Light</button> <button class="btn" onclick="setTheme('dark')">Dark</button> <button class="btn" onclick="setTheme('system')">System</button></div>`}
window.setTheme=t=>{localStorage.setItem('theme',t);document.documentElement.dataset.theme=t==='system'&&(matchMedia('(prefers-color-scheme: dark)').matches)?'dark':t==='system'?'light':t}; window.toggleTheme=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function workflowBoard(){const steps=['Request','AI Quote','Admin Review','Client Accepts','Work Order','Assign Worker','Schedule','In Progress','Worker Completed','Admin Review','Client Approval','Invoice','Payment','Payment Verified','Archive'];return `<div class="panel"><h2>Workflow Engine</h2><p class="muted">Single source of truth: ${steps.join(' → ')}</p><div class="kanban">${['Active Quotes','Work Orders','Worker Queue','Finance'].map((c,i)=>`<div class="card"><h3>${c}</h3><p>${12-i*3} synchronized items</p><button class="btn secondary">Advance</button></div>`).join('')}</div></div>`}
function aiPanel(mod){return `<div class="panel"><h2>${escapeHtml(mod.title)}</h2><p>Shared AI Intelligence Engine uses secure server-side OpenAI configuration.</p><button class="btn" onclick="fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'${mod.id}',prompt:'diagnose'})}).then(r=>r.json()).then(j=>alert(JSON.stringify(j)))">Run AI</button></div>`}
function invoicePanel(){return `<div class="panel"><h2>Invoices & Square Payments</h2><p>Invoices can be viewed, downloaded, paid through secure Square links, verified by admins, and closed through workflow transitions.</p><button class="btn">Create Payment Link</button></div>`}
function renderInstall(){const steps=['Welcome','License Key','Environment Check','Database Check','Company Information','Logo Upload','Branding','Theme','Sidebar Colors','Owner Account','Email Verification','Homepage Setup','Module Selection','Permissions','Square Setup','AI Setup','Final Review','Installation Complete'];$('#app').innerHTML=`<div class="wizard"><div class="brand"><span class="logo">AI</span><span>First-Run Installer</span></div><div class="steps">${steps.map((s,i)=>`<span class="step ${i===0?'active':''}">${i+1}. ${s}</span>`).join('')}</div><div class="panel"><h1>Welcome</h1><p class="muted">Configure company profile, license placeholder, database, branding, owner account, homepage, modules, permissions, Square, AI, and final review. Drafts save safely in the browser and finish through /api/install.</p><div class="grid" style="padding:0">${['Database connected','Functions reachable','Migrations valid','OpenAI configured','Resend configured','Square optional','License validation disabled by default'].map(x=>`<div class="card"><span class="badge">Check</span><h3>${x}</h3></div>`).join('')}</div><button class="btn" onclick="finishInstall()">Finish Installation</button><pre id="installResult"></pre></div></div>`}
window.finishInstall=async()=>{$('#installResult').textContent=JSON.stringify(await (await fetch('/api/install',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({company:state.home,license:{validationEnabled:false,status:'verification_disabled'},modules:state.registry.managerList.map(m=>m.id)})})).json(),null,2)};
function renderPublicDoc(kind,id){$('#app').innerHTML=shell(`<main class="section"><div class="panel"><h1>${kind} ${escapeHtml(id)}</h1><p class="muted">Secure public ${kind.toLowerCase()} viewer with acceptance/download/payment actions.</p><button class="btn">${kind==='Quote'?'Accept Quote':'Pay Invoice'}</button> <button class="btn secondary">Download</button></div></main>`)}
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))} function escapeAttr(s=''){return escapeHtml(s).replace(/'/g,'&#39;')}
boot();
