const $ = (s, r=document) => r.querySelector(s);
const api = async (path, options={}) => {
  const res = await fetch(`/api${path}`, { headers:{'content-type':'application/json'}, ...options, body: options.body && typeof options.body !== 'string' ? JSON.stringify(options.body) : options.body });
  return res.json();
};
const steps = ['Welcome','Company','Branding','Theme','Owner Account','Services','Modules','Homepage','Review','Finish'];
const protectedPrefixes = ['/dashboard','/portal','/login','/quote','/invoice','/account'];
let registry = [];
async function loadRegistry(){ const r = await fetch('/assets/module-registry.json').then(r=>r.json()).catch(()=>({modules:[]})); registry = r.modules || []; return registry; }
function top(company='Your Platform'){ return `<header class="topbar"><div class="brand"><span class="logo">CM</span><span>${company}</span></div><nav><a class="btn ghost" href="/">Homepage</a> <a class="btn secondary" href="/dashboard/">Dashboard</a></nav></header>`; }
function sidebar(active='dashboard'){ return `<nav class="sidebar">${registry.map(m=>`<a class="${active===m.id?'active':''}" href="${m.route}">${m.name}</a>`).join('')}</nav><nav class="mobile-nav">${registry.filter(m=>m.nav?.mobile).map(m=>`<a href="${m.route}">${m.name}</a>`).join('')}</nav>`; }
function emptyAction(m){ return `<div class="card"><span class="pill">${m.category}</span><h2>${m.name}</h2><p class="muted">${m.emptyState?.body || 'No records yet. This module is ready to use.'}</p><button class="btn" onclick="alert('Demo action created for ${m.name}')">${m.emptyState?.action || 'Create Record'}</button></div>`; }
async function gate(){ const st = await api('/install-status').catch(()=>({installation_complete:false})); const path = location.pathname; if (!st.installation_complete && !path.startsWith('/install')) { history.replaceState(null,'','/install/'); return false; } if (st.installation_complete && path.startsWith('/install')) { history.replaceState(null,'','/dashboard/'); } return st.installation_complete; }
function renderInstall(){ let current = Number(localStorage.installStep || 0); let draft = {}; const save = async () => { const form = Object.fromEntries(new FormData($('#installForm')).entries()); draft = { ...draft, ...form }; localStorage.installDraft = JSON.stringify(draft); await api('/install/draft',{method:'POST',body:draft}); };
  const screen = () => { const body = [
    `<h1>Welcome</h1><p>Simple install. Full platform. Optional integrations are detected but never block first install.</p><div class="okbox card">Fresh deploy is in installer mode. Homepage, dashboards, portals, public quotes, and invoices stay blocked until Finish.</div>`,
    `<h1>Company</h1><label>Company Name<input name="companyName" value="${draft.companyName||''}" placeholder="Auto-detected if available"></label><label>Service Area<input name="serviceArea" value="${draft.serviceArea||''}"></label>`,
    `<h1>Branding</h1><label>Logo URL<input name="logoUrl" value="${draft.logoUrl||''}"></label><label>Brand Color<input name="brandColor" value="${draft.brandColor||'#2563eb'}"></label><label>Accent Color<input name="accentColor" value="${draft.accentColor||'#14b8a6'}"></label>`,
    `<h1>Theme</h1><label>Theme<select name="theme"><option>Modern Contractor</option><option>Clean Light</option><option>Bold Industrial</option></select></label>`,
    `<h1>Owner Account</h1><label>Owner Name<input name="ownerName" value="${draft.ownerName||''}"></label><label>Owner Email<input name="ownerEmail" value="${draft.ownerEmail||''}" type="email"></label><p class="muted">Email delivery can be configured later. Install creates an owner setup/session path.</p>`,
    `<h1>Services</h1><label>Core Services<textarea name="services" rows="5">${draft.services||'General Repair\nPreventive Maintenance\nEmergency Service\nInspection\nInstallation'}</textarea></label>`,
    `<h1>Modules</h1><p>${registry.length} drop-in modules auto-detected from module manifests.</p><div class="grid">${registry.map(m=>`<div class="card"><strong>${m.name}</strong><br><span class="muted">${m.workspaces.join(', ')}</span></div>`).join('')}</div>`,
    `<h1>Homepage</h1><label>Headline<input name="homepageHeadline" value="${draft.homepageHeadline||'Contractor service made simple'}"></label><label>Subheadline<textarea name="homepageSubheadline">${draft.homepageSubheadline||'Request estimates, approve quotes, and track work from one branded portal.'}</textarea></label>`,
    `<h1>Review</h1><div id="health" class="card">Checking installer health…</div><p>Missing OpenAI, Square, Resend, SMTP, SerpAPI, reCAPTCHA, license, Google Maps, and supplier APIs will be warnings only.</p>`,
    `<h1>Finish</h1><p>Finish will save company settings, branding, theme, owner, roles, permissions, services, module registry, homepage config, bootstrap config, and installation_complete=true.</p><button type="button" id="finish" class="btn ok">Finish Install</button>`
  ][current];
  $('#app').innerHTML = `<main class="installer"><div class="card"><div class="brand"><span class="logo">CM</span><span>White-Label Contractor CMMS + AI Quoting Platform</span></div><div class="steps">${steps.map((s,i)=>`<span class="step ${i===current?'active':''}">${i+1}. ${s}</span>`).join('')}</div><form id="installForm">${body}<div style="display:flex;gap:10px;justify-content:space-between;margin-top:18px"><button type="button" class="btn ghost" id="back" ${current===0?'disabled':''}>Back</button><button type="button" class="btn" id="next" ${current===steps.length-1?'style="display:none"':''}>Save & Continue</button></div></form></div></main>`;
  $('#back')?.addEventListener('click', async()=>{ await save(); current--; localStorage.installStep=current; screen(); });
  $('#next')?.addEventListener('click', async()=>{ await save(); current++; localStorage.installStep=current; screen(); if(current===8) health(); });
  $('#finish')?.addEventListener('click', async()=>{ await save(); const payload={ company:{name:draft.companyName, serviceArea:draft.serviceArea}, branding:{logoUrl:draft.logoUrl, brandColor:draft.brandColor, accentColor:draft.accentColor}, theme:{name:draft.theme}, owner:{name:draft.ownerName,email:draft.ownerEmail}, services:String(draft.services||'').split('\n').filter(Boolean), homepage:{headline:draft.homepageHeadline,subheadline:draft.homepageSubheadline} }; const done=await api('/install/finish',{method:'POST',body:payload}); if(done.ok) location.href='/dashboard/'; });
  if(current===8) health(); };
  const health = async()=>{ const h=await api('/install/health'); $('#health').innerHTML = `<h3>Auto Detect</h3><p>Modules: ${h.detected.moduleCount}. Site URL: ${h.detected.siteUrl || 'not set yet'}.</p><h3>Integration Warnings</h3>${h.optionalIntegrations.map(i=>`<div class="${i.configured?'okbox':'warn'} card"><strong>${i.key}</strong>: ${i.message}</div>`).join('')}`; };
  (async()=>{ await loadRegistry(); const d=await api('/install/draft'); draft = { ...(d.draft||{}), ...(JSON.parse(localStorage.installDraft||'{}')) }; screen(); })(); }
async function renderHome(){ $('#app').innerHTML = `${top()}<main class="content"><section class="hero"><h1>Contractor service made simple</h1><p>Request estimates, approve quotes, track work, view invoices, and manage maintenance plans in a white-label portal.</p><a class="btn" href="/dashboard/modules/request-estimate">Request Estimate</a></section><div class="grid" style="margin-top:18px"><div class="card"><h2>AI + Manual Estimating</h2><p>AI photo estimates and quote builders work when OpenAI is configured and fall back to manual mode when not.</p></div><div class="card"><h2>Client & Worker Portals</h2><p>Keep clients, workers, managers, admins, and owners aligned through role-aware workspaces.</p></div><div class="card"><h2>End-to-End Workflow</h2><p>Request → quote → work order → schedule → completion → invoice → payment → archive.</p></div></div></main>`; }
async function renderDashboard(){ /* Welcome to Your New Business Platform */ const d = await api('/dashboard'); $('#app').innerHTML = `${top()}<div class="layout">${sidebar('dashboard')}<main class="content"><h1>${d.headline}</h1><div class="grid"><div class="card"><h2>Quick Start Checklist</h2>${d.checklist.map(x=>`<p><button class="btn secondary">${x}</button></p>`).join('')}</div><div class="card"><h2>Business Health</h2><p><strong>${d.health.modules}</strong> modules enabled</p><p><strong>${d.health.activeWorkflows}</strong> active workflows</p><p class="warn card">${d.health.integrations.filter(i=>!i.configured).length} optional integrations need attention.</p></div><div class="card"><h2>Recommended Actions</h2><p>Create your first client, request, quote, and work order. Then open System Center to configure email, payments, AI, maps, license, and suppliers.</p><a class="btn" href="/dashboard/modules/system-center">Open System Center</a></div></div><h2>Workspaces</h2><div class="grid">${['Owner','Admin','Manager','Worker','Client'].map(w=>`<div class="card"><h3>${w} Dashboard</h3><p>Role-aware ${w.toLowerCase()} view with no empty screens.</p><button class="btn ghost" onclick="switchView('${w.toLowerCase()}')">Switch to ${w}</button></div>`).join('')}</div></main></div>`; }
window.switchView = async (workspace)=>{ await api('/view-switch',{method:'POST',body:{actor:'owner',workspace}}); alert(`Switched to ${workspace} view`); };
async function renderModule(id){ const m = registry.find(x=>x.id===id); if(!m){ $('#app').innerHTML=`${top()}<main class="content"><div class="bad card">Module not found.</div></main>`; return; } const sys = id==='system-center' || id==='environment-integrations'; $('#app').innerHTML = `${top()}<div class="layout">${sidebar(id)}<main class="content">${emptyAction(m)}<div class="grid"><div class="card"><h3>Permissions</h3>${m.permissions.map(p=>`<span class="pill">${p.key}</span> `).join('')}</div><div class="card"><h3>Workspaces</h3><p>${m.workspaces.join(', ')}</p></div><div class="card"><h3>API</h3><p>${m.apiBase}</p><button class="btn secondary" onclick="demoWorkflow()">Run workflow demo</button></div></div>${sys?`<div class="card"><h2>Environment & Integrations</h2><p>Configure OpenAI, Resend, Square, SMTP, SerpAPI, reCAPTCHA, license server, Google Maps, and supplier APIs after install. Missing values are warnings only.</p><div id="integrations">Loading…</div></div>`:''}</main></div>`; if(sys){ const s=await api('/system/integrations'); $('#integrations').innerHTML=s.integrations.map(i=>`<div class="${i.configured?'okbox':'warn'} card"><strong>${i.key}</strong> — ${i.message}</div>`).join(''); } }
window.demoWorkflow = async()=>{ const w = await api('/workflow/demo',{method:'POST',body:{}}); alert(`Workflow ready at stage ${w.workflow.currentStage}`); };

async function renderPublicDocument(kind, id){ const endpoint = kind === 'quote' ? `/public/quote/${id||'demo'}` : `/public/invoice/${id||'demo'}`; const r = await api(endpoint); $('#app').innerHTML = `${top()}<main class="content"><div class="card"><span class="pill">Public ${kind}</span><h1>${kind === 'quote' ? 'Public Quote View' : 'Public Invoice View'}</h1><p class="muted">Secure branded ${kind} page for client review without exposing admin screens.</p><pre>${JSON.stringify(r[kind] || r, null, 2)}</pre><button class="btn ok">${kind === 'quote' ? 'Accept Quote' : 'Record / Open Payment'}</button></div></main>`; }

async function renderLogin(){ $('#app').innerHTML = `${top()}<main class="content"><div class="card"><h1>Magic Login</h1><p>Passwordless email links support owners, admins, managers, workers, and clients.</p><label>Email<input id="email" type="email"></label><button class="btn" id="send">Send Magic Link</button><div id="loginResult"></div></div></main>`; $('#send').onclick=async()=>{ const r=await api('/auth/magic-link',{method:'POST',body:{email:$('#email').value}}); $('#loginResult').innerHTML=`<div class="${r.ok?'okbox':'warn'} card">${r.message}</div>`; }; }
async function main(){ await loadRegistry(); const installed = await gate(); if(location.pathname.startsWith('/install')) return renderInstall(); if(!installed) return renderInstall(); if(location.pathname==='/') return renderHome(); if(location.pathname.startsWith('/login')) return renderLogin(); if(location.pathname.startsWith('/quote/')) return renderPublicDocument('quote', location.pathname.split('/').pop()); if(location.pathname.startsWith('/invoice/')) return renderPublicDocument('invoice', location.pathname.split('/').pop()); if(location.pathname.startsWith('/dashboard/modules/')) return renderModule(location.pathname.split('/').filter(Boolean).pop()); if(location.pathname.startsWith('/dashboard') || location.pathname.startsWith('/portal')) return renderDashboard(); return renderHome(); }
main().catch(e=>{ $('#app').innerHTML=`<main class="content"><div class="bad card"><h1>Handled Error</h1><p>${e.message}</p><a class="btn" href="/install/">Open Installer</a></div></main>`; });
