import { CORE_MODULES } from '../lib/platformData.mjs';

const root = document.getElementById('root');
const navGroups = ['Main','Operations','Financial','People','AI Tools','System'];
const roleVisibility = { Owner: navGroups, Admin: ['Main','Operations','Financial','People'], Manager: ['Main','Operations'], Worker: ['Main','Operations'], Client: ['Main','Operations','Financial'] };
const moduleIcons = { 'Main':'⌂','Operations':'▣','Financial':'$','People':'◉','AI Tools':'✦','System':'⚙' };
const dataModules = {
  customers: { title:'Customers / Clients', api:'customers', fields:['full_name','email','phone','address'], empty:'No customers yet. Add the first client to start managing properties and requests.' },
  'request-estimate': { title:'Request Estimate', api:'requests', fields:['customer_name','service_category','description','status'], empty:'No estimate requests yet. Create a manual request or accept one from the client portal.' },
  'estimate-quote-center': { title:'Estimate & Quote Center', api:'quotes', fields:['customer_name','title','total','status'], empty:'No quotes yet. Build a manual quote, then send it for approval.' },
  'work-orders': { title:'Work Orders', api:'work-orders', fields:['customer_name','summary','assigned_to','status'], empty:'No work orders yet. Approved quotes can create work orders automatically.' },
  'schedule-calendar': { title:'Schedule / Calendar', api:'schedule-events', fields:['title','starts_at','worker','status'], empty:'No scheduled events yet. Assign work orders to place them on the calendar.' },
  inventory: { title:'Inventory', api:'inventory', fields:['name','sku','quantity','reorder_level'], empty:'No inventory items yet. Add materials and tools to track stock.' },
  invoices: { title:'Invoices', api:'invoices', fields:['customer_name','invoice_number','amount_due','status'], empty:'No invoices yet. Completed work can generate invoices.' },
  payments: { title:'Payments', api:'payments', fields:['customer_name','amount','method','status'], empty:'No payments yet. Record manual payments or connect Square later.' },
  finance: { title:'Finance', api:'payments', fields:['customer_name','amount','method','status'], empty:'No finance activity yet. Manual payment tracking works without Square.' },
};
const modules = CORE_MODULES.map(([slug,name,group,route]) => ({ slug,name,group,route }));
async function api(path, options) { const r = await fetch(`/api/${path}`, { headers:{'content-type':'application/json'}, ...options }); return r.json(); }
function escapeHtml(value='') { return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function applyTheme(theme) { const prefersDark = window.matchMedia?.('(prefers-color-scheme: dark)').matches; const resolved = theme.mode === 'system' ? (prefersDark ? 'dark' : 'light') : theme.mode; document.documentElement.dataset.theme = resolved; Object.entries({ '--primary':theme.primary, '--accent':theme.accent, '--color-background':theme.background, '--color-surface':theme.surface, '--color-text':theme.text }).forEach(([k,v]) => v && document.documentElement.style.setProperty(k, v)); }
function renderInstaller() {
  const draft = { company:{ name:'Contractor Company' }, owner:{ fullName:'Platform Owner', email:'owner@example.com' }, theme:{ mode:'system', primary:'#2563eb', accent:'#10b981', background:'#f8fafc', surface:'#ffffff', text:'#0f172a' }};
  root.innerHTML = `<main class="installer"><section class="install-card"><span class="eyebrow">Installer</span><h1>Launch your white-label contractor CMMS</h1><p>Simple installer, complete platform. Optional integrations never block installation.</p><div class="grid two"><label>Company name<input id="company" value="${draft.company.name}"></label><label>Owner email<input id="ownerEmail" value="${draft.owner.email}"></label><label>Owner full name<input id="ownerName" value="${draft.owner.fullName}"></label><label>Theme mode<select id="mode"><option>system</option><option>light</option><option>dark</option></select></label><label>Primary<input id="primary" type="color" value="${draft.theme.primary}"></label><label>Accent<input id="accent" type="color" value="${draft.theme.accent}"></label></div><div class="actions"><button id="saveDraft">Save Draft</button><button class="primary" id="finish">Finish Install</button></div><div id="installResult"></div></section><aside class="install-card preview"><h2>Live theme preview</h2><div class="sample-shell"><b id="previewName">Contractor Company</b><button>Primary action</button><article>Dashboard card, public homepage card, inputs, and buttons update live.</article></div><h3>Environment & Integrations</h3><p>These integrations can be configured later in System Center.</p><div id="integrations"></div></aside></main>`;
  const refresh = () => { draft.company.name = document.getElementById('company').value; draft.owner.email = document.getElementById('ownerEmail').value; draft.owner.fullName = document.getElementById('ownerName').value; draft.theme.mode = document.getElementById('mode').value; draft.theme.primary = document.getElementById('primary').value; draft.theme.accent = document.getElementById('accent').value; document.getElementById('previewName').textContent = draft.company.name; applyTheme(draft.theme); };
  root.querySelectorAll('input,select').forEach(el => el.addEventListener('input', refresh));
  window.matchMedia?.('(prefers-color-scheme: dark)')?.addEventListener?.('change', refresh);
  document.getElementById('saveDraft').onclick = async () => { refresh(); await api('install/draft',{method:'POST',body:JSON.stringify(draft)}); document.getElementById('installResult').innerHTML='<div class="success">Installer draft saved correctly.</div>'; };
  document.getElementById('finish').onclick = async () => { refresh(); const x = await api('install/finish',{method:'POST',body:JSON.stringify(draft)}); document.getElementById('installResult').innerHTML = x.ok ? '<div class="success">Finish Install created a real platform: owner, roles, permissions, settings, modules, services, and audit logs.</div>' : `<div class="empty">${escapeHtml(x.error)}</div>`; };
  api('install/integration-status').then(x => document.getElementById('integrations').innerHTML = (x.integrations||[]).map(i => `<div class="status"><b>${i.key}</b><span>${i.statusText}</span></div>`).join(''));
}
function renderSidebar(role) { return `<aside class="sidebar"><div class="brand"><div class="logo">CM</div><div><b>Contractor CMMS</b><small>Default workspace</small></div></div><div class="rolebox"><span>Viewing as: ${role}</span>${role!=='Owner'?`<div class="banner">Testing ${role} View as Owner <button data-role="Owner">Exit Test View</button></div>`:''}<select id="roleView">${['Owner','Admin','Manager','Worker','Client'].map(r=>`<option ${r===role?'selected':''}>${r}</option>`).join('')}</select></div>${navGroups.filter(g => roleVisibility[role].includes(g)).map(group => `<nav><h3>${group}</h3>${modules.filter(m => m.group === group).map(m => `<a class="${location.pathname===m.route?'active':''}" href="${m.route}"><span>${moduleIcons[group]}</span><span>${m.name}</span></a>`).join('')}</nav>`).join('')}<button class="collapse" id="collapse">Collapse mode</button></aside>`; }
async function renderCrud(config) { const x = await api(config.api); return `<section class="panel"><h1>${config.title}</h1><p>${config.empty}</p><div class="grid form">${config.fields.map(f=>`<label>${f.replaceAll('_',' ')}<input id="field-${f}"></label>`).join('')}<button class="primary" id="saveRecord">Save ${config.title}</button></div><div class="cards">${(x.items||[]).length ? x.items.map(item => `<article>${config.fields.map(f => `<p><b>${f}:</b> ${escapeHtml(item[f] || '—')}</p>`).join('')}</article>`).join('') : `<article class="empty">${config.empty}</article>`}</div></section>`; }
async function renderContent(slug) { if (slug === 'dashboard-overview') return `<section class="panel"><h1>Dashboard / Overview</h1><div class="cards stats"><article><b>Open Requests</b><strong>0</strong></article><article><b>Active Work Orders</b><strong>0</strong></article><article><b>Unpaid Invoices</b><strong>0</strong></article><article><b>Setup Checklist</b><strong>Ready</strong></article></div><div class="quick"><button>New Customer</button><button>New Request</button><button>New Quote</button><button>Record Payment</button></div></section>`; if (dataModules[slug]) return renderCrud(dataModules[slug]); if (slug.startsWith('ai-')) { const status = await api('ai/status'); return `<section class="panel"><h1>${modules.find(m=>m.slug===slug)?.name}</h1>${status.configured ? '<div class="success">OpenAI is configured. Real AI jobs will run through the shared AI service.</div>' : '<div class="empty"><b>AI is not configured yet.</b><p>Configure OpenAI in System Center → Environment & Integrations. Manual workflow remains available.</p></div>'}</section>`; } return `<section class="panel"><h1>${modules.find(m=>m.slug===slug)?.name || 'Platform Module'}</h1><p>This production module is registered, permission-controlled, and database driven through the platform API.</p></section>`; }
async function renderApp() { const role = sessionStorage.getItem('roleView') || 'Owner'; const slug = modules.find(m => location.pathname === m.route)?.slug || 'dashboard-overview'; root.innerHTML = `<div class="app">${renderSidebar(role)}<main class="content">${role !== 'Owner' ? `<div class="test-banner">Testing ${role} View as Owner <button data-role="Owner">Exit Test View</button></div>`:''}${await renderContent(slug)}</main><nav class="mobile-nav">${modules.slice(0,5).map(m=>`<a href="${m.route}">${m.name.split(' ')[0]}</a>`).join('')}</nav></div>`; document.getElementById('roleView').onchange = e => { sessionStorage.setItem('roleView', e.target.value); renderApp(); }; root.querySelectorAll('[data-role]').forEach(b => b.onclick = () => { sessionStorage.setItem('roleView', b.dataset.role); renderApp(); }); const config = dataModules[slug]; if (config) document.getElementById('saveRecord').onclick = async () => { const body = Object.fromEntries(config.fields.map(f => [f, document.getElementById(`field-${f}`).value])); await api(config.api,{method:'POST',body:JSON.stringify(body)}); renderApp(); }; }
(async function bootstrap(){ if (location.pathname.startsWith('/install')) return renderInstaller(); const status = await api('install-status').catch(()=>({installed:false})); if (!status.installed) return renderInstaller(); renderApp(); })();
