import { HttpError, hasPermission, type AuthUser } from '../auth';
import { createDatabase, type Queryable } from '../database';
import { requireLicensedModule } from '../license-client';

export const AI_CODES = { notConfigured:'AI_NOT_CONFIGURED', locked:'LICENSE_MODULE_LOCKED', invalid:'AI_OUTPUT_INVALID', research:'AI_RESEARCH_FAILED', timeout:'AI_TIMEOUT', modelParameter:'AI_MODEL_PARAMETER_ERROR' } as const;
export type AiModuleKey = 'ai_quoting' | 'ai_troubleshooting';
const DEFAULT_QUOTE_SETTINGS = { enabled: true, defaultModel: process.env.OPENAI_MODEL || 'gpt-5.5', maxProcessSeconds: 15, webResearchEnabled: false, fallbackWithoutResearchEnabled: true, requireHumanApproval: true, hourlyLaborRate: 95, minimumServiceFee: 125, markupPercentage: 20, taxPercentage: 0, preferredSuppliers: '', serviceArea: '', excludedJobTypes: '', confidenceThreshold: 'medium', autoCreateQuoteDraft: true, autoSendQuote: false, openAiModel: process.env.OPENAI_MODEL || 'gpt-5.5', openAiTimeoutSeconds: 15, serpApiTimeoutSeconds: 5, maxSources: 3, maxPromptCharacters: 6000, timeoutSeconds: 15, enableWebResearch: false, maxSearchResults: 3, allowFallbackWithoutResearch: true, maxPromptLength: 6000, serpApiEnabled: false };
const DEFAULT_TROUBLESHOOTING_SETTINGS = { defaultModel: process.env.OPENAI_MODEL || 'gpt-5.5', maxProcessSeconds: 15, webResearchEnabled: false, fallbackWithoutResearchEnabled: true, openAiModel: process.env.OPENAI_MODEL || 'gpt-5.5', openAiTimeoutSeconds: 15, serpApiTimeoutSeconds: 5, maxSources: 3, maxPromptCharacters: 6000, timeoutSeconds: 15, enableWebResearch: false, maxSearchResults: 3, allowFallbackWithoutResearch: true, maxPromptLength: 6000 };

export function isUuid(value: unknown): value is string { return typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value); }

export async function ensureAiFoundation(db: Queryable = createDatabase()) {
  await db.query(`create table if not exists ai_jobs (id uuid primary key default gen_random_uuid(), module_key text not null, job_type text not null, related_type text, related_id uuid, status text default 'queued', stage text default 'queued', input jsonb default '{}'::jsonb, output jsonb default '{}'::jsonb, error_code text, error_message text, warnings jsonb default '[]'::jsonb, sources jsonb default '[]'::jsonb, model text, attempts int default 0, max_attempts int default 3, created_by uuid references users(id), created_at timestamptz default now(), updated_at timestamptz default now(), started_at timestamptz, completed_at timestamptz)`);
  await db.query(`create table if not exists ai_runs (id uuid primary key default gen_random_uuid(), module_key text not null, related_type text, related_id uuid, status text default 'queued', input jsonb default '{}'::jsonb, output jsonb default '{}'::jsonb, model text, search_used boolean default false, confidence text, error_message text, created_by uuid references users(id), created_at timestamptz default now(), updated_at timestamptz default now())`);
  await db.query(`create table if not exists ai_sources (id uuid primary key default gen_random_uuid(), ai_run_id uuid references ai_runs(id) on delete cascade, title text, url text, snippet text, source_type text, created_at timestamptz default now())`);
  await db.query(`create table if not exists ai_quote_drafts (id uuid primary key default gen_random_uuid(), request_id uuid references work_requests(id), quote_id uuid references quotes(id), ai_run_id uuid references ai_runs(id), status text default 'needs_review', confidence text, summary text, output jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now())`);
  await db.query(`create table if not exists ai_troubleshooting_reports (id uuid primary key default gen_random_uuid(), job_id uuid references jobs(id), work_request_id uuid references work_requests(id), ai_run_id uuid references ai_runs(id), status text default 'draft', equipment_type text, make text, model text, error_code text, issue text, output jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now())`);
  await db.query(`alter table ai_quote_drafts add column if not exists ai_job_id uuid references ai_jobs(id)`);
  await db.query(`alter table ai_troubleshooting_reports add column if not exists ai_job_id uuid references ai_jobs(id)`);
  await db.query(`create table if not exists ai_settings (id uuid primary key default gen_random_uuid(), key text unique not null, value jsonb default '{}'::jsonb, updated_at timestamptz default now())`);
  await db.query(`insert into ai_settings (key,value) values ('ai_quoting',$1::jsonb) on conflict (key) do nothing`, [JSON.stringify(DEFAULT_QUOTE_SETTINGS)]);
  await db.query(`insert into ai_settings (key,value) values ('ai_troubleshooting',$1::jsonb) on conflict (key) do nothing`, [JSON.stringify(DEFAULT_TROUBLESHOOTING_SETTINGS)]);
}

export function aiError(code: string, error: string, status = 400) { throw new HttpError(status, `${code}:${error}`); }
export function aiResponseError(error: unknown) { const msg = error instanceof Error ? error.message : String(error); const [code, ...rest] = msg.split(':'); return { ok:false, code: code || 'AI_ERROR', error: rest.join(':') || msg }; }
export function selectedModel(settings?: any) { return String(settings?.openAiModel || settings?.defaultModel || process.env.OPENAI_MODEL || process.env.OPENAI_FALLBACK_MODEL || 'gpt-5.5'); }
export async function getAiSettings(db: Queryable = createDatabase()) { await ensureAiFoundation(db); const r = await db.query(`select key,value,updated_at::text as "updatedAt" from ai_settings order by key`); return { ok:true, settings:Object.fromEntries(r.rows.map((x:any)=>[x.key,x.value])), environment:{ openAiConfigured:Boolean(process.env.OPENAI_API_KEY), serpApiConfigured:Boolean(process.env.SERPAPI_API_KEY), defaultModel:process.env.OPENAI_MODEL || 'gpt-5.5' } }; }
export async function patchAiSettings(body:any, user:AuthUser, db:Queryable=createDatabase()) { await ensureAiFoundation(db); const entries = body.settings && typeof body.settings==='object' ? body.settings : body; for (const [key,value] of Object.entries(entries)) if (key.startsWith('ai_')) await db.query(`insert into ai_settings (key,value,updated_at) values ($1,$2::jsonb,now()) on conflict (key) do update set value=excluded.value,updated_at=now()`, [key, JSON.stringify(value)]); return getAiSettings(db); }

export function supportsCustomTemperature(model: string): boolean { const normalized = String(model || '').toLowerCase(); return !(normalized.startsWith('gpt-5') || normalized.startsWith('o-series') || normalized.startsWith('o1') || normalized.startsWith('o3') || normalized.startsWith('o4')); }
export function buildOpenAiJsonPayload(prompt:string, model:string, temperature?:number) { const payload:any = { model, response_format:{type:'json_object'}, messages:[{role:'system',content:'Return valid JSON only. Be conservative. Do not claim certainty when information is weak.'},{role:'user',content:prompt}] }; if (temperature != null && (supportsCustomTemperature(model) || temperature === 1)) payload.temperature = temperature; return payload; }
export async function runOpenAiJson(prompt:string, schema:any, model:string, temperature = 0.2, timeoutMs = 25000) { if (!process.env.OPENAI_API_KEY) aiError('AI_NOT_CONFIGURED','OpenAI API key is missing',503); const ctrl = new AbortController(); const t = setTimeout(()=>ctrl.abort(), timeoutMs); try { const res = await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',signal:ctrl.signal,headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify(buildOpenAiJsonPayload(prompt, model, temperature))}); const data:any=await res.json().catch(()=>({})); if(!res.ok) { const message = data.error?.message || 'OpenAI request failed'; if (/temperature|unsupported|not support|does not support|parameter/i.test(message)) aiError('AI_MODEL_PARAMETER_ERROR','The configured OpenAI model does not support one of the requested parameters. The request was adjusted; please retry.',400); throw new Error(message); } return JSON.parse(data.choices?.[0]?.message?.content || '{}'); } catch(e:any){ if(e?.name==='AbortError') aiError('AI_TIMEOUT','OpenAI request timed out',504); throw e; } finally { clearTimeout(t); } }
export async function serpSearch(terms:string[], timeoutMs = 8000) { if(!process.env.SERPAPI_API_KEY) return { searchUsed:false, warning:'SERPAPI_NOT_CONFIGURED', sources:[] as any[], searchTerms:terms }; const ctrl = new AbortController(); const timer = setTimeout(()=>ctrl.abort(), timeoutMs); const sources:any[]=[]; try { for (const q of terms.slice(0,4)) { const u = new URL('https://serpapi.com/search.json'); u.searchParams.set('engine','google'); u.searchParams.set('q',q); u.searchParams.set('api_key',process.env.SERPAPI_API_KEY!); const r:any = await fetch(u, { signal: ctrl.signal }).then(x=>x.json()).catch((e)=>{ if(e?.name==='AbortError') throw e; return {}; }); for (const it of (r.organic_results || []).slice(0,3)) sources.push({ title:it.title, url:it.link, snippet:it.snippet, source_type:'serpapi' }); } return { searchUsed:true, sources, searchTerms:terms }; } catch(e:any) { if (e?.name === 'AbortError') return { searchUsed:false, warning:'Search research timed out. AI diagnosis used provided details only.', sources:[] as any[], searchTerms:terms }; return { searchUsed:false, warning:'AI_RESEARCH_FAILED', sources:[] as any[], searchTerms:terms }; } finally { clearTimeout(timer); } }

function normalizeTroubleshootingOutput(output:any, fallbackSources:any[] = []) {
  const value = output && typeof output === 'object' ? output : {};
  return {
    likelyCauses: Array.isArray(value.likelyCauses) ? value.likelyCauses : [],
    safetyWarnings: Array.isArray(value.safetyWarnings) ? value.safetyWarnings : [],
    firstChecks: Array.isArray(value.firstChecks) ? value.firstChecks : [],
    stepByStepDiagnostics: Array.isArray(value.stepByStepDiagnostics) ? value.stepByStepDiagnostics : [],
    partsPossiblyNeeded: Array.isArray(value.partsPossiblyNeeded) ? value.partsPossiblyNeeded : [],
    measurementsToTake: Array.isArray(value.measurementsToTake) ? value.measurementsToTake : [],
    manufacturerNotes: Array.isArray(value.manufacturerNotes) ? value.manufacturerNotes : [],
    whenToStopAndCallSpecialist: Array.isArray(value.whenToStopAndCallSpecialist) ? value.whenToStopAndCallSpecialist : [],
    customerExplanation: typeof value.customerExplanation === 'string' ? value.customerExplanation : '',
    workerSummary: typeof value.workerSummary === 'string' ? value.workerSummary : '',
    confidence: ['low','medium','high'].includes(String(value.confidence)) ? String(value.confidence) : 'low',
    sources: Array.isArray(value.sources) ? value.sources : fallbackSources,
    ...value,
  };
}

async function insertSources(db:Queryable, runId:string, sources:any[]) { for (const s of sources) await db.query(`insert into ai_sources (ai_run_id,title,url,snippet,source_type) values ($1,$2,$3,$4,$5)`,[runId,s.title,s.url,s.snippet,s.source_type||'serpapi']); }

export async function searchAiQuoteRequests(query:any, user?:AuthUser|null, db:Queryable=createDatabase()) {
  await ensureAiFoundation(db);
  await requireLicensedModule('ai_quoting', db);
  const q = String(query?.q || '').trim();
  const status = String(query?.status || '').trim();
  const limit = Math.min(Math.max(Number(query?.limit) || 20, 1), 50);
  const params: unknown[] = [];
  const where: string[] = ['true'];
  if (q) {
    params.push(`%${q}%`);
    const i = params.length;
    where.push(`(wr.id::text ilike $${i} or right(wr.id::text, 8) ilike $${i} or wr.title ilike $${i} or wr.description ilike $${i} or wr.status ilike $${i} or to_char(wr.created_at,'Mon DD YYYY') ilike $${i} or c.display_name ilike $${i} or c.email ilike $${i} or c.phone ilike $${i} or p.address ilike $${i} or sc.name ilike $${i})`);
  }
  if (status) { params.push(status); where.push(`wr.status = $${params.length}`); }
  params.push(limit);
  const r = await db.query<any>(`select wr.id::text, concat('REQ-', upper(right(wr.id::text, 6))) as "displayId", coalesce(nullif(wr.title,''),'Untitled request') as title, coalesce(c.display_name,'Unknown customer') as "clientName", c.email as "clientEmail", c.phone, coalesce(p.address,'No property address') as address, coalesce(wr.status,'new') as status, coalesce(sc.name,'General service') as "serviceCategory", wr.created_at::text as "createdAt", left(coalesce(wr.description,''), 180) as "descriptionPreview", (d.id is not null) as "hasAiQuote", case when d.id is null then 'not_run' when d.status in ('approved','quote_created') then 'approved' when d.status in ('failed','rejected') then 'failed' else 'draft' end as "aiStatus" from work_requests wr left join clients c on c.id=wr.client_id left join properties p on p.id=wr.property_id left join service_categories sc on sc.id=wr.service_category_id left join lateral (select id,status from ai_quote_drafts where request_id=wr.id order by created_at desc limit 1) d on true where ${where.join(' and ')} order by wr.created_at desc limit $${params.length}`, params);
  return { ok: true, requests: r.rows };
}

export async function runAiQuoteForRequest(requestId:string, user?:AuthUser|null, db:Queryable=createDatabase()) {
  if (!isUuid(requestId)) return { ok:false, code:'AI_QUOTE_REQUEST_ID_REQUIRED', error:'Valid request id is required.' };
  await ensureAiFoundation(db); await requireLicensedModule('ai_quoting', db);
  const settings=(await getAiSettings(db)).settings.ai_quoting || DEFAULT_QUOTE_SETTINGS;
  if(settings?.enabled===false) return {ok:false, code:'AI_DISABLED', error:'AI quoting is disabled.'};
  const req=(await db.query<any>(`select wr.id::text,wr.title,wr.description,wr.priority as urgency,c.display_name as client,c.email,c.phone,p.address,p.property_type as "propertyType",sc.name as service from work_requests wr left join clients c on c.id=wr.client_id left join properties p on p.id=wr.property_id left join service_categories sc on sc.id=wr.service_category_id where wr.id=$1::uuid`,[requestId])).rows[0];
  if(!req) throw new HttpError(404,'Request not found');
  const model=selectedModel(settings);
  const job=(await db.query(`insert into ai_jobs (module_key,job_type,related_type,related_id,status,stage,input,model,created_by) values ('ai_quoting','quote_draft','request',$1::uuid,'queued','queued',$2::jsonb,$3,$4::uuid) returning id::text`,[requestId,JSON.stringify(req),model,user?.id||null])).rows[0];
  const run=(await db.query(`insert into ai_runs (id,module_key,related_type,related_id,status,input,model,created_by) values ($1::uuid,'ai_quoting','request',$2::uuid,'queued',$3::jsonb,$4,$5::uuid) returning id::text`,[job.id,requestId,JSON.stringify(req),model,user?.id||null]).catch(async()=> (await db.query(`insert into ai_runs (module_key,related_type,related_id,status,input,model,created_by) values ('ai_quoting','request',$1::uuid,'queued',$2::jsonb,$3,$4::uuid) returning id::text`,[requestId,JSON.stringify(req),model,user?.id||null])))).rows[0];
  const draft=(await db.query(`insert into ai_quote_drafts (request_id,ai_run_id,ai_job_id,status,confidence,summary,output) values ($1::uuid,$2::uuid,$3::uuid,'queued','low','AI quote queued','{}'::jsonb) returning id::text`,[requestId,run.id,job.id])).rows[0];
  return {ok:true,status:'queued',aiJobId:job.id,aiRunId:run.id,draftId:draft.id,message:'AI quote started.'};
}

function stageSettings(settings:any){ return { maxSources:Number(settings?.maxSources ?? settings?.maxSearchResults ?? 3) || 3, promptChars:Number(settings?.maxPromptCharacters ?? settings?.maxPromptLength ?? 6000) || 6000, serpMs:Math.min(5000,(Number(settings?.serpApiTimeoutSeconds ?? 5)||5)*1000), openAiMs:Math.min(12000,(Number(settings?.openAiTimeoutSeconds ?? settings?.timeoutSeconds ?? 12)||12)*1000), web: Boolean(settings?.webResearchEnabled ?? settings?.enableWebResearch ?? false) }; }

export async function processAiQuoteRun(id:string, user?:AuthUser|null, db:Queryable=createDatabase()) {
  await ensureAiFoundation(db); await requireLicensedModule('ai_quoting', db);
  if (!isUuid(id)) return { ok:false, error:'AI job id is required.', code:'AI_JOB_ID_REQUIRED' };
  const settings=(await getAiSettings(db)).settings.ai_quoting || DEFAULT_QUOTE_SETTINGS; const st=stageSettings(settings);
  const run=(await db.query<any>(`select j.id::text as "aiJobId",j.status,j.stage,j.input,j.output,j.model,j.sources,j.warnings,j.error_code as "errorCode",d.id::text as "draftId",d.output as "draftOutput" from ai_jobs j left join ai_quote_drafts d on d.ai_job_id=j.id where (j.id=$1::uuid or d.id=$1::uuid) and j.module_key='ai_quoting' order by j.created_at desc limit 1`,[id])).rows[0];
  if(!run) throw new HttpError(404,'AI quote job not found');
  if(run.status==='completed') return {ok:true,status:'completed',stage:'completed',aiJobId:run.aiJobId,draftId:run.draftId,output:run.draftOutput||run.output||{},sources:run.sources||[],warnings:run.warnings||[]};
  if(run.status==='failed') return {ok:false,status:'failed',stage:'failed',aiJobId:run.aiJobId,draftId:run.draftId,code:run.errorCode,error:run.errorCode||'AI quote failed.',output:run.draftOutput||{},sources:run.sources||[],warnings:run.warnings||[]};
  const body=run.input||{};
  try {
    await db.query(`update ai_jobs set status='running',stage='drafting',started_at=coalesce(started_at,now()),updated_at=now() where id=$1`,[run.aiJobId]);
    await db.query(`update ai_runs set status='drafting',updated_at=now() where id=$1`,[run.aiJobId]).catch(()=>undefined);
    await db.query(`update ai_quote_drafts set status='drafting',summary='Drafting estimate',updated_at=now() where ai_job_id=$1`,[run.aiJobId]);
    const sources:any[] = [];
    const slim={title:body.title,description:String(body.description||'').slice(0,1000),serviceCategory:body.service,propertyType:body.propertyType,address:String(body.address||'').slice(0,120),urgency:body.urgency||body.priority};
    const prompt=`Contractor quote draft. Return compact JSON: summary, assumptions, questionsForClient, recommendedScope, labor, materials, priceRange, riskFactors, confidence, customerFriendlySummary. Request ${JSON.stringify(slim)}`.slice(0,Math.min(st.promptChars,2500));
    const output=await runOpenAiJson(prompt,{},run.model,0.2,15000); output.sources=sources; output.warnings=[];
    const confidence=String(output.confidence||'low');
    await db.query(`update ai_quote_drafts set status='needs_review',confidence=$2,summary=$3,output=$4::jsonb,updated_at=now() where ai_job_id=$1`,[run.aiJobId,confidence,output.summary||'AI Draft — needs human review',JSON.stringify(output)]);
    await db.query(`update ai_jobs set status='completed',stage='completed',output=$2::jsonb,warnings='[]'::jsonb,sources='[]'::jsonb,completed_at=now(),updated_at=now() where id=$1`,[run.aiJobId,JSON.stringify(output)]);
    await db.query(`update ai_runs set status='completed',output=$2::jsonb,updated_at=now() where id=$1`,[run.aiJobId,JSON.stringify(output)]).catch(()=>undefined);
    return {ok:true,status:'completed',stage:'completed',aiJobId:run.aiJobId,draftId:run.draftId,output,sources,warnings:[]};
  } catch(e:any){ const code=e.message?.split(':')[0]==='AI_TIMEOUT'?'AI_TIMEOUT':'AI_ERROR'; await db.query(`update ai_jobs set status='failed',stage='failed',error_code=$2,error_message=$3,completed_at=now(),updated_at=now() where id=$1`,[run.aiJobId,code,e.message||code]); await db.query(`update ai_runs set status='failed',error_message=$2,updated_at=now() where id=$1`,[run.aiJobId,code]).catch(()=>undefined); await db.query(`update ai_quote_drafts set status='failed',summary=$2,updated_at=now() where ai_job_id=$1`,[run.aiJobId,code]); return {ok:false,status:'failed',stage:'failed',aiJobId:run.aiJobId,draftId:run.draftId,code,error:e.message||'AI quote failed',sources:[],warnings:[]}; }
}
export async function getAiQuoteStatus(id:string, db:Queryable=createDatabase()) { await ensureAiFoundation(db); if (!isUuid(id)) return { ok:false, code:'AI_JOB_ID_REQUIRED', error:'AI job id is required.' }; const row=(await db.query<any>(`select j.id::text as "aiJobId",j.status,j.stage,j.output,j.sources,j.warnings,j.error_code as "errorCode",j.error_message as "errorMessage",d.id::text,d.request_id::text as "requestId",d.status as "draftStatus",d.confidence,d.summary,d.output as "draftOutput",d.created_at::text as "createdAt" from ai_jobs j left join ai_quote_drafts d on d.ai_job_id=j.id where j.id=$1::uuid or d.id=$1::uuid order by j.created_at desc limit 1`,[id])).rows[0]; if(!row) throw new HttpError(404,'AI quote job not found'); const draft={ id:row.id, requestId:row.requestId, aiJobId:row.aiJobId, aiRunId:row.aiJobId, status:row.draftStatus||row.status, stage:row.stage, confidence:row.confidence||(row.draftOutput||row.output||{}).confidence||'low', summary:row.summary||(row.draftOutput||row.output||{}).summary||'', output:row.draftOutput||row.output||{}, errorMessage:row.errorMessage||'' }; return {ok:true,status:row.status,stage:row.stage,aiJobId:row.aiJobId,draft,sources:row.sources||[],warnings:row.warnings||[]}; }
export async function getAiQuoteForRequest(requestId:string, db:Queryable=createDatabase()) { await ensureAiFoundation(db); const drafts=await db.query(`select d.id::text,d.status,d.confidence,d.summary,d.output,d.created_at::text as "createdAt",coalesce(j.id,d.ai_run_id)::text as "aiJobId",coalesce(j.id,d.ai_run_id)::text as "aiRunId",j.stage,j.sources,j.warnings from ai_quote_drafts d left join ai_jobs j on j.id=d.ai_job_id where d.request_id=$1::uuid order by d.created_at desc`,[requestId]); return {ok:true,drafts:drafts.rows,sources:(drafts.rows[0] as any)?.sources||[]}; }
export async function quoteDraftAction(id:string, action:string, user:AuthUser, db:Queryable=createDatabase()) { await ensureAiFoundation(db); await requireLicensedModule('ai_quoting',db); if(action==='rerun'){ const d=(await db.query<any>(`select request_id::text as "requestId" from ai_quote_drafts where id=$1::uuid`,[id])).rows[0]; if(!d) throw new HttpError(404,'AI draft not found'); return runAiQuoteForRequest(d.requestId,user,db); } if(action==='approve'||action==='reject'){ await db.query(`update ai_quote_drafts set status=$2,updated_at=now() where id=$1`,[id,action==='approve'?'approved':'rejected']); return {ok:true,id,status:action}; } if(action==='create-quote'){ const d=(await db.query<any>(`select * from ai_quote_drafts where id=$1::uuid`,[id])).rows[0]; const req=(await db.query<any>(`select client_id,property_id from work_requests where id=$1`,[d.request_id])).rows[0]; const total=Math.round(Number(d.output?.priceRange?.high || d.output?.priceRange?.low || 0)*100); const q=(await db.query(`insert into quotes (client_id,request_id,property_id,status,total_cents,customer_notes) values ($1,$2,$3,'draft',$4,$5) returning id::text`,[req.client_id,d.request_id,req.property_id,total,d.output?.customerFriendlySummary||d.summary])).rows[0]; await db.query(`update ai_quote_drafts set quote_id=$2,status='quote_created',updated_at=now() where id=$1`,[id,q.id]); return {ok:true,id,quoteId:q.id}; } throw new HttpError(405,'Method not allowed'); }
export async function searchTroubleshootingJobs(query:any, user:AuthUser, db:Queryable=createDatabase()) {
  await ensureAiFoundation(db); await requireLicensedModule('ai_troubleshooting', db);
  if (!hasPermission(user, 'jobs.view')) throw new HttpError(403, 'Missing permission jobs.view');
  const q=String(query?.q||'').trim(); const statusFilter=String(query?.status||'active').trim(); const limit=Math.min(Math.max(Number(query?.limit)||20,1),50);
  const active=['scheduled','in_progress','paused','waiting_parts','waiting_customer','blocked','approved','ready'];
  const completed=['completed','closed','canceled','cancelled'];
  const waiting=['waiting_parts','waiting_customer','paused','blocked'];
  const params:unknown[]=[]; const where:string[]=['true'];
  const statusMap:Record<string,string[]>={active,scheduled:['scheduled','approved','ready'],in_progress:['in_progress'],waiting,completed};
  if (statusFilter !== 'all') where.push(`lower(j.status) in (${(statusMap[statusFilter]||active).map(x=>`'${x}'`).join(',')})`);
  if (q) { params.push(`%${q}%`); const i=params.length; where.push(`(j.id::text ilike $${i} or concat('JOB-', upper(right(j.id::text, 6))) ilike $${i} or j.title ilike $${i} or j.scope ilike $${i} or j.status ilike $${i} or c.display_name ilike $${i} or p.address ilike $${i} or u.name ilike $${i} or q.id::text ilike $${i} or wr.id::text ilike $${i} or wr.title ilike $${i})`); }
  params.push(limit);
  const r=await db.query<any>(`select j.id::text, concat('JOB-', upper(right(j.id::text, 6))) as "displayId", coalesce(nullif(j.title,''),'Work order') as title, coalesce(c.display_name,'Unknown customer') as "clientName", c.id::text as "clientId", coalesce(p.address,'No property address') as "propertyAddress", p.id::text as "propertyId", coalesce(u.name,'Unassigned') as "assignedTechnician", coalesce(j.status,'scheduled') as status, coalesce(j.scope,wr.description,'') as scope, q.id::text as "quoteId", wr.id::text as "requestId", j.created_at::text as "createdAt", s.starts_at::text as "scheduledAt", jsonb_build_object('type', coalesce(a.asset_type,''), 'make', coalesce(a.manufacturer,''), 'model', coalesce(a.model_number,''), 'serial', coalesce(a.serial_number,'')) as equipment from jobs j left join users u on u.id=j.assigned_user_id left join clients c on c.id=j.client_id left join properties p on p.id=j.property_id left join quotes q on q.id=j.quote_id left join work_requests wr on wr.id=j.request_id left join lateral (select starts_at from schedules s where s.job_id=j.id order by s.starts_at asc limit 1) s on true left join lateral (select * from assets a where a.property_id=j.property_id order by a.updated_at desc nulls last limit 1) a on true where ${where.join(' and ')} order by coalesce(s.starts_at,j.created_at) desc limit $${params.length}`,[...params]);
  return {ok:true,jobs:r.rows};
}

export async function runTroubleshooting(body:any,user:AuthUser,db:Queryable=createDatabase()) {
  await ensureAiFoundation(db); await requireLicensedModule('ai_troubleshooting',db);
  const jobId = body?.jobId ? String(body.jobId) : ''; const workRequestId = body?.workRequestId ? String(body.workRequestId) : '';
  if (jobId && !isUuid(jobId)) return {ok:false, code:'AI_TROUBLESHOOTING_JOB_ID_INVALID', error:'Selected job is invalid.'};
  if (workRequestId && !isUuid(workRequestId)) return {ok:false, code:'AI_TROUBLESHOOTING_REQUEST_ID_INVALID', error:'Selected work request is invalid.'};
  let job:any=null; if (jobId) job=(await db.query<any>(`select j.id::text,j.title,j.scope,j.client_id::text as "clientId",j.property_id::text as "propertyId",c.display_name as client,p.address as property,a.asset_type as "equipmentType",a.manufacturer as make,a.model_number as model,a.serial_number as "serialNumber" from jobs j left join clients c on c.id=j.client_id left join properties p on p.id=j.property_id left join lateral (select * from assets a where a.property_id=j.property_id order by a.updated_at desc nulls last limit 1) a on true where j.id=$1::uuid`,[jobId])).rows[0];
  const issue = String(body?.issue || body?.issueDescription || job?.scope || '').trim();
  if (!jobId && !issue) return {ok:false, code:'AI_TROUBLESHOOTING_INPUT_REQUIRED', error:'Describe the issue or select a job.'};
  if (jobId && !job) throw new HttpError(404,'Selected job was not found.');
  const input={...job,...body,jobId:jobId||undefined,workRequestId:workRequestId||undefined,issue,equipmentType:body?.equipmentType||job?.equipmentType||'',make:body?.make||job?.make||'',model:body?.model||job?.model||'',serialNumber:body?.serialNumber||job?.serialNumber||'',disclaimer:'AI troubleshooting is assistance only. Follow company procedures, codes, manufacturer documentation, and safety requirements.'};
  const settings=(await getAiSettings(db)).settings.ai_troubleshooting || DEFAULT_TROUBLESHOOTING_SETTINGS; const model=selectedModel(settings); const relatedId=jobId||workRequestId||null;
  const jobRow=(await db.query(`insert into ai_jobs (module_key,job_type,related_type,related_id,status,stage,input,model,created_by) values ('ai_troubleshooting','diagnostic_report',$1,$2::uuid,'queued','queued',$3::jsonb,$4,$5::uuid) returning id::text`,[jobId?'job':workRequestId?'work_request':'manual',relatedId,JSON.stringify(input),model,user.id])).rows[0];
  await db.query(`insert into ai_runs (id,module_key,related_type,related_id,status,input,model,created_by) values ($1::uuid,'ai_troubleshooting',$2,$3::uuid,'queued',$4::jsonb,$5,$6::uuid)`,[jobRow.id,jobId?'job':workRequestId?'work_request':'manual',relatedId,JSON.stringify(input),model,user.id]).catch(()=>undefined);
  const report=(await db.query(`insert into ai_troubleshooting_reports (job_id,work_request_id,ai_run_id,ai_job_id,status,equipment_type,make,model,error_code,issue,output) values ($1::uuid,$2::uuid,$3::uuid,$3::uuid,'queued',$4,$5,$6,$7,$8,'{}'::jsonb) returning id::text`,[jobId||null,workRequestId||null,jobRow.id,input.equipmentType,input.make,input.model,body.errorCode,issue])).rows[0];
  return {ok:true,status:'queued',aiJobId:jobRow.id,aiRunId:jobRow.id,reportId:report.id,message:'AI troubleshooting started.'};
}
function requireValidAiId(id:string) { if (!id || id === 'undefined' || id === 'null' || !/^[0-9a-f-]{36}$/i.test(id)) throw new HttpError(400, 'AI_REPORT_ID_REQUIRED:AI troubleshooting report id is required.'); }
export async function processTroubleshooting(id:string,user:AuthUser,db:Queryable=createDatabase()) {
  requireValidAiId(id); await ensureAiFoundation(db); await requireLicensedModule('ai_troubleshooting',db);
  const settings=(await getAiSettings(db)).settings.ai_troubleshooting || DEFAULT_TROUBLESHOOTING_SETTINGS; const st=stageSettings(settings);
  const run=(await db.query<any>(`select j.id::text as "aiJobId",j.status,j.stage,j.input,j.output,j.model,j.sources,j.warnings,j.error_code as "errorCode",tr.id::text as "reportId" from ai_jobs j left join ai_troubleshooting_reports tr on tr.ai_job_id=j.id where (j.id=$1::uuid or tr.id=$1::uuid) and j.module_key='ai_troubleshooting' order by j.created_at desc limit 1`,[id])).rows[0];
  if(!run) throw new HttpError(404,'AI job not found');
  if(run.status==='completed'||run.status==='failed') return getTroubleshooting(run.aiJobId,db);
  const body=run.input||{};
  try {
    await db.query(`update ai_jobs set status='running',stage='diagnosing',started_at=coalesce(started_at,now()),updated_at=now() where id=$1`,[run.aiJobId]);
    await db.query(`update ai_runs set status='diagnosing',updated_at=now() where id=$1`,[run.aiJobId]).catch(()=>undefined);
    await db.query(`update ai_troubleshooting_reports set status='diagnosing',updated_at=now() where ai_job_id=$1`,[run.aiJobId]);
    const slim={equipmentType:body.equipmentType,make:body.make,model:body.model,errorCode:body.errorCode,issue:String(body.issue||body.issueDescription||'').slice(0,1000),symptoms:String(body.symptoms||body.notes||'').slice(0,500),jobScope:String(body.scope||'').slice(0,700)};
    const prompt=`Safety-first technician assistant. Return compact JSON: likelyCauses, safetyWarnings, firstChecks, stepByStepDiagnostics, partsPossiblyNeeded, measurementsToTake, whenToStopAndCallSpecialist, customerExplanation, workerSummary, confidence. Input ${JSON.stringify(slim)}`.slice(0,Math.min(st.promptChars,2500));
    const output=normalizeTroubleshootingOutput(await runOpenAiJson(prompt,{},run.model,0.2,15000),[]); output.disclaimer=body.disclaimer; output.warnings=[];
    await db.query(`update ai_troubleshooting_reports set status='complete',output=$2::jsonb,updated_at=now() where ai_job_id=$1`,[run.aiJobId,JSON.stringify(output)]);
    await db.query(`update ai_jobs set status='completed',stage='completed',output=$2::jsonb,warnings='[]'::jsonb,sources='[]'::jsonb,completed_at=now(),updated_at=now() where id=$1`,[run.aiJobId,JSON.stringify(output)]);
    await db.query(`update ai_runs set status='completed',output=$2::jsonb,updated_at=now() where id=$1`,[run.aiJobId,JSON.stringify(output)]).catch(()=>undefined);
    return getTroubleshooting(run.aiJobId,db);
  } catch(e:any){ const code=e.message?.split(':')[0]==='AI_TIMEOUT'?'AI_TIMEOUT':(e.message?.split(':')[0]||'AI_ERROR'); await db.query(`update ai_jobs set status='failed',stage='failed',error_code=$2,error_message=$3,completed_at=now(),updated_at=now() where id=$1`,[run.aiJobId,code,e.message||code]); await db.query(`update ai_troubleshooting_reports set status='failed',updated_at=now() where ai_job_id=$1`,[run.aiJobId]); await db.query(`update ai_runs set status='failed',error_message=$2,updated_at=now() where id=$1`,[run.aiJobId,code]).catch(()=>undefined); return getTroubleshooting(run.aiJobId,db); }
}
export async function getTroubleshooting(id:string,db:Queryable=createDatabase()) { requireValidAiId(id); await ensureAiFoundation(db); const row=(await db.query<any>(`select j.id::text as "aiJobId",j.status,j.stage,j.input,j.output,j.error_code,j.error_message,j.created_at::text,j.updated_at::text,j.sources,j.warnings,j.model,tr.id::text,tr.status as "reportStatus",tr.equipment_type,tr.make,tr.model as report_model,tr.error_code as report_error_code,tr.issue,tr.output as report_output,tr.created_at::text as "reportCreatedAt",tr.updated_at::text as "reportUpdatedAt" from ai_jobs j left join ai_troubleshooting_reports tr on tr.ai_job_id=j.id where (j.id=$1::uuid or tr.id=$1::uuid) and j.module_key='ai_troubleshooting' order by j.created_at desc limit 1`,[id])).rows[0]; if(!row) throw new HttpError(404,'Report not found'); const input=row.input||{}; const status=row.status==='completed'?'complete':row.status; const report={ id: row.id || row.aiJobId, aiJobId: row.aiJobId, aiRunId: row.aiJobId, status, stage: row.stage, equipment_type: row.equipment_type || input.equipmentType || '', make: row.make || input.make || '', model: row.report_model || input.model || '', error_code: row.report_error_code || input.errorCode || '', issue: row.issue || input.issue || input.issueDescription || '', output: normalizeTroubleshootingOutput(row.report_output || row.output || {}, row.sources||[]), error_message: row.error_message || '', error_code_raw: row.error_code || '', created_at: row.reportCreatedAt || row.created_at, updated_at: row.reportUpdatedAt || row.updated_at, modelName: row.model }; return {ok:true,status:row.status,stage:row.stage,aiJobId:row.aiJobId,report,record:report,sources:row.sources||[],warnings:row.warnings||[]}; }
export async function troubleshootingAction(id:string, action:string, body:any, db:Queryable=createDatabase()) { await ensureAiFoundation(db); if(action==='save-to-job'){ await db.query(`update ai_troubleshooting_reports set job_id=coalesce($2::uuid,job_id),status='saved',updated_at=now() where id=$1`,[id,body.jobId||null]); return {ok:true,id,status:'saved'}; } if(action==='create-checklist'){ await db.query(`update ai_troubleshooting_reports set status='checklist_created',updated_at=now() where id=$1::uuid`,[id]); return {ok:true,id,status:'checklist_created'}; } throw new HttpError(405,'Method not allowed'); }
